import type { InhaltsModul } from '@lehrunterlagen/schema';

// Deutsch — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const deutschInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-deutsch-maerchen-sagen',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'unterstufe',
    schulstufe: 5,
    titel: 'Märchen, Sagen und Fabeln',
    beschreibung: 'Einfache literarische Gattungen und ihre Merkmale, Erzählstrukturen und Moral.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-kinderliteratur',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Kinder- und Jugendliteratur',
    beschreibung: 'Kinderromane, Gedichte und kurze Erzählungen mit Fokus auf Figuren und Handlung.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-balladen',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Balladen und Kurzgeschichten',
    beschreibung: 'Literarische Gattungen, Motive und historische Kontexte.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-drama',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Drama und Roman',
    beschreibung: 'Komplexere literarische Werke, Textanalyse und Interpretation.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-klassik-romantik',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Weimarer Klassik und Romantik',
    beschreibung: 'Literarische Epochen, zentrale Werke und historische Einordnung.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-vormaerz-realismus',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Vormärz, Realismus und Moderne',
    beschreibung: 'Epochenübergreifende Analyse und theoretische Perspektiven.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-moderne-nachkrieg',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Moderne und Nachkriegsliteratur',
    beschreibung: 'Kafka, Celan, Bachmann und literarische Traditionen nach 1945.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
  {
    id: 'at-deutsch-gegenwart',
    rahmenwerk: 'at-lehrplan',
    fach: 'deutsch',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Gegenwartsliteratur und Medien',
    beschreibung: 'Aktuelle literarische Positionen, Identität und Erinnerung.',
    quelle: 'BMBWF-Lehrplan AHS Deutsch — RIS, Stand 2023',
  },
];
