import type { InhaltsModul } from '@lehrunterlagen/schema';

// Englisch — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const englischInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-englisch-alltag',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'unterstufe',
    schulstufe: 5,
    titel: 'Everyday Life and Personal World',
    beschreibung: 'Familie, Schule, Hobbys und tägliche Routinen auf A1-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-reisen',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Travel and Cultural Exchange',
    beschreibung: 'Reisen, Essen, Feste und interkulturelle Begegnungen auf A2-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-medien',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Media and Digital Communication',
    beschreibung: 'Soziale Medien, Nachrichten und digitale Kommunikation auf A2/B1-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-umwelt',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Environment and Sustainability',
    beschreibung: 'Klimawandel, Umweltschutz und nachhaltige Lebensweisen auf B1-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-globalisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Globalization and Migration',
    beschreibung: 'Internationale Mobilität, kulturelle Vielfalt und Identität auf B1/B2-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-literatur',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Literature and Creative Expression',
    beschreibung: 'Kurzgeschichten, Gedichte und kreative Schreibformen auf B2-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-politik',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Politics and Social Issues',
    beschreibung: 'Demokratie, Menschenrechte und gesellschaftliche Debatten auf B2-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
  {
    id: 'at-englisch-wissenschaft',
    rahmenwerk: 'at-lehrplan',
    fach: 'englisch',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Science and Future Challenges',
    beschreibung: 'Wissenschaftliche Diskurse, Technologie und Zukunftsfragen auf B2/C1-Niveau.',
    quelle: 'BMBWF-Lehrplan AHS Englisch — RIS, Stand 2023',
  },
];
