import type { InhaltsModul } from '@lehrunterlagen/schema';

// Ethik — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const ethikInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-ethik-identitaet',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Identität und Selbstverständnis',
    beschreibung: 'Personale Identität, Autonomie und Verantwortung.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-gemeinschaft',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Gemeinschaft und soziale Beziehungen',
    beschreibung: 'Familie, Freundschaft, Liebe und soziale Normen.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-gerechtigkeit',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Gerechtigkeit und Menschenrechte',
    beschreibung: 'Soziale Gerechtigkeit, Gleichheit und Menschenwürde.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-umwelt',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Umweltethik und Nachhaltigkeit',
    beschreibung: 'Klimawandel, Tierethik und Verantwortung für zukünftige Generationen.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-medizin',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Medizinethik und Biopolitik',
    beschreibung: 'Sterbehilfe, Gentechnik und ethische Grenzfälle.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-technologie',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Technologie und Digitalisierung',
    beschreibung: 'Künstliche Intelligenz, Datenschutz und digitale Autonomie.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-philosophie',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Philosophische Ethik',
    beschreibung: 'Utilitarismus, Pflichtethik, Tugendethik und zeitgenössische Positionen.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
  {
    id: 'at-ethik-globalisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'ethik',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Globalisierung und Verantwortung',
    beschreibung: 'Globale Gerechtigkeit, Migration und kosmopolitische Ethik.',
    quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023',
  },
];
