import type { InhaltsModul } from '@lehrunterlagen/schema';

// Geographie — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const geographieInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-geographie-heimatraum',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 5,
    titel: 'Heimatraum und Österreich',
    beschreibung: 'Landschaftsformen, Siedlungsstrukturen und wirtschaftliche Nutzung im unmittelbaren Lebensraum.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-europa',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Europa – Vielfalt und Integration',
    beschreibung: 'Naturräume, Kulturlandschaften und wirtschaftliche Zusammenarbeit in der EU.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-erde-natur',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Physische Geographie der Erde',
    beschreibung: 'Klimazonen, Plattentektonik, Naturgefahren und Anpassungsstrategien.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-bevoelkerung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Bevölkerung und Urbanisierung',
    beschreibung: 'Demographischer Übergang, Migration, Stadtentwicklung und Megastädte.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-globalisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Globalisierung und Wirtschaft',
    beschreibung: 'Wertschöpfungsketten, Standorttheorien und regionale Disparitäten.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-entwicklung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Entwicklung und Ressourcen',
    beschreibung: 'Entwicklungsländer, Schwellenländer, Tourismus und nachhaltige Entwicklung.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-geopolitik',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Geopolitik und Nachhaltigkeit',
    beschreibung: 'Klimawandel, Ressourcenkonflikte und internationale Wirtschaftsbeziehungen.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
  {
    id: 'at-geographie-zukunft',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Zukunftsfragen der Raumgestaltung',
    beschreibung: 'Digitalisierung, Deglobalisierung und gesellschaftliche Debatten um Nachhaltigkeit.',
    quelle: 'BMBWF-Lehrplan AHS Geographie und Wirtschaftskunde — RIS, Stand 2023',
  },
];
