import type { InhaltsModul } from '@lehrunterlagen/schema';

export const geographieInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-geographie-klima-vegetation',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Klima- und Vegetationszonen',
    beschreibung: 'Zusammenhänge von Klimaelementen, Großklimazonen und charakteristischen Ökosystemen der Erde.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geographie — nicht offiziell zitiert',
  },
  {
    id: 'at-geographie-oesterreich-landschaften',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Österreich: Natur- und Kulturlandschaften',
    beschreibung: 'Räumliche Strukturen Österreichs, ihre naturräumliche Vielfalt und kulturelle Prägung.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geographie — nicht offiziell zitiert',
  },
  {
    id: 'at-geographie-bevoelkerung-migration',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Bevölkerung & Migration',
    beschreibung: 'Bevölkerungsentwicklung, Wanderungsbewegungen und deren räumliche Folgen im 21. Jahrhundert.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geographie — nicht offiziell zitiert',
  },
  {
    id: 'at-geographie-wirtschaftsraeume-globalisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Wirtschaftsräume und Globalisierung',
    beschreibung: 'Globale Arbeitsteilung, Wirtschaftszentren, Lieferketten und regionale Entwicklungsunterschiede.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geographie — nicht offiziell zitiert',
  },
  {
    id: 'at-geographie-umwelt-nachhaltigkeit',
    rahmenwerk: 'at-lehrplan',
    fach: 'geographie',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Umwelt und nachhaltige Entwicklung',
    beschreibung: 'Globale Umweltprobleme, Ressourcennutzung und Ansätze einer nachhaltigen Entwicklung.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geographie — nicht offiziell zitiert',
  },
];
