import type { InhaltsModul } from '@lehrunterlagen/schema';

export const geschichteInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-geschichte-roemer',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Die Römer in Europa',
    beschreibung: 'Vom römischen Reich über Alltag und Verwaltung bis zu dessen langfristigen kulturellen Spuren in Europa.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-mittelalter',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Das Mittelalter',
    beschreibung: 'Lebenswelten im Früh- und Hochmittelalter, Feudalismus, Kirche und erste Städte.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-amerika',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Die Entdeckung Amerikas',
    beschreibung: 'Europäische Expansion, Konflikte mit indigenen Völkern und globale Verflechtungen.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-industrialisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Industrialisierung',
    beschreibung: 'Technischer Wandel, Soziale Frage, Urbanisierung und ihre Auswirkungen bis heute.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-franzoesische-revolution',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Französische Revolution',
    beschreibung: 'Ursachen, Verlauf und europäische Wirkung der Revolution von 1789.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-erster-weltkrieg',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Erster Weltkrieg',
    beschreibung: 'Krisenjahre vor 1914, Kriegsverlauf, Kriegsgesellschaft und das Ende der Donaumonarchie.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
  {
    id: 'at-geschichte-zweiter-weltkrieg-holocaust',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Zweiter Weltkrieg und Holocaust',
    beschreibung: 'Totaler Krieg, Verbrechen des NS-Regimes, Widerstand und Erinnerungskultur.',
    quelle: 'Entwurf, angelehnt an BMBWF-Lehrplan AHS Geschichte — nicht offiziell zitiert',
  },
];
