import type { InhaltsModul } from '@lehrunterlagen/schema';

// Geschichte — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const geschichteInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-geschichte-antike',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Antike Hochkulturen',
    beschreibung: 'Griechische Polis, Römisches Reich, Demokratie und Republik als Grundlagen europäischer Kultur.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-mittelalter',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Mittelalter und frühe Neuzeit',
    beschreibung: 'Feudalismus, Kirche, Kreuzzüge, Renaissance und Reformation als Umbruchszeiten.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-aufklaerung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Aufklärung und Revolutionen',
    beschreibung: 'Aufklärung, Französische Revolution, Industrialisierung und ihre gesellschaftlichen Folgen.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-imperialismus',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Imperialismus und Erster Weltkrieg',
    beschreibung: 'Kolonialismus, Nationalismus, Erster Weltkrieg und die Neuordnung Europas.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-zwischenkrieg',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Zwischenkriegszeit und Nationalsozialismus',
    beschreibung: 'Weimarer Republik, Ständestaat, NS-Diktatur, Holocaust und Zweiter Weltkrieg.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-zweite-republik',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Zweite Republik und Kalter Krieg',
    beschreibung: 'Besatzungszeit, Staatsvertrag, Neutralität, Ost-West-Konflikt und europäische Integration.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-globalisierung',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Globalisierung und Gegenwart',
    beschreibung: 'Ende des Kalten Krieges, EU-Erweiterung, 9/11, Migration und aktuelle globale Herausforderungen.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
  {
    id: 'at-geschichte-erinnerungskultur',
    rahmenwerk: 'at-lehrplan',
    fach: 'geschichte',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Erinnerungskultur und Geschichtspolitik',
    beschreibung: 'Denkmäler, Gedenktage, Museen und die politische Nutzung von Geschichte.',
    quelle: 'BMBWF-Lehrplan AHS Geschichte — RIS, Stand 2023',
  },
];
