import type { InhaltsModul } from '@lehrunterlagen/schema';

// Latein — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const lateinInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-latein-grundlagen',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Grundlagen der lateinischen Sprache',
    beschreibung: 'Deklinationen, Konjugationen und einfache Satzstrukturen.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-roemischer-alltag',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Römischer Alltag und Gesellschaft',
    beschreibung: 'Familie, Sklaverei, Wohnen und Leben im antiken Rom.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-geschichte',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Römische Geschichte und Politik',
    beschreibung: 'Republik, Kaiserzeit und politische Institutionen.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-mythologie',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Griechische und römische Mythologie',
    beschreibung: 'Götter, Helden und mythologische Erzählungen in lateinischen Texten.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-philosophie',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Antike Philosophie und Ethik',
    beschreibung: 'Stoa, Epikureismus und philosophische Texte (Seneca, Cicero).',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-literatur',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Römische Literatur und Dichtung',
    beschreibung: 'Vergil, Ovid, Horaz und literarische Gattungen.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
  {
    id: 'at-latein-rezeption',
    rahmenwerk: 'at-lehrplan',
    fach: 'latein',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Rezeption und europäische Tradition',
    beschreibung: 'Einfluss des Lateinischen auf europäische Sprachen, Recht und Kultur.',
    quelle: 'BMBWF-Lehrplan AHS Latein — RIS, Stand 2023',
  },
];
