import type { InhaltsModul } from '@lehrunterlagen/schema';

// Religion — Inhalts-Module (Themenbereiche), generiert aus Lehrplan-Recherche.

export const religionInhaltsModule: InhaltsModul[] = [
  {
    id: 'at-religion-identitaet',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'unterstufe',
    schulstufe: 5,
    titel: 'Identität und Gemeinschaft',
    beschreibung: 'Selbstwahrnehmung, Freundschaft und religiöse Zugehörigkeit.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-bibel',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'unterstufe',
    schulstufe: 6,
    titel: 'Bibel und religiöse Texte',
    beschreibung: 'Altes und Neues Testament, Erzählungen und ihre Bedeutung.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-weltreligionen',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'unterstufe',
    schulstufe: 7,
    titel: 'Weltreligionen und Dialog',
    beschreibung: 'Judentum, Islam, Buddhismus und interreligiöser Dialog.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-ethik',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'unterstufe',
    schulstufe: 8,
    titel: 'Ethische Fragen und Werte',
    beschreibung: 'Gerechtigkeit, Verantwortung und moralische Entscheidungen.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-kirche',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'oberstufe',
    schulstufe: 9,
    titel: 'Kirche und Geschichte',
    beschreibung: 'Kirchengeschichte, Reformation und moderne Herausforderungen.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-sinn',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'oberstufe',
    schulstufe: 10,
    titel: 'Sinnfragen und Spiritualität',
    beschreibung: 'Leid, Tod, Hoffnung und spirituelle Suche.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-gesellschaft',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'oberstufe',
    schulstufe: 11,
    titel: 'Religion und Gesellschaft',
    beschreibung: 'Religion im öffentlichen Raum, Säkularisierung und Fundamentalismus.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
  {
    id: 'at-religion-philosophie',
    rahmenwerk: 'at-lehrplan',
    fach: 'religion',
    stufe: 'oberstufe',
    schulstufe: 12,
    titel: 'Theologie und Philosophie',
    beschreibung: 'Gottesfrage, Theodizee und religiöse Sprachformen.',
    quelle: 'BMBWF-Lehrplan AHS Religionsunterricht — RIS, Stand 2023',
  },
];
