import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Deutsch — Lehrplan-Deskriptoren + Stoff-Items (Rahmenwerk at-lehrplan).
// `bereich`/`kategorie` verwenden die Namen aus KOMPETENZBEREICHE['deutsch'] wortgleich.
// Deskriptoren sind kuratierte Entwürfe (siehe `quelle`).

const Q = (stufe: string) =>
  `Entwurf, angelehnt an BMBWF-Lehrplan AHS Deutsch ${stufe} — nicht offiziell zitiert`;

// Deutsch — gemischt: gesourcte Skill-Deskriptoren aus Lehrplan-Recherche
// plus erhaltene kuratierte Grammatik-/Wortschatz-/Sprachmittlungs-/Literatur-Blöcke.

export const deutschDeskriptoren: Deskriptor[] = [
  // Zuhören & Sprechen — Unterstufe
  { id: 'at-deutsch-un-zuhoeren-sprechen-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können Inhalte aus unterschiedlichen medialen Beiträgen erschließen, Absichten und Emotionen wahrnehmen, Wissen sichern, wiedergeben und der Situation angemessen reagieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-zuhoeren-sprechen-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können bereits bekannte verbale und nonverbale Mittel variieren, monologische und dialogische Sprechbeiträge planen und ausführen, um adressaten- und situationsgerecht zu kommunizieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-zuhoeren-sprechen-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können aus unterschiedlichen Quellen Informationen einholen, aufbereiten und mündlich präsentieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-zuhoeren-sprechen-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können einfache Formen der Argumentation anwenden.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  // Zuhören & Sprechen — Oberstufe
  { id: 'at-deutsch-ob-zuhoeren-sprechen-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können in unterschiedlichen Beiträgen, im direkten Kontakt oder über Medien vermittelt, Mehrdeutigkeiten und nicht explizit genannte Inhalte erschließen und interpretieren, dabei Absichten und Emotionen reflektieren und situationsbezogen Schlüsse daraus ziehen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-zuhoeren-sprechen-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können ihr Repertoire verbaler und nonverbaler Mittel erweitern und Sprache unter Verwendung unterschiedlicher sprachlicher Register (Standard- und Bildungssprache) reflektiert und bewusst kreativ einsetzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-zuhoeren-sprechen-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können aus bewusst gewählten Quellen Informationen gezielt herausfiltern, thematisch aufbereiten und unter Anwendung entsprechender Visualisierungsmethoden mündlich präsentieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  // Lesen & Textverständnis — Unterstufe
  { id: 'at-deutsch-un-lesen-text-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können sinnerfassend, mit zunehmender Leseflüssigkeit und unter Anwendung geeigneter Lesestrategien lesen und vorlesen, Inhalte entnehmen und darüber kommunizieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-lesen-text-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können subjektive und kreative Zugänge zu literarischen Werken in unterschiedlichen künstlerischen Erscheinungsformen finden und zur Anschlusskommunikation nutzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-lesen-text-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können die Art der Aufbereitung von Beiträgen in unterschiedlichen Mediensystemen erkennen und darüber sprechen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-lesen-text-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können mit Internetquellen sorgsam und dem Datenschutz gemäß umgehen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  // Lesen & Textverständnis — Oberstufe
  { id: 'at-deutsch-ob-lesen-text-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können pragmatische und literarische Texte und Medien in unterschiedlichen Darbietungsformen rezipieren, deren Inhalt, Form und Sprache erschließen und ihre Entstehungszusammenhänge erfassen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-lesen-text-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können eigene Leseinteressen vertiefen, eine dynamische und vielfältige Lesebiografie entwickeln und sich differenziert mit anderen darüber austauschen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-lesen-text-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können Texte mit Hilfe szenischer Mittel vortragen, darstellen und mit anderen künstlerischen Ausdrucksformen vergleichen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-lesen-text-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können die Aufbereitung und Gestaltung von Themen und Inhalten medialer Beiträge erkennen und vergleichen und dabei Informationssysteme differenziert und kritisch nutzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  // Schreiben — Unterstufe
  { id: 'at-deutsch-un-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Erlebnisse, Erfahrungen und Gedanken verschriftlichen sowie persönliche Beziehungen und Absichten ausdrücken, auch in kreativer Form.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können schriftlich informieren und darstellen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Textverarbeitungsprogramme zur digitalen Textproduktion einsetzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können einfache Argumente schriftlich formulieren und auf Aussagen anderer sprachlich und inhaltlich angemessen reagieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  // Schreiben — Oberstufe
  { id: 'at-deutsch-ob-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche Impulse und Vorlagen für eigene pragmatische und kreative Schreibprozesse nutzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können zu strittigen Sachverhalten, unter Einbeziehung differenzierter Quellen, argumentierend schreiben und auf Gegenargumente eingehen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Textverarbeitungsprogramme zur Gestaltung umfangreicherer multimedialer Texte, auch im Team, nutzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Bedeutungswandel der Schrift und des Schreibens in analogen, digitalen und multimodalen Settings reflektieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  // Sprachbewusstsein — Unterstufe
  { id: 'at-deutsch-un-sprachbewusstsein-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können Einsichten in Rechtschreibung und Grammatik hinsichtlich Gebrauch und Funktion anwenden.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-sprachbewusstsein-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können differenzierte Fertigkeiten im Bereich von Wort-, Satz- und Textgrammatik unter Berücksichtigung ihrer stilistischen Auswirkungen nutzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-un-sprachbewusstsein-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können Kennzeichen mündlicher, schriftlich-textueller und multimodaler Kommunikation im Kontext von Mehrsprachigkeit reflektieren.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Unterstufe) — RIS, Stand 2023' },
  // Sprachbewusstsein — Oberstufe
  { id: 'at-deutsch-ob-sprachbewusstsein-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können vertieftes Verständnis von sprachlichen Strukturen und Regeln (Variation und Vergleich) entwickeln.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-sprachbewusstsein-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können sich mit Soziolekten, Dialekten, Fachsprachen, Idiolekten und deren Abweichungen von der Standardsprache auseinandersetzen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-deutsch-ob-sprachbewusstsein-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können Einsicht in die Sprachverwendung im Kontext von Mehrsprachigkeit gewinnen.', quelle: 'BMBWF-Lehrplan AHS Deutsch (Oberstufe) — RIS, Stand 2023' },
  // Literarische Bildung — Unterstufe
  { id: 'at-de-un-lit-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen können literarische Texte lesen, Inhalt und Aussage erfassen.', quelle: Q('Unterstufe') },
  { id: 'at-de-un-lit-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen können Figuren, Handlung und Sprache in literarischen Texten beschreiben.', quelle: Q('Unterstufe') },
  // Literarische Bildung — Oberstufe
  { id: 'at-de-ob-lit-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen können literarische Werke im historischen und kulturellen Kontext interpretieren.', quelle: Q('Oberstufe') },
  { id: 'at-de-ob-lit-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen können ästhetische, ethische und gesellschaftliche Fragestellungen an literarischen Texten entwickeln.', quelle: Q('Oberstufe') },
  // Grammatik — Unterstufe
  { id: 'at-de-un-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die wichtigsten Zeitformen (Präsens, Präteritum, Perfekt) unterscheiden und richtig bilden.', quelle: '' },
  { id: 'at-de-un-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Satzglieder (Subjekt, Prädikat, Akkusativ-/Dativobjekt) erkennen und bestimmen.', quelle: '' },
  { id: 'at-de-un-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die wichtigsten Wortarten (Nomen, Verb, Adjektiv, Adverb, Pronomen) bestimmen.', quelle: '' },
  { id: 'at-de-un-gramm-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können einfache Kommasetzungsregeln (Haupt- und Nebensatz, Aufzählung) anwenden.', quelle: '' },
  { id: 'at-de-un-gramm-5', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Aktiv- und Passivsätze unterscheiden und einfache Passivformen bilden.', quelle: '' },
  // Grammatik — Oberstufe
  { id: 'at-de-ob-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Tempus und Modus (Indikativ, Konjunktiv I und II) sicher unterscheiden und gezielt einsetzen.', quelle: '' },
  { id: 'at-de-ob-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Konjunktiv I und II in der indirekten Rede und in irreale Bedingungssätzen anwenden.', quelle: '' },
  { id: 'at-de-ob-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können komplexe Kommasetzungsregeln (Nebensätze, Infinitivkonstruktionen, Einschübe) korrekt anwenden.', quelle: '' },
  { id: 'at-de-ob-gramm-4', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Satzglieder und Satzgefüge analysieren sowie Syntax-Fehler begründen.', quelle: '' },
  { id: 'at-de-ob-gramm-5', rahmenwerk: 'at-lehrplan', fach: 'deutsch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Wortarten und Wortbildung im Kontext grammatisch reflektieren und terminologisch benennen.', quelle: '' },
];

export const deutschStoffItems: StoffItem[] = [
  // Zuhören & Sprechen
  { id: 'de-zuh-ren-und-sprechen-un', rahmenwerk: 'at-lehrplan', titel: 'Zuhören & Sprechen', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Zuhören & Sprechen', deskriptorIds: ['at-deutsch-un-zuhoeren-sprechen-1', 'at-deutsch-un-zuhoeren-sprechen-2', 'at-deutsch-un-zuhoeren-sprechen-3', 'at-deutsch-un-zuhoeren-sprechen-4'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'de-zuh-ren-und-sprechen-ob', rahmenwerk: 'at-lehrplan', titel: 'Zuhören & Sprechen', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Zuhören & Sprechen', deskriptorIds: ['at-deutsch-ob-zuhoeren-sprechen-1', 'at-deutsch-ob-zuhoeren-sprechen-2', 'at-deutsch-ob-zuhoeren-sprechen-3'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  // Lesen & Textverständnis
  { id: 'de-lesen-und-textverst-ndnis-un', rahmenwerk: 'at-lehrplan', titel: 'Lesen & Textverständnis', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Lesen & Textverständnis', deskriptorIds: ['at-deutsch-un-lesen-text-1', 'at-deutsch-un-lesen-text-2', 'at-deutsch-un-lesen-text-3', 'at-deutsch-un-lesen-text-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  { id: 'de-lesen-und-textverst-ndnis-ob', rahmenwerk: 'at-lehrplan', titel: 'Lesen & Textverständnis', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Lesen & Textverständnis', deskriptorIds: ['at-deutsch-ob-lesen-text-1', 'at-deutsch-ob-lesen-text-2', 'at-deutsch-ob-lesen-text-3', 'at-deutsch-ob-lesen-text-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  // Schreiben
  { id: 'de-schreiben-un', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Schreiben', deskriptorIds: ['at-deutsch-un-schreiben-1', 'at-deutsch-un-schreiben-2', 'at-deutsch-un-schreiben-3', 'at-deutsch-un-schreiben-4'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'de-schreiben-ob', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Schreiben', deskriptorIds: ['at-deutsch-ob-schreiben-1', 'at-deutsch-ob-schreiben-2', 'at-deutsch-ob-schreiben-3', 'at-deutsch-ob-schreiben-4'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  // Sprachbewusstsein
  { id: 'de-sprachbewusstsein-un', rahmenwerk: 'at-lehrplan', titel: 'Sprachbewusstsein', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Sprachbewusstsein', deskriptorIds: ['at-deutsch-un-sprachbewusstsein-1', 'at-deutsch-un-sprachbewusstsein-2', 'at-deutsch-un-sprachbewusstsein-3'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-sprachbewusstsein-ob', rahmenwerk: 'at-lehrplan', titel: 'Sprachbewusstsein', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Sprachbewusstsein', deskriptorIds: ['at-deutsch-ob-sprachbewusstsein-1', 'at-deutsch-ob-sprachbewusstsein-2', 'at-deutsch-ob-sprachbewusstsein-3'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  // Literarische Bildung
  { id: 'de-literatur-un', rahmenwerk: 'at-lehrplan', titel: 'Literarische Texte lesen und beschreiben', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Literarische Bildung', deskriptorIds: ['at-de-un-lit-1', 'at-de-un-lit-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'offeneSchreibaufgabe'] },
  { id: 'de-literatur-ob', rahmenwerk: 'at-lehrplan', titel: 'Literatur im historischen und kulturellen Kontext', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Literarische Bildung', deskriptorIds: ['at-de-ob-lit-1', 'at-de-ob-lit-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  // Grammatik
  { id: 'de-zeiten-un', rahmenwerk: 'at-lehrplan', titel: 'Zeiten (Präsens, Präteritum, Perfekt)', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-un-gramm-1'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'de-satzglieder-un', rahmenwerk: 'at-lehrplan', titel: 'Satzglieder', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-un-gramm-2'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice', 'markieraufgabe'] },
  { id: 'de-wortarten-un', rahmenwerk: 'at-lehrplan', titel: 'Wortarten', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-un-gramm-3'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice', 'markieraufgabe'] },
  { id: 'de-kommasetzung-un', rahmenwerk: 'at-lehrplan', titel: 'Kommasetzung', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-un-gramm-4'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'de-passiv-un', rahmenwerk: 'at-lehrplan', titel: 'Aktiv und Passiv', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-un-gramm-5'], defaultAufgabentypen: ['fehlerkorrektur'] },
  { id: 'de-konjunktiv-ob', rahmenwerk: 'at-lehrplan', titel: 'Konjunktiv I und II', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-ob-gramm-1', 'at-de-ob-gramm-2'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext'] },
  { id: 'de-kommasetzung-ob', rahmenwerk: 'at-lehrplan', titel: 'Kommasetzung (komplex)', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-ob-gramm-3'], defaultAufgabentypen: ['fehlerkorrektur'] },
  { id: 'de-satzgefüge-ob', rahmenwerk: 'at-lehrplan', titel: 'Satzglieder und Satzgefüge', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-ob-gramm-4'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice', 'markieraufgabe'] },
  { id: 'de-wortarten-ob', rahmenwerk: 'at-lehrplan', titel: 'Wortarten und Wortbildung', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-ob-gramm-5'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'de-mixed-grammar-ob', rahmenwerk: 'at-lehrplan', titel: 'Mixed Grammar (Oberstufenwiederholung)', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-de-ob-gramm-1', 'at-de-ob-gramm-3', 'at-de-ob-gramm-4'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
];
