import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Englisch — Lehrplan-Deskriptoren + Stoff-Items (Rahmenwerk at-lehrplan).
// `bereich`/`kategorie` verwenden die Namen aus KOMPETENZBEREICHE['englisch'] wortgleich.
// Deskriptoren sind kuratierte Entwürfe (siehe `quelle`).

const Q = (stufe: string) =>
  `Entwurf, angelehnt an BMBWF-Lehrplan AHS Englisch ${stufe} — nicht offiziell zitiert`;

// Englisch — gemischt: gesourcte Skill-Deskriptoren aus Lehrplan-Recherche
// plus erhaltene kuratierte Grammatik-/Wortschatz-/Sprachmittlungs-/Literatur-Blöcke.

export const englischDeskriptoren: Deskriptor[] = [
  // Hören — Unterstufe
  { id: 'at-englisch-un-hoeren-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können, wenn sehr langsam, klar und deutlich in Standardsprache gesprochen wird, in kurzen Dialogen oder Monologen einfache Fragen und Sätze, die sich auf sie selbst und ihr persönliches Umfeld beziehen, verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-hoeren-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können einfache alltägliche Kommunikation im Unterricht verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-hoeren-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können, wenn langsam, klar und deutlich in Standardsprache gesprochen wird, Anweisungen, Fragen und Auskünfte verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-hoeren-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können kurze einfache Gespräche und Texte über vertraute Themen verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-hoeren-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können, wenn klar und deutlich und nicht zu schnell in Standardsprache gesprochen wird, einfache Gespräche, Erzählungen und kurze Medienbeiträge verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-hoeren-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können, wenn in klarer und deutlicher Standardsprache gesprochen wird, Gespräche, kurze Erzählungen, Präsentationen, Filme und kurze Medienbeiträge über vertraute Themen verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  // Hören — Oberstufe
  { id: 'at-englisch-ob-hoeren-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können genug verstehen, um Bedürfnisse konkreter Art befriedigen zu können, sofern deutlich und langsam gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-hoeren-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können die Hauptpunkte verstehen, wenn in deutlich artikulierter Standardsprache über vertraute Dinge gesprochen wird, denen man normalerweise in der Ausbildung oder der Freizeit begegnet.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-hoeren-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte Sachinformationen über gewöhnliche alltags-, berufs- oder ausbildungsbezogene Themen verstehen und dabei die Hauptaussagen und Einzelinformationen erkennen, sofern klar artikuliert und mit vertrautem Akzent gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-hoeren-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können längeren Redebeiträgen und komplexer Argumentation folgen, sofern die Thematik einigermaßen vertraut und der Rede- oder Gesprächsverlauf durch explizite Signale gekennzeichnet ist.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-hoeren-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können Hauptaussagen und spezifische Informationen von inhaltlich und sprachlich komplexen Redebeiträgen zu konkreten und abstrakten Themen verstehen, wenn Standardsprache gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-hoeren-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können im direkten Kontakt und in den Medien gesprochene Standardsprache verstehen, wenn es um vertraute oder auch um weniger vertraute Themen geht.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  // Lesen — Unterstufe
  { id: 'at-englisch-un-lesen-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können einfache Arbeitsanweisungen und Mitteilungen verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-lesen-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können sehr einfache Texte über vertraute Themen verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-lesen-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurze einfache Geschichten, Briefe, E-Mails oder bebilderte Sachtexte verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-lesen-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurzen vertrauten Alltagstexten wichtige Informationen entnehmen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-lesen-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können einfache und konkrete Artikel in Magazinen und Jugendzeitschriften, altersadäquate Kinder- und Jugendbücher, Geschichten und Sachtexte sowie persönliche Texte, die sich auf altersgerechte Aspekte der zielsprachlichen Kultur(en) beziehen, verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-lesen-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können einfache klar strukturierte Jugendliteratur oder Sachliteratur mit befriedigendem Verständnis lesen und darin enthaltene Einstellungen erkennen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  // Lesen — Oberstufe
  { id: 'at-englisch-ob-lesen-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurze, einfache Texte zu vertrauten, konkreten Themen verstehen, in denen gängige Alltagssprache verwendet wird.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-lesen-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können konkrete, unkomplizierte Texte über vertraute Themen mit befriedigendem Verständnis lesen, die wesentlichen Punkte erfassen und wichtige Informationen auffinden.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-lesen-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte, auch literarische Texte über vertraute Themen mit befriedigendem Verständnis lesen und wichtige Informationen auffinden.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-lesen-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können längere Texte, auch Berichte und Artikel, zu aktuellen Fragen sowie literarische Texte selbstständig lesen und verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-lesen-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können die Hauptaussagen von inhaltlich und sprachlich komplexen Texten, auch literarischen, zu konkreten und abstrakten Themen verstehen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-lesen-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können ein breites Spektrum an Texten (auch literarischen) auch zu weniger vertrauten Themen verstehen und die Hauptaussagen sowie spezifische Informationen und implizite Bedeutungen erfassen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  // An Gesprächen teilnehmen — Unterstufe
  { id: 'at-englisch-un-gespraeche-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können zu alltäglichen und persönlichen Themen an Gesprächen teilnehmen und sich mit Hilfe des Gesprächspartners auf einfache Art verständigen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-gespraeche-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können einfache Fragen stellen und beantworten.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-gespraeche-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können in einfachen zusammenhängenden Sätzen kurze Gespräche über vertraute Themen führen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-gespraeche-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können in einfacher Sprache ein Gespräch beginnen, weiterführen und beenden sowie einfache Sprecherwechsel durchführen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-gespraeche-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können sich in routinemäßigen Situationen über vertraute Themen ohne große Mühe verständigen (ua. Zustimmung oder Ablehnung ausdrücken, Vorschläge machen, über Pläne reden, Rat erbitten und geben, einfache Begründungen vorbringen, die eigene Meinung und Vermutungen formulieren).', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  // An Gesprächen teilnehmen — Oberstufe
  { id: 'at-englisch-ob-gespraeche-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können ohne Vorbereitung an Gesprächen über vertraute Themen teilnehmen und Informationen austauschen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-gespraeche-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können die eigene Meinung und Gefühle ausdrücken und darauf reagieren sowie für Ansichten, Pläne oder Handlungen Begründungen oder Erklärungen geben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-gespraeche-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können ein Gespräch oder eine Diskussion aufrechterhalten und dabei kurz zu den Standpunkten anderer Stellung nehmen, Vergleiche anstellen und verschiedene Möglichkeiten angeben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  // Zusammenhängend sprechen — Unterstufe
  { id: 'at-englisch-un-zusammenhaengend-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können beim zusammenhängenden Sprechen in einfachen Sätzen über vertraute Themen (ua. Familie, Freunde, Tagesablauf, Hobbys, Schule) sprechen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  // Zusammenhängend sprechen — Oberstufe
  { id: 'at-englisch-ob-zusammenhaengend-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können kurz und einfach über ein Ereignis, gegenwärtige oder vergangene Aktivitäten oder Tätigkeiten berichten und sich darüber austauschen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-zusammenhaengend-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können relativ flüssig eine unkomplizierte zusammenhängende Beschreibung zu vertrauten Themen (auch Filme, literarische Texte) geben, wobei einzelne Punkte linear aneinandergereiht werden.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-zusammenhaengend-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können flüssig, korrekt und wirkungsvoll über ein breites Spektrum allgemeiner Themen sprechen und dabei Zusammenhänge zwischen Ideen deutlich machen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  // Schreiben — Unterstufe
  { id: 'at-englisch-un-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können über sich selbst und vertraute Themen (ua. Familie, Freunde, Tagesablauf, Hobbys, Schule) in einfachen Sätzen schreiben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Informationen in geschriebener Form weitergeben (persönliche Mitteilungen).', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können in einfachen zusammenhängenden Sätzen Aspekte des persönlichen Lebensumfeldes beschreiben (ua. Personen, Orte, Pläne, Wünsche).', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können die eigene Meinung ausdrücken und begründen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-schreiben-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können einfache Geschichten und Gebrauchstexte (ua. E-Mails, Mitteilungen) schreiben und dabei auch über vergangene und zukünftige Ereignisse berichten.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-un-schreiben-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte, strukturierte Texte (ua. Postings, E-Mails, Erfahrungsberichte) zu vertrauten Themen schreiben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Unterstufe) — RIS, Stand 2023' },
  // Schreiben — Oberstufe
  { id: 'at-englisch-ob-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können kurze, unkomplizierte zusammenhängende Texte über alltägliche Aspekte des eigenen Umfelds schreiben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte, zusammenhängende Texte zu vertrauten Themen verfassen, wobei einzelne kürzere Teile in linearer Abfolge verbunden werden; Sachinformationen weitergeben sowie Gründe für Handlungen angeben.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte, detaillierte Beschreibungen zu einer Reihe verschiedener vertrauter Themen verfassen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können mit einer gewissen Sicherheit größere Mengen von Sachinformationen über vertraute Routineangelegenheiten und über weniger routinemäßige Dinge zusammenfassen, darüber berichten und dazu Stellung nehmen.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-schreiben-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche Texte schreiben, in denen Argumente für oder gegen einen bestimmten Standpunkt angegeben und die Vor- und Nachteile verschiedener Optionen erläutert werden.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-englisch-ob-schreiben-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können klare detaillierte Texte zu einem breiten Spektrum an Themen verfassen, darin den Zusammenhang zwischen verschiedenen Ideen deutlich machen und die für das betreffende Genre geltenden Konventionen beachten.', quelle: 'BMBWF-Lehrplan AHS Englisch (Oberstufe) — RIS, Stand 2023' },
  // Sprachmittlung — Unterstufe
  { id: 'at-en-un-mitt-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können einfache Informationen zwischen Deutsch und Englisch übertragen.', quelle: Q('Unterstufe') },
  { id: 'at-en-un-mitt-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können unbekannte englische Wörter mithilfe von Kontext erschließen.', quelle: Q('Unterstufe') },
  // Sprachmittlung — Oberstufe
  { id: 'at-en-ob-mitt-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können komplexere Textausschnitte zwischen Englisch und Deutsch sinngemäß wiedergeben.', quelle: Q('Oberstufe') },
  { id: 'at-en-ob-mitt-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können englische Informationen für ein deutschsprachiges Publikum zusammenfassen.', quelle: Q('Oberstufe') },
  // Grammatik — Unterstufe
  { id: 'at-en-un-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Present Simple und Present Continuous sicher unterscheiden und in Kontexten anwenden.', quelle: '' },
  { id: 'at-en-un-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Past Simple (regelmäßige und unregelmäßige Verben) bilden und verwenden.', quelle: '' },
  { id: 'at-en-un-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Future mit will und going to bilden und die Bedeutungsunterschiede erkennen.', quelle: '' },
  { id: 'at-en-un-gramm-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Steigerung von Adjektiven und Adverbien regelmäßig und unregelmäßig bilden.', quelle: '' },
  { id: 'at-en-un-gramm-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die Verwendung von some, any, much, many und a lot of im Satz sicher anwenden.', quelle: '' },
  { id: 'at-en-un-gramm-6', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können das Present Perfect Simple (have/has + past participle) bilden und mit since/for, already/just/yet anwenden.', quelle: '' },
  { id: 'at-en-un-gramm-7', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Past Simple und Present Perfect Simple situationsgerecht unterscheiden und anwenden.', quelle: '' },
  { id: 'at-en-un-gramm-8', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Fragen, Verneinungen und Kurzantworten in den gängigen englischen Zeitformen bilden.', quelle: '' },
  // Grammatik — Oberstufe
  { id: 'at-en-ob-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die Grundformen der englischen Verbzeiten (Past, Present, Future) sicher unterscheiden und anwenden.', quelle: '' },
  { id: 'at-en-ob-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen beherrschen die Perfect-Bildung und deren Zusammenhang mit Zeitverlauf und Handlungsabfolge.', quelle: '' },
  { id: 'at-en-ob-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Konditionalsätze (Type 1–3) bilden und ihre Bedeutungsunterschiede erkennen.', quelle: '' },
  { id: 'at-en-ob-gramm-4', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Passivkonstruktionen in verschiedenen Zeiten bilden und umformen.', quelle: '' },
  { id: 'at-en-ob-gramm-5', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die indirekte Rede (Reported Speech) korrekt bilden und Zeitverschiebungen anwenden.', quelle: '' },
  // Wortschatz — Unterstufe
  { id: 'at-en-un-wort-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können thematischen Grundwortschatz (Alltag, Schule, Familie) verstehen und aktiv verwenden.', quelle: Q('Unterstufe') },
  { id: 'at-en-un-wort-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'unterstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können unbekannte Wörter mithilfe von Kontext und Wortbildung erschließen.', quelle: Q('Unterstufe') },
  // Wortschatz — Oberstufe
  { id: 'at-en-ob-wort-1', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können einen differenzierten, thematisch breiten Wortschatz verstehen und produktiv einsetzen.', quelle: Q('Oberstufe') },
  { id: 'at-en-ob-wort-2', rahmenwerk: 'at-lehrplan', fach: 'englisch', stufe: 'oberstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können synonyme und registerabhängige Ausdrücke zielgruppengerecht verwenden.', quelle: Q('Oberstufe') },
];

export const englischStoffItems: StoffItem[] = [
  // Hören
  { id: 'en-h-ren-un', rahmenwerk: 'at-lehrplan', titel: 'Hören', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Hören', deskriptorIds: ['at-englisch-un-hoeren-1', 'at-englisch-un-hoeren-2', 'at-englisch-un-hoeren-3', 'at-englisch-un-hoeren-4', 'at-englisch-un-hoeren-5', 'at-englisch-un-hoeren-6'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'en-h-ren-ob', rahmenwerk: 'at-lehrplan', titel: 'Hören', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Hören', deskriptorIds: ['at-englisch-ob-hoeren-1', 'at-englisch-ob-hoeren-2', 'at-englisch-ob-hoeren-3', 'at-englisch-ob-hoeren-4', 'at-englisch-ob-hoeren-5', 'at-englisch-ob-hoeren-6'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  // Lesen
  { id: 'en-lesen-un', rahmenwerk: 'at-lehrplan', titel: 'Lesen', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Lesen', deskriptorIds: ['at-englisch-un-lesen-1', 'at-englisch-un-lesen-2', 'at-englisch-un-lesen-3', 'at-englisch-un-lesen-4', 'at-englisch-un-lesen-5', 'at-englisch-un-lesen-6'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'en-lesen-ob', rahmenwerk: 'at-lehrplan', titel: 'Lesen', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Lesen', deskriptorIds: ['at-englisch-ob-lesen-1', 'at-englisch-ob-lesen-2', 'at-englisch-ob-lesen-3', 'at-englisch-ob-lesen-4', 'at-englisch-ob-lesen-5', 'at-englisch-ob-lesen-6'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  // An Gesprächen teilnehmen
  { id: 'en-an-gespr-chen-teilnehmen-un', rahmenwerk: 'at-lehrplan', titel: 'An Gesprächen teilnehmen', fach: 'englisch', stufe: 'unterstufe', kategorie: 'An Gesprächen teilnehmen', deskriptorIds: ['at-englisch-un-gespraeche-1', 'at-englisch-un-gespraeche-2', 'at-englisch-un-gespraeche-3', 'at-englisch-un-gespraeche-4', 'at-englisch-un-gespraeche-5'], defaultAufgabentypen: ['roleplay', 'multipleChoice'] },
  { id: 'en-an-gespr-chen-teilnehmen-ob', rahmenwerk: 'at-lehrplan', titel: 'An Gesprächen teilnehmen', fach: 'englisch', stufe: 'oberstufe', kategorie: 'An Gesprächen teilnehmen', deskriptorIds: ['at-englisch-ob-gespraeche-1', 'at-englisch-ob-gespraeche-2', 'at-englisch-ob-gespraeche-3'], defaultAufgabentypen: ['roleplay', 'multipleChoice'] },
  // Zusammenhängend sprechen
  { id: 'en-zusammenh-ngend-sprechen-un', rahmenwerk: 'at-lehrplan', titel: 'Zusammenhängend sprechen', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['at-englisch-un-zusammenhaengend-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'en-zusammenh-ngend-sprechen-ob', rahmenwerk: 'at-lehrplan', titel: 'Zusammenhängend sprechen', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['at-englisch-ob-zusammenhaengend-1', 'at-englisch-ob-zusammenhaengend-2', 'at-englisch-ob-zusammenhaengend-3'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  // Schreiben
  { id: 'en-schreiben-un', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Schreiben', deskriptorIds: ['at-englisch-un-schreiben-1', 'at-englisch-un-schreiben-2', 'at-englisch-un-schreiben-3', 'at-englisch-un-schreiben-4', 'at-englisch-un-schreiben-5', 'at-englisch-un-schreiben-6'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'en-schreiben-ob', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Schreiben', deskriptorIds: ['at-englisch-ob-schreiben-1', 'at-englisch-ob-schreiben-2', 'at-englisch-ob-schreiben-3', 'at-englisch-ob-schreiben-4', 'at-englisch-ob-schreiben-5', 'at-englisch-ob-schreiben-6'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  // Sprachmittlung
  { id: 'en-mittlung-un', rahmenwerk: 'at-lehrplan', titel: 'Einfache Übersetzung und Paraphrase', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['at-en-un-mitt-1', 'at-en-un-mitt-2'], defaultAufgabentypen: ['vokabeluebung', 'lueckentext'] },
  { id: 'en-mittlung-ob', rahmenwerk: 'at-lehrplan', titel: 'Zusammenfassung englischer Texte', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['at-en-ob-mitt-1', 'at-en-ob-mitt-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  // Grammatik
  { id: 'en-present-simple-vs-continuous-un', rahmenwerk: 'at-lehrplan', titel: 'Present Simple vs. Present Continuous', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-1'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'en-past-simple-un', rahmenwerk: 'at-lehrplan', titel: 'Past Simple', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-2'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext'] },
  { id: 'en-will-vs-going-to-un', rahmenwerk: 'at-lehrplan', titel: 'will vs. going to', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-3'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'en-comparison-un', rahmenwerk: 'at-lehrplan', titel: 'Comparison of adjectives', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-4'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'en-some-any-much-many-un', rahmenwerk: 'at-lehrplan', titel: 'some, any, much, many', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-5'], defaultAufgabentypen: ['lueckentext', 'multipleChoice', 'fehlerkorrektur'] },
  { id: 'en-mixed-tenses-un', rahmenwerk: 'at-lehrplan', titel: 'Mixed Tenses (Unterstufenwiederholung)', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-1', 'at-en-un-gramm-2', 'at-en-un-gramm-3'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'en-present-perfect-un', rahmenwerk: 'at-lehrplan', titel: 'Present Perfect Simple', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-6'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'en-past-simple-vs-present-perfect-un', rahmenwerk: 'at-lehrplan', titel: 'Past Simple vs. Present Perfect', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-6', 'at-en-un-gramm-7'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'en-questions-negation-short-answers-un', rahmenwerk: 'at-lehrplan', titel: 'Questions, Negation, Short Answers', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-un-gramm-8'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext'] },
  { id: 'en-present-perfect-vs-past-simple', rahmenwerk: 'at-lehrplan', titel: 'Present Perfect vs. Past Simple', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-1', 'at-en-ob-gramm-2'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  { id: 'en-past-perfect', rahmenwerk: 'at-lehrplan', titel: 'Past Perfect', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-2'], defaultAufgabentypen: ['fehlerkorrektur'] },
  { id: 'en-future-forms', rahmenwerk: 'at-lehrplan', titel: 'Future forms (will, going to, present continuous)', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-1'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'en-conditionals', rahmenwerk: 'at-lehrplan', titel: 'Conditionals (Type 1–3)', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-3'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext'] },
  { id: 'en-passive-voice', rahmenwerk: 'at-lehrplan', titel: 'Passive Voice', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-4'], defaultAufgabentypen: ['fehlerkorrektur'] },
  { id: 'en-reported-speech', rahmenwerk: 'at-lehrplan', titel: 'Reported Speech', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-5'], defaultAufgabentypen: ['fehlerkorrektur'] },
  { id: 'en-gerund-vs-infinitive', rahmenwerk: 'at-lehrplan', titel: 'Gerund vs. Infinitive', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-1'], defaultAufgabentypen: ['multipleChoice', 'fehlerkorrektur'] },
  { id: 'en-tenses-mixed', rahmenwerk: 'at-lehrplan', titel: 'Mixed Tenses (Oberstufenwiederholung)', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-en-ob-gramm-1', 'at-en-ob-gramm-2'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
  // Wortschatz
  { id: 'en-wortschatz-un', rahmenwerk: 'at-lehrplan', titel: 'Thematischer Grundwortschatz', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Wortschatz', deskriptorIds: ['at-en-un-wort-1', 'at-en-un-wort-2'], defaultAufgabentypen: ['vokabeluebung', 'kreuzwortraetsel'] },
  { id: 'en-wortschatz-ob', rahmenwerk: 'at-lehrplan', titel: 'Differenzierter Wortschatz und Register', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Wortschatz', deskriptorIds: ['at-en-ob-wort-1', 'at-en-ob-wort-2'], defaultAufgabentypen: ['vokabeluebung', 'offeneSchreibaufgabe'] },
];
