import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Ethik — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Ethik ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const ethikDeskriptoren: Deskriptor[] = [
  { id: 'at-ethik-un-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können Situationen und Probleme der individuellen, sozialen und ökologischen Lebenswelt in ihrem eigenen Umfeld wahrnehmen und beschreiben.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können einfache ethisch-relevante Texte mit Hilfe grundlegender Fachbegriffe erschließen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können eigene Gedanken und Gefühle in ethischen Fragen sachgemäß ausdrücken.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können einfache moralische und ethische Grundkonzepte darstellen und ihre Bedeutung für das eigene Leben verstehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Argumente in ethischen Diskussionen prüfen und eigene begründete Positionen entwickeln.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-analysieren-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können in einfachen ethischen Auseinandersetzungen konsens- und dissensfähig argumentieren.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-analysieren-4', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Wissen aus verschiedenen Lebensbereichen auf ethische Fragen beziehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können zu einfachen moralischen Problemen verantwortungsbewusst Stellung beziehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die erworbenen ethischen Kompetenzen zu eigenen Lebenserfahrungen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-urteilen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die eigene Position in ethischen Fragen reflektieren und begründen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können sich mit Denkweisen und Wertvorstellungen anderer in ihrem direkten Umfeld auseinandersetzen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung von Umwelt und Mitwelt für das eigene Handeln erkennen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-un-perspektiven-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'unterstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können einfache Konflikte aus verschiedenen Perspektiven betrachten und Lösungen entwickeln.', quelle: 'BMBWF-Lehrplan AHS Ethik (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können Situationen und Probleme der individuellen, sozialen und ökologischen Lebenswelt wahrnehmen, beschreiben und deuten.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethisch-relevante Texte mit Hilfe fachspezifischer Terminologie und Methoden erschließen und verfassen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können eigene Gedankengänge und die anderer sachgemäß und sprachlich sensibel darstellen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Wissen aus unterschiedlichen Fachgebieten und Lebensbereichen aufeinander beziehen und im Lichte ethischer Positionen reflektieren.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können moralische und ethische Grundkonzepte darstellen und ihre historischen und kulturellen Zusammenhänge verstehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-analysieren-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Argumente kritisch prüfen sowie eigenständige und begründete ethische Urteile fällen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-analysieren-4', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Auseinandersetzungen auf argumentativer Grundlage konsens- und dissensfähig führen und mit Meinungsverschiedenheiten und Konflikten gewaltfrei umgehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können durch Handlungsentwürfe zu moralischen Problemen verantwortungsbewusst und ethisch reflektiert Stellung beziehen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die erworbenen Kompetenzen zu eigenen Lebensentwürfen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-urteilen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können sich mit Denkweisen, Wertvorstellungen und Lebenswelten anderer auseinandersetzen sowie die eigene Position einordnen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können sich mit Denkweisen, Wertvorstellungen und Lebenswelten anderer auseinandersetzen sowie die eigene Position einordnen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung der Wahrnehmung und Bewertung von Umwelt im weitesten Sinn für das menschliche Handeln erkennen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-ethik-ob-perspektiven-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können ihre persönliche Rolle als Konsument bzw. Konsumentin kritisch durchleuchten und die volkswirtschaftliche Bedeutung des Konsumverhaltens erkennen.', quelle: 'BMBWF-Lehrplan AHS Ethik (Oberstufe) — RIS, Stand 2023' },
];

export const ethikStoffItems: StoffItem[] = [
  { id: 'et-wahrnehmen-und-beschreiben-un', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmen & Beschreiben', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Wahrnehmen & Beschreiben', deskriptorIds: ['at-ethik-un-wahrnehmen-1', 'at-ethik-un-wahrnehmen-2', 'at-ethik-un-wahrnehmen-3'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
  { id: 'et-analysieren-und-argumentieren-un', rahmenwerk: 'at-lehrplan', titel: 'Analysieren & Argumentieren', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Analysieren & Argumentieren', deskriptorIds: ['at-ethik-un-analysieren-1', 'at-ethik-un-analysieren-2', 'at-ethik-un-analysieren-3', 'at-ethik-un-analysieren-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'et-urteilen-und-reflektieren-un', rahmenwerk: 'at-lehrplan', titel: 'Urteilen & Reflektieren', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Urteilen & Reflektieren', deskriptorIds: ['at-ethik-un-urteilen-1', 'at-ethik-un-urteilen-2', 'at-ethik-un-urteilen-3'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'et-perspektivenwechsel-un', rahmenwerk: 'at-lehrplan', titel: 'Perspektivenwechsel', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Perspektivenwechsel', deskriptorIds: ['at-ethik-un-perspektiven-1', 'at-ethik-un-perspektiven-2', 'at-ethik-un-perspektiven-3'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'et-wahrnehmen-und-beschreiben-ob', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmen & Beschreiben', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Wahrnehmen & Beschreiben', deskriptorIds: ['at-ethik-ob-wahrnehmen-1', 'at-ethik-ob-wahrnehmen-2', 'at-ethik-ob-wahrnehmen-3'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
  { id: 'et-analysieren-und-argumentieren-ob', rahmenwerk: 'at-lehrplan', titel: 'Analysieren & Argumentieren', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Analysieren & Argumentieren', deskriptorIds: ['at-ethik-ob-analysieren-1', 'at-ethik-ob-analysieren-2', 'at-ethik-ob-analysieren-3', 'at-ethik-ob-analysieren-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'et-urteilen-und-reflektieren-ob', rahmenwerk: 'at-lehrplan', titel: 'Urteilen & Reflektieren', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Urteilen & Reflektieren', deskriptorIds: ['at-ethik-ob-urteilen-1', 'at-ethik-ob-urteilen-2', 'at-ethik-ob-urteilen-3'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'et-perspektivenwechsel-ob', rahmenwerk: 'at-lehrplan', titel: 'Perspektivenwechsel', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Perspektivenwechsel', deskriptorIds: ['at-ethik-ob-perspektiven-1', 'at-ethik-ob-perspektiven-2', 'at-ethik-ob-perspektiven-3'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
];
