import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Ethik — generiert aus Lehrplan-Recherche (_stufen.json).
// Deskriptoren sind gesourct und mit konkreter Schulstufe (5–12) hinterlegt;
// StoffItems bleiben grob (Unter-/Oberstufe) und verlinken passende Deskriptoren.

export const ethikDeskriptoren: Deskriptor[] = [
  { id: 'at-ethik-s9-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Fragen und Konflikte im Alltag und in der eigenen Lebenswelt wahrnehmen und beschreiben.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können verschiedene Wertvorstellungen und Lebensentwürfe in der pluralistischen Gesellschaft identifizieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können moralische Emotionen (z. B. Empathie, Schuld, Verantwortung) bei sich und anderen wahrnehmen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können einfache ethische Dilemmata analysieren und verschiedene Handlungsoptionen beschreiben.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können grundlegende ethische Begriffe (z. B. gut/böse, gerecht/ungerecht, frei/gebunden) klären und anwenden.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können eigene Wertvorstellungen reflektieren und in einfachen Situationen begründet urteilen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können verschiedene ethische Positionen vergleichen und erste eigene Standpunkte entwickeln.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die Perspektive anderer Personen und Gruppen in ethischen Konflikten einnehmen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s9-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 9, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können kulturelle und weltanschauliche Unterschiede in ethischen Fragen nachvollziehen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Dimensionen gesellschaftlicher und politischer Debatten (z. B. Umwelt, Migration, Technologie) wahrnehmen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können verschiedene ethische Theorien (z. B. Utilitarismus, Pflichtethik, Tugendethik) in Grundzügen charakterisieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können mediale Darstellungen ethischer Konflikte kritisch analysieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können komplexe ethische Dilemmata mit verschiedenen theoretischen Ansätzen analysieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können ethische Argumente strukturiert aufbauen und auf Gegenargumente eingehen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können eigene ethische Positionen in Auseinandersetzung mit verschiedenen Theorien begründen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die Grenzen und Stärken verschiedener ethischer Ansätze beurteilen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können verschiedene kulturelle und weltanschauliche Perspektiven auf ethische Fragen systematisch vergleichen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s10-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 10, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die eigene Position im Licht fremder Perspektiven kritisch hinterfragen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Dimensionen wissenschaftlicher und technologischer Entwicklungen (z. B. KI, Gentechnik, Überwachung) multiperspektivisch erfassen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können komplexe ethische Theorien und ihre historischen Kontexte analysieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können ethische Fragen mit wissenschaftlichen Methoden analysieren und verschiedene theoretische Positionen systematisch vergleichen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können komplexe ethische Argumentationen aufbauen und kritisch bewerten.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können eigene ethische Positionen reflexiv und differenziert in komplexen gesellschaftlichen Debatten vertreten.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die Tragfähigkeit verschiedener ethischer Ansätze für gegenwärtige Herausforderungen beurteilen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können verschiedene kulturelle, weltanschauliche und disziplinäre Perspektiven auf ethische Fragen produktiv integrieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s11-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die eigene Position im Kontext globaler und historischer Perspektiven kritisch reflektieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können aktuelle ethische Herausforderungen (z. B. Klimawandel, digitale Ethik, globale Gerechtigkeit) multiperspektivisch analysieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können die Relevanz ethischer Reflexion für persönliche und gesellschaftliche Zukunftsfragen erfassen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-analysieren-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können komplexe ethische Fragestellungen eigenständig und mit wissenschaftlichen Methoden analysieren.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-analysieren-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können ethische Argumentationen unter komplexen Fragestellungen vergleichend erarbeiten.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-urteilen-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können eigene ethische Positionen souverän und reflektiert in akademischen und öffentlichen Diskursen vertreten.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-urteilen-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können mündliche Reifeprüfung differenziert und souverän führen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-perspektiven-1', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können verschiedene Perspektiven auf ethische Fragen souverän integrieren und für verantwortungsvolles Handeln nutzen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
  { id: 'at-ethik-s12-perspektiven-2', rahmenwerk: 'at-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können ethische Reflexion als Grundlage für lebenslanges Lernen und gesellschaftliche Teilhabe verstehen.', quelle: 'BMBWF-Lehrplan AHS Ethik — RIS, Stand 2023' },
];

export const ethikStoffItems: StoffItem[] = [
  { id: 'et-wahrnehmen-und-beschreiben-ob', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmen & Beschreiben', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Wahrnehmen & Beschreiben', deskriptorIds: ['at-ethik-s9-wahrnehmen-1', 'at-ethik-s9-wahrnehmen-2', 'at-ethik-s9-wahrnehmen-3', 'at-ethik-s10-wahrnehmen-1', 'at-ethik-s10-wahrnehmen-2', 'at-ethik-s10-wahrnehmen-3', 'at-ethik-s11-wahrnehmen-1', 'at-ethik-s11-wahrnehmen-2', 'at-ethik-s12-wahrnehmen-1', 'at-ethik-s12-wahrnehmen-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
  { id: 'et-analysieren-und-argumentieren-ob', rahmenwerk: 'at-lehrplan', titel: 'Analysieren & Argumentieren', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Analysieren & Argumentieren', deskriptorIds: ['at-ethik-s9-analysieren-1', 'at-ethik-s9-analysieren-2', 'at-ethik-s10-analysieren-1', 'at-ethik-s10-analysieren-2', 'at-ethik-s11-analysieren-1', 'at-ethik-s11-analysieren-2', 'at-ethik-s12-analysieren-1', 'at-ethik-s12-analysieren-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'et-urteilen-und-reflektieren-ob', rahmenwerk: 'at-lehrplan', titel: 'Urteilen & Reflektieren', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Urteilen & Reflektieren', deskriptorIds: ['at-ethik-s9-urteilen-1', 'at-ethik-s9-urteilen-2', 'at-ethik-s10-urteilen-1', 'at-ethik-s10-urteilen-2', 'at-ethik-s11-urteilen-1', 'at-ethik-s11-urteilen-2', 'at-ethik-s12-urteilen-1', 'at-ethik-s12-urteilen-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'et-perspektivenwechsel-ob', rahmenwerk: 'at-lehrplan', titel: 'Perspektivenwechsel', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Perspektivenwechsel', deskriptorIds: ['at-ethik-s9-perspektiven-1', 'at-ethik-s9-perspektiven-2', 'at-ethik-s10-perspektiven-1', 'at-ethik-s10-perspektiven-2', 'at-ethik-s11-perspektiven-1', 'at-ethik-s11-perspektiven-2', 'at-ethik-s12-perspektiven-1', 'at-ethik-s12-perspektiven-2'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
];
