import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Französisch — Lehrplan-Deskriptoren + Stoff-Items (Rahmenwerk at-lehrplan).
// `bereich`/`kategorie` verwenden die Namen aus KOMPETENZBEREICHE['franzoesisch'] wortgleich.
// Deskriptoren sind kuratierte Entwürfe (siehe `quelle`).

const Q = (stufe: string) =>
  `Entwurf, angelehnt an BMBWF-Lehrplan AHS Französisch ${stufe} — nicht offiziell zitiert`;

// Französisch — gemischt: gesourcte Skill-Deskriptoren aus Lehrplan-Recherche
// plus erhaltene kuratierte Grammatik-/Wortschatz-/Sprachmittlungs-/Literatur-Blöcke.

export const franzoesischDeskriptoren: Deskriptor[] = [
  // Hören — Unterstufe
  { id: 'at-franzoesisch-un-hoeren-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können vertraute Wörter und ganz einfache Sätze, die sich auf die eigene Person, die Familie oder auf konkrete Dinge beziehen, verstehen, vorausgesetzt, es wird langsam und deutlich gesprochen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-hoeren-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Informationen zur eigenen Person, zu Familie, Einkaufen, Arbeit, nähere Umgebung verstehen, sofern deutlich und langsam gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-hoeren-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können die wesentliche Information sowie zentrale Wendungen und Wörter verstehen, wenn es um Dinge von ganz unmittelbarer Bedeutung geht, sofern deutlich und langsam gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-hoeren-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können genug verstehen, um Bedürfnisse konkreter Art befriedigen zu können, sofern deutlich und langsam gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  // Hören — Oberstufe
  { id: 'at-franzoesisch-ob-hoeren-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können die Hauptpunkte verstehen, wenn in deutlich artikulierter Standardsprache über vertraute Dinge gesprochen wird, denen man normalerweise in der Ausbildung oder der Freizeit begegnet.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-hoeren-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können Hauptpunkte und wesentliche Informationen verstehen, auch in Radiosendungen und Filmen, wenn relativ langsam und in deutlich artikulierter Standardsprache über vertraute Themen gesprochen wird.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-hoeren-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können kurze Erzählungen verstehen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  // Lesen — Unterstufe
  { id: 'at-franzoesisch-un-lesen-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurze, einfache Texte mit einem sehr frequenten Wortschatz und einem Anteil international bekannter Wörter lesen und verstehen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-lesen-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können Sätze und häufig gebrauchte Ausdrücke, die mit Bereichen von ganz unmittelbarer Bedeutung zusammenhängen, verstehen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-lesen-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können in einfachen kurzen Texten konkrete, vorhersehbare Informationen auffinden.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-lesen-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurze, einfache Texte zu vertrauten, konkreten Themen verstehen, in denen gängige Alltagssprache verwendet wird.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  // Lesen — Oberstufe
  { id: 'at-franzoesisch-ob-lesen-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können konkrete, unkomplizierte, klar gegliederte Texte, auch Zeitungsartikel und einfache literarische Texte über vertraute Themen mit befriedigendem Verständnis lesen, die wesentlichen Punkte erfassen und wichtige Informationen auffinden.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-lesen-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können Beschreibungen von Ereignissen, Gefühlen und Wünschen verstehen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-lesen-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können in klar geschriebenen argumentativen Texten die wesentlichen Schlussfolgerungen erkennen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  // An Gesprächen teilnehmen — Unterstufe
  { id: 'at-franzoesisch-un-gespraeche-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können sich auf einfache Art verständigen, wenn die Gesprächspartner bereit sind, etwas langsamer zu wiederholen oder anders zu sagen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-gespraeche-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können einfache Fragen stellen und beantworten, sofern es sich um unmittelbar notwendige Dinge und um sehr vertraute Themen handelt.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-gespraeche-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können sich in einfachen, routinemäßigen Situationen verständigen, in denen es um einen unkomplizierten und direkten Austausch von Informationen über vertraute Themen geht.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-gespraeche-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können sich in routinemäßigen Situationen verständigen, in denen es um einen unkomplizierten und direkten Austausch von Informationen über vertraute Themen im Zusammenhang mit Fragen des Alltags, Schule und Freizeit geht.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  // An Gesprächen teilnehmen — Oberstufe
  { id: 'at-franzoesisch-ob-gespraeche-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können ohne Vorbereitung an Gesprächen über vertraute Themen teilnehmen und Informationen austauschen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-gespraeche-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können die eigene Meinung und Gefühle sowie Träume, Hoffnungen und Ziele ausdrücken und darauf reagieren.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-gespraeche-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können Vorschläge unterschiedlicher Art machen und entsprechend darauf reagieren.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-gespraeche-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können zu einem vertrauten Thema kurz Gründe und Erläuterungen zu Meinungen, Plänen und Handlungen geben.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  // Zusammenhängend sprechen — Unterstufe
  { id: 'at-franzoesisch-un-zusammenhaengend-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können einfache Wendungen und Sätze gebrauchen, um Leute, die man kennt, zu beschreiben und um zu beschreiben, wo man wohnt.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-zusammenhaengend-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können einfache Beschreibungen von Menschen, Alltagsroutinen, Vorlieben oder Abneigungen geben, und zwar in kurzen, einfachen auch memorierten Wendungen und Sätzen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-zusammenhaengend-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können über gegenwärtige und vergangene Aktivitäten erzählen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-zusammenhaengend-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können Beschreibungen von Menschen, Alltagsroutinen, Vorlieben oder Abneigungen geben, und zwar in kurzen Wendungen und Sätzen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  // Zusammenhängend sprechen — Oberstufe
  { id: 'at-franzoesisch-ob-zusammenhaengend-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können relativ flüssig eine unkomplizierte zusammenhängende Beschreibung zu vertrauten Themen geben, wobei einzelne Punkte linear aneinandergereiht werden.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-zusammenhaengend-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können Vergleiche anstellen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-zusammenhaengend-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können kurz und einfach über ein Ereignis, gegenwärtige oder vergangene Aktivitäten oder Tätigkeiten berichten und sich darüber austauschen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-zusammenhaengend-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können Pläne und Vereinbarungen sowie Gewohnheiten und Alltagsbeschäftigungen beschreiben und sich darüber austauschen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  // Schreiben — Unterstufe
  { id: 'at-franzoesisch-un-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können eine Reihe einfacher Sätze über alltägliche Aspekte schreiben.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können eine Reihe einfacher memorierter Wendungen und Sätze über alltägliche Aspekte schreiben und mit Konnektoren wie und, aber oder weil verbinden.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können ganz einfache persönliche Briefe und elektronische Mitteilungen schreiben, die sich auf unmittelbare Bedürfnisse beziehen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-un-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können kurze, unkomplizierte und zusammenhängende Texte über alltägliche Aspekte des eigenen Umfelds schreiben.', quelle: 'BMBWF-Lehrplan AHS Französisch (Unterstufe) — RIS, Stand 2023' },
  // Schreiben — Oberstufe
  { id: 'at-franzoesisch-ob-schreiben-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können unkomplizierte, zusammenhängende Texte, auch in Form von persönlichen Briefen und elektronischen Mitteilungen, zu vertrauten Themen verfassen, wobei einzelne kürzere Teile in linearer Abfolge verbunden werden.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-schreiben-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können Sachinformationen weitergeben sowie Gründe für Handlungen angeben.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-schreiben-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können eine Beschreibung eines Ereignisses oder einer kürzlich unternommenen Reise verfassen.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-franzoesisch-ob-schreiben-4', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können über Erfahrungen, Gefühle und Ereignisse berichten.', quelle: 'BMBWF-Lehrplan AHS Französisch (Oberstufe) — RIS, Stand 2023' },
  // Sprachmittlung — Unterstufe
  { id: 'at-fr-un-mitt-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können einfache Informationen zwischen Deutsch und Französisch übertragen.', quelle: Q('Unterstufe') },
  { id: 'at-fr-un-mitt-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können unbekannte französische Wörter mithilfe von Kontext oder Wörterbuch erschließen.', quelle: Q('Unterstufe') },
  // Sprachmittlung — Oberstufe
  { id: 'at-fr-ob-mitt-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können komplexere Textausschnitte zwischen Französisch und Deutsch sinngemäß wiedergeben.', quelle: Q('Oberstufe') },
  { id: 'at-fr-ob-mitt-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen können fremdsprachige Informationen für ein deutschsprachiges Publikum zusammenfassen.', quelle: Q('Oberstufe') },
  // Grammatik — Unterstufe
  { id: 'at-fr-un-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können die wichtigsten französischen Zeitformen (Présent, Passé composé, Futur simple) bilden und anwenden.', quelle: Q('Unterstufe') },
  { id: 'at-fr-un-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Personalpronomen, Possessivbegleiter und unbestimmte Artikel richtig verwenden.', quelle: Q('Unterstufe') },
  { id: 'at-fr-un-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können einfache Satzstrukturen (Aussage, Frage, Verneinung) auf Französisch bilden.', quelle: Q('Unterstufe') },
  // Grammatik — Oberstufe
  { id: 'at-fr-ob-gramm-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können komplexe Zeitformen (Subjonctif, Conditionnel, Plus-que-parfait) unterscheiden und einsetzen.', quelle: Q('Oberstufe') },
  { id: 'at-fr-ob-gramm-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Pronomen (relatifs, démonstratifs, possessifs) und deren Funktionen im Satz erklären.', quelle: Q('Oberstufe') },
  { id: 'at-fr-ob-gramm-3', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Grammatik', code: '', text: 'Die Schülerinnen können Nebensätze und Satzgefüge auf Französisch bilden und korrekt satzgliedern.', quelle: Q('Oberstufe') },
  // Wortschatz — Unterstufe
  { id: 'at-fr-un-wort-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können thematischen Grundwortschatz (Alltag, Schule, Familie) verstehen und aktiv verwenden.', quelle: Q('Unterstufe') },
  { id: 'at-fr-un-wort-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können unbekannte Wörter mithilfe von Kontext, Wortbildung und Wörterbuch erschließen.', quelle: Q('Unterstufe') },
  // Wortschatz — Oberstufe
  { id: 'at-fr-ob-wort-1', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können einen differenzierten, thematisch breiten Wortschatz verstehen und produktiv einsetzen.', quelle: Q('Oberstufe') },
  { id: 'at-fr-ob-wort-2', rahmenwerk: 'at-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen können synonyme und registerabhängige Ausdrücke unterscheiden und zielgruppengerecht verwenden.', quelle: Q('Oberstufe') },
];

export const franzoesischStoffItems: StoffItem[] = [
  // Hören
  { id: 'fr-h-ren-un', rahmenwerk: 'at-lehrplan', titel: 'Hören', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Hören', deskriptorIds: ['at-franzoesisch-un-hoeren-1', 'at-franzoesisch-un-hoeren-2', 'at-franzoesisch-un-hoeren-3', 'at-franzoesisch-un-hoeren-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'fr-h-ren-ob', rahmenwerk: 'at-lehrplan', titel: 'Hören', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Hören', deskriptorIds: ['at-franzoesisch-ob-hoeren-1', 'at-franzoesisch-ob-hoeren-2', 'at-franzoesisch-ob-hoeren-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  // Lesen
  { id: 'fr-lesen-un', rahmenwerk: 'at-lehrplan', titel: 'Lesen', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Lesen', deskriptorIds: ['at-franzoesisch-un-lesen-1', 'at-franzoesisch-un-lesen-2', 'at-franzoesisch-un-lesen-3', 'at-franzoesisch-un-lesen-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'fr-lesen-ob', rahmenwerk: 'at-lehrplan', titel: 'Lesen', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Lesen', deskriptorIds: ['at-franzoesisch-ob-lesen-1', 'at-franzoesisch-ob-lesen-2', 'at-franzoesisch-ob-lesen-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  // An Gesprächen teilnehmen
  { id: 'fr-an-gespr-chen-teilnehmen-un', rahmenwerk: 'at-lehrplan', titel: 'An Gesprächen teilnehmen', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'An Gesprächen teilnehmen', deskriptorIds: ['at-franzoesisch-un-gespraeche-1', 'at-franzoesisch-un-gespraeche-2', 'at-franzoesisch-un-gespraeche-3', 'at-franzoesisch-un-gespraeche-4'], defaultAufgabentypen: ['roleplay', 'multipleChoice'] },
  { id: 'fr-an-gespr-chen-teilnehmen-ob', rahmenwerk: 'at-lehrplan', titel: 'An Gesprächen teilnehmen', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'An Gesprächen teilnehmen', deskriptorIds: ['at-franzoesisch-ob-gespraeche-1', 'at-franzoesisch-ob-gespraeche-2', 'at-franzoesisch-ob-gespraeche-3', 'at-franzoesisch-ob-gespraeche-4'], defaultAufgabentypen: ['roleplay', 'multipleChoice'] },
  // Zusammenhängend sprechen
  { id: 'fr-zusammenh-ngend-sprechen-un', rahmenwerk: 'at-lehrplan', titel: 'Zusammenhängend sprechen', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['at-franzoesisch-un-zusammenhaengend-1', 'at-franzoesisch-un-zusammenhaengend-2', 'at-franzoesisch-un-zusammenhaengend-3', 'at-franzoesisch-un-zusammenhaengend-4'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'fr-zusammenh-ngend-sprechen-ob', rahmenwerk: 'at-lehrplan', titel: 'Zusammenhängend sprechen', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['at-franzoesisch-ob-zusammenhaengend-1', 'at-franzoesisch-ob-zusammenhaengend-2', 'at-franzoesisch-ob-zusammenhaengend-3', 'at-franzoesisch-ob-zusammenhaengend-4'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  // Schreiben
  { id: 'fr-schreiben-un', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Schreiben', deskriptorIds: ['at-franzoesisch-un-schreiben-1', 'at-franzoesisch-un-schreiben-2', 'at-franzoesisch-un-schreiben-3', 'at-franzoesisch-un-schreiben-4'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'fr-schreiben-ob', rahmenwerk: 'at-lehrplan', titel: 'Schreiben', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Schreiben', deskriptorIds: ['at-franzoesisch-ob-schreiben-1', 'at-franzoesisch-ob-schreiben-2', 'at-franzoesisch-ob-schreiben-3', 'at-franzoesisch-ob-schreiben-4'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  // Sprachmittlung
  { id: 'fr-mittlung-un', rahmenwerk: 'at-lehrplan', titel: 'Einfache Übersetzung und Paraphrase', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['at-fr-un-mitt-1', 'at-fr-un-mitt-2'], defaultAufgabentypen: ['vokabeluebung', 'lueckentext'] },
  { id: 'fr-mittlung-ob', rahmenwerk: 'at-lehrplan', titel: 'Zusammenfassung französischer Texte', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['at-fr-ob-mitt-1', 'at-fr-ob-mitt-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  // Grammatik
  { id: 'fr-zeiten-un', rahmenwerk: 'at-lehrplan', titel: 'Présent, Passé composé, Futur simple', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Grammatik', deskriptorIds: ['at-fr-un-gramm-1', 'at-fr-un-gramm-2', 'at-fr-un-gramm-3'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext', 'multipleChoice'] },
  { id: 'fr-subjonctif-ob', rahmenwerk: 'at-lehrplan', titel: 'Subjonctif, Conditionnel, Plus-que-parfait', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['at-fr-ob-gramm-1', 'at-fr-ob-gramm-2', 'at-fr-ob-gramm-3'], defaultAufgabentypen: ['fehlerkorrektur', 'lueckentext', 'multipleChoice'] },
  // Wortschatz
  { id: 'fr-wortschatz-un', rahmenwerk: 'at-lehrplan', titel: 'Thematischer Grundwortschatz', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Wortschatz', deskriptorIds: ['at-fr-un-wort-1', 'at-fr-un-wort-2'], defaultAufgabentypen: ['vokabeluebung', 'kreuzwortraetsel'] },
  { id: 'fr-wortschatz-ob', rahmenwerk: 'at-lehrplan', titel: 'Differenzierter Wortschatz und Register', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Wortschatz', deskriptorIds: ['at-fr-ob-wort-1', 'at-fr-ob-wort-2'], defaultAufgabentypen: ['vokabeluebung', 'offeneSchreibaufgabe'] },
];
