import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Geographie — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Geographie ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const geographieDeskriptoren: Deskriptor[] = [
  { id: 'at-geographie-un-wahrnehmung-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '1.3', text: 'Die Schülerinnen und Schüler können persönliches Leben beginnend in der Wohn-/Schulortgemeinde auf verschiedenen Maßstabsebenen mit Hilfe von Geomedien einordnen und darstellen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wahrnehmung-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '1.4', text: 'Die Schülerinnen und Schüler können wesentliche Charakteristika der räumlichen Umwelt erheben, beschreiben und individuell bewerten.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wahrnehmung-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '1.6', text: 'Die Schülerinnen und Schüler können soziale, ökonomische und kulturelle sowie alters- und geschlechtsbedingte Gemeinsamkeiten und Unterschiede im Zusammenhang mit Arbeiten, Wohnen und Mobilität in weltweit ausgewählten Fallbeispielen aus Zentren und Peripherien vergleichen und diese mit Geomedien lokalisieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wahrnehmung-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '3.6', text: 'Die Schülerinnen und Schüler können Industrieregionen, Tourismusregionen, landwirtschaftlich geprägte Regionen und Regionen mit anderen wirtschaftlichen Schwerpunkten charakterisieren und verorten.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wahrnehmung-5', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '3.15', text: 'Die Schülerinnen und Schüler können Zentren und Peripherien Österreichs abgrenzen, in Geomedien verorten und die Relativität jeder Abgrenzung erläutern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Methodenkompetenz', code: '1.1', text: 'Die Schülerinnen und Schüler können eigene Wünsche und Bedürfnisse formulieren, vergleichen und reflektieren, deren Umsetzbarkeit überprüfen und erklären.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Methodenkompetenz', code: '2.2', text: 'Die Schülerinnen und Schüler können die ungleiche räumliche und gesellschaftliche Verteilung von Ressourcen mit Hilfe von (Geo-)Medien beschreiben und deren Nutzung, Wiederverwendung und Entsorgung analysieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-methoden-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Methodenkompetenz', code: '3.1', text: 'Die Schülerinnen und Schüler können aktuelle demografische Strukturen und Prozesse beschreiben und deren mediale Darstellungen interpretieren sowie die Bedeutung für die eigene und gesellschaftliche Zukunft erörtern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-methoden-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Methodenkompetenz', code: '3.17', text: 'Die Schülerinnen und Schüler können mit Hilfe von (Geo-)Medien die Raumnutzungen für Wohnen, Arbeit, Verkehr, Freizeitaktivitäten und Tourismus vergleichen sowie Lösungsansätze der Raumplanung bei Nutzungskonflikten erörtern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-methoden-5', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Methodenkompetenz', code: '4.4', text: 'Die Schülerinnen und Schüler können unterschiedliche Gliederungen, Wahrnehmungen und Darstellungen von Europa und der Europäischen Union in ihrer Vielfalt beschreiben, in (Geo-)Medien analysieren und dazu kritisch Stellung beziehen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-synthese-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Synthesekompetenz', code: '1.5', text: 'Die Schülerinnen und Schüler können unterschiedliche Vorstellungen von Lebensqualität erkunden und Lebensstile hinsichtlich Nachhaltigkeit reflektieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-synthese-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Synthesekompetenz', code: '1.11', text: 'Die Schülerinnen und Schüler können Wechselwirkungen von Naturereignissen, Lebensqualität und Wirtschaften der Menschen anhand von Fallbeispielen beschreiben und erörtern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-synthese-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Synthesekompetenz', code: '1.12', text: 'Die Schülerinnen und Schüler können unterschiedliche Betroffenheit von Menschen und Gesellschaften durch Naturgefahren in angemessener Sprache bewerten und Möglichkeiten solidarischen Handelns erörtern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-synthese-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Synthesekompetenz', code: '4.2', text: 'Die Schülerinnen und Schüler können Folgen der Überschreitung von Belastungsgrenzen der Erde, des Klimawandels oder des Artensterbens auf das Leben und Wirtschaften erörtern.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-synthese-5', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Synthesekompetenz', code: '4.3', text: 'Die Schülerinnen und Schüler können über das sich wandelnde Verhältnis zwischen Mensch und Natur reflektieren, bereits etablierte Maßnahmen und Konzepte zum nachhaltigen Leben und Wirtschaften analysieren und eigene Ideen für nachhaltige Handlungen entwickeln.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wirtschaft-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wirtschaftliche Bildung', code: '1.2', text: 'Die Schülerinnen und Schüler können das Produzieren und Konsumieren im Wirtschaftskreislauf sowie den verantwortungsbewussten Umgang mit Geld (Einnahmen und Ausgaben) anhand von Fallbeispielen aus dem eigenen Umfeld analysieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wirtschaft-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wirtschaftliche Bildung', code: '2.7', text: 'Die Schülerinnen und Schüler können das Zusammentreffen von Angebot und Nachfrage nach verschiedenen Gütern auf Märkten sowie deren wesentliche Funktionen insbesondere für die Preisbildung charakterisieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wirtschaft-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wirtschaftliche Bildung', code: '2.8', text: 'Die Schülerinnen und Schüler können einfache Projektideen zur Erzeugung von Gütern oder zur Bereitstellung von Dienstleistungen planen und durchführen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wirtschaft-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wirtschaftliche Bildung', code: '3.4', text: 'Die Schülerinnen und Schüler können unbezahlte und bezahlte Arbeit, Arbeitslosigkeit, Höhe und Verwendung des Einkommens, Sparen, Finanzieren und Versichern, Rechte und Pflichten von Erwerbstätigen und Konsumierenden einschließlich Konsumentenschutz beschreiben.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-un-wirtschaft-5', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'unterstufe', bereich: 'Wirtschaftliche Bildung', code: '3.13', text: 'Die Schülerinnen und Schüler können die wirtschaftliche Entwicklung Österreichs anhand von Kenngrößen beschreiben und persönliche, gesellschaftliche und ökologische Folgen diskutieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wahrnehmung-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe räumliche Strukturen und Prozesse auf verschiedenen Maßstabsebenen (lokal, regional, national, global) wahrnehmen, analysieren und einordnen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wahrnehmung-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche Wahrnehmungen und Bewertungen von Räumen durch verschiedene Akteure identifizieren und reflektieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wahrnehmung-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können ihr räumliches Orientierungswissen erweitern und dieses für Entscheidungen in privaten, beruflichen und öffentlichen Kontexten nutzen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wahrnehmung-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Relativität räumlicher Abgrenzungen und Zuordnungen erkennen und kritisch hinterfragen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können geographisch-wirtschaftskundliche Informationen mit Hilfe bewährter und computergestützter Verfahren gewinnen, analysieren und zielgruppenorientiert darstellen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können topographische und thematische Karten sowie Satellitenbilder selbstständig auswerten und interpretieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-methoden-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können statistische Daten und Geodaten kritisch analysieren und visualisieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-methoden-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können qualitative und quantitative Forschungsmethoden der Geographie und Wirtschaftskunde anwenden.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-synthese-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Einsicht in das Wirkungsgefüge und die Dynamik von Raum, Gesellschaft und Wirtschaft sowie in die zugrunde liegenden Machtstrukturen gewinnen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-synthese-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Komplexität von Beziehungsgeflechten zwischen Natur- und Humanfaktoren erkennen und zu den Auswirkungen menschlicher Eingriffe Stellung nehmen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-synthese-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Raum, Gesellschaft und Wirtschaft fächerübergreifend mit benachbarten natur- und sozialwissenschaftlichen Disziplinen betrachten.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-synthese-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Landschaften als Lebensräume ökonomisch und ökologisch einschätzen und Interessensgegensätze bei der Nutzung analysieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wirtschaft-1', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Zusammenhänge in betriebs-, volks- und weltwirtschaftlichen Bereichen sowie gesamtwirtschaftliche Gesetzmäßigkeiten, Strukturen und Probleme analysieren.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wirtschaft-2', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können Wirtschaftspolitik als wesentlichen Bestandteil der Politik erkennen, ihre Modelle und deren reale Umsetzung in unterschiedlichen Systemen einschätzen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wirtschaft-3', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können ihre persönliche Rolle als Konsument bzw. Konsumentin kritisch durchleuchten und die volkswirtschaftliche Bedeutung des Konsumverhaltens erkennen.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geographie-ob-wirtschaft-4', rahmenwerk: 'at-lehrplan', fach: 'geographie', stufe: 'oberstufe', bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung nachhaltiger wirtschaftlicher Aktivitäten in der globalisierten Welt diskutieren und Handlungsmöglichkeiten entwickeln.', quelle: 'BMBWF-Lehrplan AHS Geographie und wirtschaftliche Bildung (Oberstufe) — RIS, Stand 2023' },
];

export const geographieStoffItems: StoffItem[] = [
  { id: 'gw-wahrnehmungs-und-orientierungskompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmungs- & Orientierungskompetenz', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Wahrnehmungs- & Orientierungskompetenz', deskriptorIds: ['at-geographie-un-wahrnehmung-1', 'at-geographie-un-wahrnehmung-2', 'at-geographie-un-wahrnehmung-3', 'at-geographie-un-wahrnehmung-4', 'at-geographie-un-wahrnehmung-5'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'gw-methodenkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Methodenkompetenz', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Methodenkompetenz', deskriptorIds: ['at-geographie-un-methoden-1', 'at-geographie-un-methoden-2', 'at-geographie-un-methoden-3', 'at-geographie-un-methoden-4', 'at-geographie-un-methoden-5'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'gw-synthesekompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Synthesekompetenz', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Synthesekompetenz', deskriptorIds: ['at-geographie-un-synthese-1', 'at-geographie-un-synthese-2', 'at-geographie-un-synthese-3', 'at-geographie-un-synthese-4', 'at-geographie-un-synthese-5'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'gw-wirtschaftliche-bildung-un', rahmenwerk: 'at-lehrplan', titel: 'Wirtschaftliche Bildung', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Wirtschaftliche Bildung', deskriptorIds: ['at-geographie-un-wirtschaft-1', 'at-geographie-un-wirtschaft-2', 'at-geographie-un-wirtschaft-3', 'at-geographie-un-wirtschaft-4', 'at-geographie-un-wirtschaft-5'], defaultAufgabentypen: ['multipleChoice', 'offeneSchreibaufgabe'] },
  { id: 'gw-wahrnehmungs-und-orientierungskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmungs- & Orientierungskompetenz', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Wahrnehmungs- & Orientierungskompetenz', deskriptorIds: ['at-geographie-ob-wahrnehmung-1', 'at-geographie-ob-wahrnehmung-2', 'at-geographie-ob-wahrnehmung-3', 'at-geographie-ob-wahrnehmung-4'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'gw-methodenkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Methodenkompetenz', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Methodenkompetenz', deskriptorIds: ['at-geographie-ob-methoden-1', 'at-geographie-ob-methoden-2', 'at-geographie-ob-methoden-3', 'at-geographie-ob-methoden-4'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'gw-synthesekompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Synthesekompetenz', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Synthesekompetenz', deskriptorIds: ['at-geographie-ob-synthese-1', 'at-geographie-ob-synthese-2', 'at-geographie-ob-synthese-3', 'at-geographie-ob-synthese-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'gw-wirtschaftliche-bildung-ob', rahmenwerk: 'at-lehrplan', titel: 'Wirtschaftliche Bildung', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Wirtschaftliche Bildung', deskriptorIds: ['at-geographie-ob-wirtschaft-1', 'at-geographie-ob-wirtschaft-2', 'at-geographie-ob-wirtschaft-3', 'at-geographie-ob-wirtschaft-4'], defaultAufgabentypen: ['multipleChoice', 'offeneSchreibaufgabe'] },
];
