import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Geschichte — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Geschichte ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const geschichteDeskriptoren: Deskriptor[] = [
  { id: 'at-geschichte-un-frage-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Fragen an Quellen und Darstellungen stellen und dabei zwischen Vergangenheit, Gegenwart und Zukunft unterscheiden.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-frage-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Fragen zur Geschichte eigener Lebenswelten formulieren und diese mit historischen Entwicklungen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-frage-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Fragestellungen zu gesellschaftlichen und politischen Veränderungen in verschiedenen Epochen entwickeln.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Quellen (Texte, Bilder, Karten, Statistiken, Sachquellen) identifizieren, analysieren und kritisch bewerten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Darstellungen (Geschichtsbücher, Dokumentationen, Filme, Internet) auf ihre Aussageabsicht und Zuverlässigkeit überprüfen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-methoden-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Informationen aus verschiedenen Quellen sammeln, ordnen und vergleichen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-methoden-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Sachverhalte mit Hilfe von Zeitleisten, Karten und Diagrammen einordnen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-orientierung-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Ereignisse, Personen und Strukturen in zeitliche und räumliche Zusammenhänge einordnen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-orientierung-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Kontinuitäten und Veränderungen in verschiedenen historischen Epochen erkennen und beschreiben.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-orientierung-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Erfahrungen für die Orientierung in der Gegenwart nutzen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-sach-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale Ereignisse, Entwicklungen und Strukturen in verschiedenen Epochen (Antike, Mittelalter, Neuzeit) beschreiben und erklären.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-sach-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Ursachen und Folgen historischer Entwicklungen analysieren und darstellen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-sach-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Handlungsmöglichkeiten und -grenzen von Menschen in verschiedenen historischen Situationen beschreiben und bewerten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-sach-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Begriffe und Konzepte fachgerecht verwenden.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-politisch-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können grundlegende politische Strukturen und Prozesse in Österreich und Europa beschreiben und erklären.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-politisch-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können eigene politische Positionen entwickeln und begründen sowie andere Standpunkte respektieren.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-politisch-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung von Menschenrechten, Demokratie und Rechtsstaatlichkeit in Geschichte und Gegenwart beschreiben.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-un-politisch-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'unterstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Möglichkeiten der politischen Partizipation in Schule, Gemeinde und Gesellschaft erkennen und nutzen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Politische Bildung (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-frage-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe historische Fragestellungen zu gesellschaftlichen, politischen und kulturellen Entwicklungen formulieren und diese methodisch geleitet bearbeiten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-frage-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Fragestellungen mit aktuellen gesellschaftlichen und politischen Problemen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-frage-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche historiographische Perspektiven und Deutungen historischer Ereignisse identifizieren und vergleichen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können verschiedene Quellengattungen (schriftliche Quellen, Bildquellen, audiovisuelle Medien, digitale Quellen) selbstständig analysieren und kritisch bewerten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Argumentationen in wissenschaftlichen und populären Darstellungen identifizieren und auf ihre Schlüssigkeit überprüfen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-methoden-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Informationen aus verschiedenen Quellen und Darstellungen synthetisieren und eigene historische Narrative konstruieren.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-methoden-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können quantitative und qualitative Methoden der Geschichtswissenschaft anwenden.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-orientierung-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe historische Zusammenhänge und Entwicklungen in verschiedenen Epochen analysieren und in größere historische Narrative einordnen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-orientierung-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Erfahrungen für die Analyse und Bewertung aktueller gesellschaftlicher und politischer Herausforderungen nutzen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-orientierung-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können die historische Bedingtheit gegenwärtiger Strukturen und Probleme erkennen und reflektieren.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-sach-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale historische Prozesse und Strukturen in verschiedenen Epochen (19., 20., 21. Jahrhundert) analysieren und erklären.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-sach-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Ursachen, Verläufe und Folgen historischer Entwicklungen multiperspektivisch analysieren und darstellen.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-sach-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Handlungsspielräume und -grenzen von Individuen und Gruppen in verschiedenen historischen Kontexten bewerten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-sach-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Fachbegriffe und Konzepte differenziert und reflektiert verwenden.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-politisch-1', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können komplexe politische Strukturen, Prozesse und Institutionen in Österreich, Europa und der Welt analysieren und bewerten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-politisch-2', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können eigene politische Positionen auf der Grundlage demokratischer Werte und Menschenrechte begründen und in öffentlichen Diskursen vertreten.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-politisch-3', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können die historische Genese und aktuelle Bedeutung von Demokratie, Rechtsstaatlichkeit und Menschenrechten analysieren.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-geschichte-ob-politisch-4', rahmenwerk: 'at-lehrplan', fach: 'geschichte', stufe: 'oberstufe', bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Formen politischer Partizipation und zivilgesellschaftlichen Engagements analysieren und eigene Handlungsmöglichkeiten entwickeln.', quelle: 'BMBWF-Lehrplan AHS Geschichte und Sozialkunde/Politische Bildung (Oberstufe) — RIS, Stand 2023' },
];

export const geschichteStoffItems: StoffItem[] = [
  { id: 'ge-historische-fragekompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Historische Fragekompetenz', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Fragekompetenz', deskriptorIds: ['at-geschichte-un-frage-1', 'at-geschichte-un-frage-2', 'at-geschichte-un-frage-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ge-historische-methodenkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Historische Methodenkompetenz', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Methodenkompetenz', deskriptorIds: ['at-geschichte-un-methoden-1', 'at-geschichte-un-methoden-2', 'at-geschichte-un-methoden-3', 'at-geschichte-un-methoden-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ge-historische-orientierungskompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Historische Orientierungskompetenz', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Orientierungskompetenz', deskriptorIds: ['at-geschichte-un-orientierung-1', 'at-geschichte-un-orientierung-2', 'at-geschichte-un-orientierung-3'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'ge-historische-sachkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Historische Sachkompetenz', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Sachkompetenz', deskriptorIds: ['at-geschichte-un-sach-1', 'at-geschichte-un-sach-2', 'at-geschichte-un-sach-3', 'at-geschichte-un-sach-4'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'ge-politische-bildung-un', rahmenwerk: 'at-lehrplan', titel: 'Politische Bildung', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Politische Bildung', deskriptorIds: ['at-geschichte-un-politisch-1', 'at-geschichte-un-politisch-2', 'at-geschichte-un-politisch-3', 'at-geschichte-un-politisch-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'ge-historische-fragekompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Historische Fragekompetenz', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Fragekompetenz', deskriptorIds: ['at-geschichte-ob-frage-1', 'at-geschichte-ob-frage-2', 'at-geschichte-ob-frage-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ge-historische-methodenkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Historische Methodenkompetenz', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Methodenkompetenz', deskriptorIds: ['at-geschichte-ob-methoden-1', 'at-geschichte-ob-methoden-2', 'at-geschichte-ob-methoden-3', 'at-geschichte-ob-methoden-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ge-historische-orientierungskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Historische Orientierungskompetenz', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Orientierungskompetenz', deskriptorIds: ['at-geschichte-ob-orientierung-1', 'at-geschichte-ob-orientierung-2', 'at-geschichte-ob-orientierung-3'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'ge-historische-sachkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Historische Sachkompetenz', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Sachkompetenz', deskriptorIds: ['at-geschichte-ob-sach-1', 'at-geschichte-ob-sach-2', 'at-geschichte-ob-sach-3', 'at-geschichte-ob-sach-4'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'ge-politische-bildung-ob', rahmenwerk: 'at-lehrplan', titel: 'Politische Bildung', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Politische Bildung', deskriptorIds: ['at-geschichte-ob-politisch-1', 'at-geschichte-ob-politisch-2', 'at-geschichte-ob-politisch-3', 'at-geschichte-ob-politisch-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
