import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Informatik und Künstliche Intelligenz — generiert aus Lehrplan-Recherche (_stufen.json).
// Deskriptoren sind gesourct und mit konkreter Schulstufe (5–12) hinterlegt;
// StoffItems bleiben grob (Unter-/Oberstufe) und verlinken passende Deskriptoren.

export const informatikkiDeskriptoren: Deskriptor[] = [
  { id: 'at-informatikki-s9-algorithmen-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können alltägliche Abläufe als geordnete Schrittfolgen beschreiben und Bedingungen sowie Wiederholungen darin erkennen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s9-algorithmen-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können einfache Algorithmen in eigenen Worten erklären und deren Eingaben, Verarbeitungsschritte und Ergebnisse unterscheiden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s9-ki-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Beispiele für KI-Systeme im Alltag benennen und zwischen regelbasierten und lernenden digitalen Systemen unterscheiden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s9-ki-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Chancen und Risiken automatisierter Empfehlungen für Lernen, Freizeit und Information altersgerecht beschreiben.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s9-datenschutz-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können personenbezogene Daten erkennen und erklären, warum sparsame Datenweitergabe wichtig ist.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s9-datenschutz-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 9, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Schutzmaßnahmen wie starke Passwörter, Mehrfaktor-Anmeldung und vorsichtigen Umgang mit Links anwenden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-algorithmen-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können Variablen als veränderbare Werte in Abläufen beschreiben und einfache Zustandsänderungen nachvollziehen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-algorithmen-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können Ablaufpläne, Trace-Tabellen und Entscheidungspfade nutzen, um die Wirkung eines Algorithmus zu prüfen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-ki-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können erklären, dass KI-Systeme Muster aus Trainingsdaten ableiten und dadurch von Datenqualität abhängig sind.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-ki-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können einfache Fälle von Verzerrung, unfairer Behandlung oder Fehlklassifikation in KI-Anwendungen erkennen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-datenschutz-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Phishing, Malware, Social Engineering und Identitätsdiebstahl als unterschiedliche Sicherheitsrisiken einordnen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s10-datenschutz-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 10, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Datenschutz-Einstellungen digitaler Dienste prüfen und ihre Wirkung auf Sichtbarkeit, Tracking und Kontrolle beschreiben.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-algorithmen-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Lösungswege vergleichen und nach Verständlichkeit, Effizienz und Fehleranfälligkeit beurteilen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-algorithmen-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können komplexere Probleme in Teilprobleme zerlegen und geeignete Datenstrukturen als Konzept beschreiben.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-ki-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Grundideen von Klassifikation, Generierung und Vorhersage als typische KI-Leistungen unterscheiden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-ki-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können ethische Fragen zu Transparenz, Verantwortung und menschlicher Kontrolle bei KI-Systemen argumentativ bearbeiten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-datenschutz-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Grundprinzipien von Verschlüsselung, Zugriffskontrolle und Datensicherung in alltagsnahen Szenarien erklären.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s11-datenschutz-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Risiken vernetzter Systeme für Privatsphäre, Sicherheit und gesellschaftliche Teilhabe analysieren.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-algorithmen-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können Grenzen algorithmischer Verfahren reflektieren und erklären, warum nicht jedes Problem eindeutig oder automatisiert lösbar ist.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-algorithmen-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Entscheidungen hinsichtlich Nachvollziehbarkeit, Skalierung und gesellschaftlicher Folgen bewerten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-ki-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können generative KI, Deepfakes und automatisierte Entscheidungssysteme als technische und gesellschaftliche Phänomene kritisch einordnen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-ki-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können begründete Positionen zu KI-Regulierung, Urheberrecht, Bias und Verantwortung entwickeln.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-datenschutz-1', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Datenschutz, IT-Sicherheit und digitale Grundrechte in Konfliktfällen systematisch gegeneinander abwägen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-informatikki-s12-datenschutz-2', rahmenwerk: 'at-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Sicherheitsvorfälle, Datenlecks und Plattformrisiken anhand von Akteuren, Ursachen, Folgen und Präventionsmaßnahmen analysieren.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
];

export const informatikkiStoffItems: StoffItem[] = [
  { id: 'ik-algorithmisches-denken-ob', rahmenwerk: 'at-lehrplan', titel: 'Algorithmisches Denken', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'Algorithmisches Denken', deskriptorIds: ['at-informatikki-s9-algorithmen-1', 'at-informatikki-s9-algorithmen-2', 'at-informatikki-s10-algorithmen-1', 'at-informatikki-s10-algorithmen-2', 'at-informatikki-s11-algorithmen-1', 'at-informatikki-s11-algorithmen-2', 'at-informatikki-s12-algorithmen-1', 'at-informatikki-s12-algorithmen-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  { id: 'ik-ki-grundlagen-und-ethik-ob', rahmenwerk: 'at-lehrplan', titel: 'KI-Grundlagen & Ethik', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'KI-Grundlagen & Ethik', deskriptorIds: ['at-informatikki-s9-ki-1', 'at-informatikki-s9-ki-2', 'at-informatikki-s10-ki-1', 'at-informatikki-s10-ki-2', 'at-informatikki-s11-ki-1', 'at-informatikki-s11-ki-2', 'at-informatikki-s12-ki-1', 'at-informatikki-s12-ki-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  { id: 'ik-datenschutz-und-cybersecurity-ob', rahmenwerk: 'at-lehrplan', titel: 'Datenschutz & Cybersecurity', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'Datenschutz & Cybersecurity', deskriptorIds: ['at-informatikki-s9-datenschutz-1', 'at-informatikki-s9-datenschutz-2', 'at-informatikki-s10-datenschutz-1', 'at-informatikki-s10-datenschutz-2', 'at-informatikki-s11-datenschutz-1', 'at-informatikki-s11-datenschutz-2', 'at-informatikki-s12-datenschutz-1', 'at-informatikki-s12-datenschutz-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
];
