import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Latein — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Latein ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const lateinDeskriptoren: Deskriptor[] = [
  { id: 'at-latein-un-sprachkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können grundlegende lateinische Wortformen (Substantive, Adjektive, Verben) erkennen und in einfachen Sätzen anwenden.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-sprachkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache lateinische Satzstrukturen (Subjekt-Prädikat-Objekt) verstehen und übersetzen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-sprachkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einen Grundwortschatz von ca. 800-1000 lateinischen Wörtern aktiv und passiv verwenden.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-sprachkompetenz-4', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können lateinische Texte mit bekanntem Wortschatz und einfacher Grammatik sinngemäß ins Deutsche übertragen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-textkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können kurze lateinische Originaltexte (Fabeln, einfache historische Berichte) inhaltlich erfassen und wiedergeben.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-textkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Textsorten (Erzählung, Beschreibung, Bericht) in lateinischen Texten erkennen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-textkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache rhetorische Figuren (Alliteration, Anapher) in lateinischen Texten identifizieren.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-kulturkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Aspekte des römischen Alltagslebens (Familie, Schule, Wohnen) beschreiben und mit der Gegenwart vergleichen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-kulturkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können wichtige römische Gottheiten, Mythen und religiöse Praktiken benennen und ihre Bedeutung erklären.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-kulturkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können den Einfluss der römischen Kultur auf das heutige Europa an Beispielen (Recht, Sprache, Architektur) aufzeigen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-un-kulturkompetenz-4', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'unterstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können geographische und historische Grundkenntnisse über das Römische Reich in Karten und Zeitleisten einordnen.', quelle: 'BMBWF-Lehrplan AHS Latein (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-sprachkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe lateinische Satzstrukturen (Hypotaxen, Partizipialkonstruktionen, Konjunktiv) analysieren und übersetzen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-sprachkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einen erweiterten Wortschatz (ca. 1500-2000 Wörter) zur Lektüre anspruchsvoller Originaltexte nutzen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-sprachkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können stilistische Besonderheiten (Wortwahl, Satzbau, Rhetorik) in lateinischen Texten erkennen und deuten.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-sprachkompetenz-4', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können sprachvergleichend arbeiten und lateinische Strukturen mit modernen romanischen Sprachen oder dem Deutschen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-textkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Originaltexte bedeutender lateinischer Autoren (Cicero, Caesar, Vergil, Ovid, Seneca) interpretieren und in ihren historischen Kontext einordnen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-textkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können literarische Gattungen (Rede, Brief, Epos, Satire, Philosophie) unterscheiden und ihre Charakteristika benennen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-textkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können rhetorische Strategien und Argumentationstechniken in lateinischen Texten analysieren und bewerten.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-textkompetenz-4', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Rezeption und Wirkungsgeschichte antiker Texte in Literatur, Kunst und Philosophie bis in die Gegenwart nachvollziehen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-kulturkompetenz-1', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale Aspekte der römischen Gesellschaft (Politik, Recht, Sozialstruktur, Sklaverei) kritisch analysieren und mit modernen Gesellschaftsformen vergleichen.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-kulturkompetenz-2', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische und ethische Konzepte der Antike (Stoa, Epikureismus, platonische Ideenlehre) darlegen und ihre Relevanz für heute diskutieren.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-kulturkompetenz-3', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können das Fortwirken antiker Mythologie, Literatur und Kunst in europäischen Kulturtraditionen aufzeigen und reflektieren.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-latein-ob-kulturkompetenz-4', rahmenwerk: 'at-lehrplan', fach: 'latein', stufe: 'oberstufe', bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung lateinischer Fachsprachen in Wissenschaft, Medizin und Rechtswesen erkennen und Fachtermini etymologisch herleiten.', quelle: 'BMBWF-Lehrplan AHS Latein (Oberstufe) — RIS, Stand 2023' },
];

export const lateinStoffItems: StoffItem[] = [
  { id: 'la-sprachkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Sprachkompetenz', fach: 'latein', stufe: 'unterstufe', kategorie: 'Sprachkompetenz', deskriptorIds: ['at-latein-un-sprachkompetenz-1', 'at-latein-un-sprachkompetenz-2', 'at-latein-un-sprachkompetenz-3', 'at-latein-un-sprachkompetenz-4'], defaultAufgabentypen: ['lueckentext', 'multipleChoice'] },
  { id: 'la-textkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Textkompetenz', fach: 'latein', stufe: 'unterstufe', kategorie: 'Textkompetenz', deskriptorIds: ['at-latein-un-textkompetenz-1', 'at-latein-un-textkompetenz-2', 'at-latein-un-textkompetenz-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'la-kulturkompetenz-un', rahmenwerk: 'at-lehrplan', titel: 'Kulturkompetenz', fach: 'latein', stufe: 'unterstufe', kategorie: 'Kulturkompetenz', deskriptorIds: ['at-latein-un-kulturkompetenz-1', 'at-latein-un-kulturkompetenz-2', 'at-latein-un-kulturkompetenz-3', 'at-latein-un-kulturkompetenz-4'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'la-sprachkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Sprachkompetenz', fach: 'latein', stufe: 'oberstufe', kategorie: 'Sprachkompetenz', deskriptorIds: ['at-latein-ob-sprachkompetenz-1', 'at-latein-ob-sprachkompetenz-2', 'at-latein-ob-sprachkompetenz-3', 'at-latein-ob-sprachkompetenz-4'], defaultAufgabentypen: ['lueckentext', 'multipleChoice'] },
  { id: 'la-textkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Textkompetenz', fach: 'latein', stufe: 'oberstufe', kategorie: 'Textkompetenz', deskriptorIds: ['at-latein-ob-textkompetenz-1', 'at-latein-ob-textkompetenz-2', 'at-latein-ob-textkompetenz-3', 'at-latein-ob-textkompetenz-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'la-kulturkompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Kulturkompetenz', fach: 'latein', stufe: 'oberstufe', kategorie: 'Kulturkompetenz', deskriptorIds: ['at-latein-ob-kulturkompetenz-1', 'at-latein-ob-kulturkompetenz-2', 'at-latein-ob-kulturkompetenz-3', 'at-latein-ob-kulturkompetenz-4'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
];
