import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Medien und Demokratie — generiert aus Lehrplan-Recherche (_stufen.json).
// Deskriptoren sind gesourct und mit konkreter Schulstufe (5–12) hinterlegt;
// StoffItems bleiben grob (Unter-/Oberstufe) und verlinken passende Deskriptoren.

export const mediendemokratieDeskriptoren: Deskriptor[] = [
  { id: 'at-mediendemokratie-s9-medien-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Nachrichten, Kommentare, Werbung und persönliche Meinungen in digitalen und analogen Medien unterscheiden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s9-medien-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können bei Medienbeiträgen Urheber, Plattform, Veröffentlichungsdatum und erkennbare Absicht benennen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s9-demokratie-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können grundlegende demokratische Prinzipien wie Meinungsfreiheit, Pluralismus, Wahlen und Rechtsstaatlichkeit erklären.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s9-demokratie-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können beschreiben, warum unabhängige Medien für demokratische Öffentlichkeit bedeutsam sind.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s9-kommunikation-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können eigene Mediennutzung reflektieren und einfache Regeln für respektvolle Online-Kommunikation anwenden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s9-kommunikation-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 9, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können in kurzen Stellungnahmen zwischen persönlicher Meinung und begründetem Argument unterscheiden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-medien-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können einfache Fact-Checking-Schritte anwenden, indem sie Aussagen mit mehreren verlässlichen Quellen vergleichen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-medien-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können typische Merkmale von Desinformation, Clickbait und manipulativem Bild- oder Videomaterial erkennen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-demokratie-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Funktionen von Parlament, Regierung, Opposition und Medien in demokratischen Entscheidungsprozessen darstellen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-demokratie-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können erklären, wie politische Informationen über Medien verbreitet, gefiltert und bewertet werden.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-kommunikation-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können kontroverse Positionen zu gesellschaftlichen Fragen fair zusammenfassen und eigene Standpunkte begründet formulieren.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s10-kommunikation-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können Leserbrief, Kommentar und Social-Media-Post als unterschiedliche Formen öffentlicher Meinungsäußerung vergleichen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-medien-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Medienbeiträge multiperspektivisch analysieren und Interessen, Zielgruppen sowie Auslassungen herausarbeiten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-medien-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Auswahlmechanismen, Filterblasen und Plattformlogiken als Faktoren der Informationswahrnehmung beschreiben.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-demokratie-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Chancen und Risiken digitaler Beteiligungsformen für demokratische Prozesse analysieren.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-demokratie-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können den Einfluss von Medienberichterstattung auf Wahlkämpfe, Protestbewegungen und politische Agenda-Setting-Prozesse erläutern.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-kommunikation-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können argumentativ auf polarisierende Medienbeiträge reagieren und dabei demokratische Gesprächsregeln einhalten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s11-kommunikation-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können eigene Kommunikationsstrategien für sachliche Online-Debatten und schulische Öffentlichkeitsarbeit entwickeln.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-medien-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können komplexe Medienereignisse anhand journalistischer Standards, Quellenlage und gesellschaftlicher Wirkung kritisch beurteilen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-medien-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Desinformationskampagnen, Deepfakes und koordinierte Online-Manipulation als Herausforderungen demokratischer Öffentlichkeit bewerten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-demokratie-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Medienfreiheit, Regulierung, Plattformverantwortung und Grundrechte in demokratischen Konfliktlagen gegeneinander abwägen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-demokratie-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können die Wirkung medialer Öffentlichkeit auf Vertrauen, Partizipation und demokratische Institutionen reflektiert bewerten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-kommunikation-1', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können begründete öffentliche Stellungnahmen zu medienpolitischen Fragen verfassen und Gegenargumente sachlich einbeziehen.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
  { id: 'at-mediendemokratie-s12-kommunikation-2', rahmenwerk: 'at-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können eigene Verantwortung als Produzentinnen und Produzenten digitaler Öffentlichkeit reflektieren und Handlungsoptionen ableiten.', quelle: 'Arbeitsentwurf LUKA-Team, keine amtliche Quelle — Verordnung stand bei Erstellung noch aus (07/2026)' },
];

export const mediendemokratieStoffItems: StoffItem[] = [
  { id: 'md-medienkompetenz-und-quellenkritik-ob', rahmenwerk: 'at-lehrplan', titel: 'Medienkompetenz & Quellenkritik', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Medienkompetenz & Quellenkritik', deskriptorIds: ['at-mediendemokratie-s9-medien-1', 'at-mediendemokratie-s9-medien-2', 'at-mediendemokratie-s10-medien-1', 'at-mediendemokratie-s10-medien-2', 'at-mediendemokratie-s11-medien-1', 'at-mediendemokratie-s11-medien-2', 'at-mediendemokratie-s12-medien-1', 'at-mediendemokratie-s12-medien-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  { id: 'md-politische-bildung-und-demokratieverst-ndnis-ob', rahmenwerk: 'at-lehrplan', titel: 'Politische Bildung & Demokratieverständnis', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Politische Bildung & Demokratieverständnis', deskriptorIds: ['at-mediendemokratie-s9-demokratie-1', 'at-mediendemokratie-s9-demokratie-2', 'at-mediendemokratie-s10-demokratie-1', 'at-mediendemokratie-s10-demokratie-2', 'at-mediendemokratie-s11-demokratie-1', 'at-mediendemokratie-s11-demokratie-2', 'at-mediendemokratie-s12-demokratie-1', 'at-mediendemokratie-s12-demokratie-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
  { id: 'md-kommunikation-und-meinungsbildung-ob', rahmenwerk: 'at-lehrplan', titel: 'Kommunikation & Meinungsbildung', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Kommunikation & Meinungsbildung', deskriptorIds: ['at-mediendemokratie-s9-kommunikation-1', 'at-mediendemokratie-s9-kommunikation-2', 'at-mediendemokratie-s10-kommunikation-1', 'at-mediendemokratie-s10-kommunikation-2', 'at-mediendemokratie-s11-kommunikation-1', 'at-mediendemokratie-s11-kommunikation-2', 'at-mediendemokratie-s12-kommunikation-1', 'at-mediendemokratie-s12-kommunikation-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage'] },
];
