import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Philosophie — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Philosophie ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const philosophieDeskriptoren: Deskriptor[] = [
  { id: 'at-philosophie-ob-begriffe-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale philosophische Begriffe (Sein, Wahrheit, Freiheit, Gerechtigkeit, Glück) definieren, differenzieren und in verschiedenen philosophischen Traditionen verorten.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-begriffe-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Texte (Primär- und Sekundärliteratur) mit Hilfe fachspezifischer Terminologie und Methoden erschließen.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-begriffe-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können verschiedene philosophische Theorien und Positionen in ihrer historischen Entwicklung und systematischen Struktur vergleichen.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-begriffe-4', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Genese und Funktion philosophischer Begriffe in verschiedenen Diskursen analysieren.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-argumentation-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Argumentationen identifizieren, analysieren und auf ihre logische Schlüssigkeit überprüfen.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-argumentation-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können eigene philosophische Positionen entwickeln, begründen und in öffentlichen Diskursen vertreten.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-argumentation-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Grenzen und Voraussetzungen des eigenen Denkens und Erkennens reflektieren.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-argumentation-4', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können in philosophischen Diskussionen konsens- und dissensfähig argumentieren und mit Meinungsverschiedenheiten produktiv umgehen.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Fragestellungen auf aktuelle gesellschaftliche, politische und ethische Probleme anwenden.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können die erworbenen philosophischen Kompetenzen zu eigenen Lebensentwürfen und Weltdeutungen in Beziehung setzen.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-anwendung-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Perspektiven auf wissenschaftliche, technologische und kulturelle Entwicklungen anwenden.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-philosophie-ob-anwendung-4', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können durch philosophische Reflexion zu verantwortungsbewusstem und ethisch reflektiertem Handeln befähigt werden.', quelle: 'BMBWF-Lehrplan AHS Philosophie (Oberstufe) — RIS, Stand 2023' },
];

export const philosophieStoffItems: StoffItem[] = [
  { id: 'ph-begriffs-und-theoriekompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Begriffs- & Theoriekompetenz', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Begriffs- & Theoriekompetenz', deskriptorIds: ['at-philosophie-ob-begriffe-1', 'at-philosophie-ob-begriffe-2', 'at-philosophie-ob-begriffe-3', 'at-philosophie-ob-begriffe-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ph-argumentations-und-reflexionskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Argumentations- & Reflexionskompetenz', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Argumentations- & Reflexionskompetenz', deskriptorIds: ['at-philosophie-ob-argumentation-1', 'at-philosophie-ob-argumentation-2', 'at-philosophie-ob-argumentation-3', 'at-philosophie-ob-argumentation-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'ph-anwendung-und-transfer-ob', rahmenwerk: 'at-lehrplan', titel: 'Anwendung & Transfer', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['at-philosophie-ob-anwendung-1', 'at-philosophie-ob-anwendung-2', 'at-philosophie-ob-anwendung-3', 'at-philosophie-ob-anwendung-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
