import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Philosophie — generiert aus Lehrplan-Recherche (_stufen.json).
// Deskriptoren sind gesourct und mit konkreter Schulstufe (5–12) hinterlegt;
// StoffItems bleiben grob (Unter-/Oberstufe) und verlinken passende Deskriptoren.

export const philosophieDeskriptoren: Deskriptor[] = [
  { id: 'at-philosophie-s11-begriff-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale philosophische Begriffe (z. B. Wahrheit, Gerechtigkeit, Freiheit, Glück) klären und ihre historische Entwicklung nachvollziehen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-begriff-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können wichtige philosophische Positionen (z. B. Platon, Aristoteles, Kant, Nietzsche) in Grundzügen charakterisieren und vergleichen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-begriff-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Texte (z. B. Platons Höhlengleichnis, Kants kategorischer Imperativ) sinnerfassend lesen und in Grundzügen interpretieren.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-argumentation-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Argumente strukturiert aufbauen und auf Gegenargumente eingehen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-argumentation-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können eigene philosophische Positionen in Auseinandersetzung mit verschiedenen Traditionen begründen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-argumentation-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Fragen (z. B. Was ist der Mensch? Was soll ich tun?) reflexiv und dialogisch bearbeiten.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Erkenntnisse auf aktuelle gesellschaftliche und ethische Fragen übertragen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s11-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Konzepte zur Reflexion eigener Lebensfragen und gesellschaftlicher Herausforderungen nutzen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-begriff-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe philosophische Theorien und ihre historischen Kontexte multiperspektivisch analysieren.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-begriff-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Texte mit wissenschaftlichen Methoden interpretieren und in größere Zusammenhänge einordnen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-begriff-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können aktuelle philosophische Debatten (z. B. Philosophie des Geistes, politische Philosophie, Ästhetik) in Grundzügen erfassen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-argumentation-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe philosophische Argumentationen aufbauen und kritisch bewerten.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-argumentation-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können eigene philosophische Positionen souverän und reflektiert in akademischen und öffentlichen Diskursen vertreten.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-argumentation-3', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können mündliche Reifeprüfung differenziert und souverän führen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Erkenntnisse auf komplexe existenzielle und gesellschaftliche Herausforderungen souverän übertragen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
  { id: 'at-philosophie-s12-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Reflexion als Grundlage für lebenslanges Lernen und verantwortungsvolles Handeln nutzen.', quelle: 'BMBWF-Lehrplan AHS Philosophie — RIS, Stand 2023' },
];

export const philosophieStoffItems: StoffItem[] = [
  { id: 'ph-begriffs-und-theoriekompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Begriffs- & Theoriekompetenz', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Begriffs- & Theoriekompetenz', deskriptorIds: ['at-philosophie-s11-begriff-1', 'at-philosophie-s11-begriff-2', 'at-philosophie-s11-begriff-3', 'at-philosophie-s12-begriff-1', 'at-philosophie-s12-begriff-2', 'at-philosophie-s12-begriff-3'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ph-argumentations-und-reflexionskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Argumentations- & Reflexionskompetenz', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Argumentations- & Reflexionskompetenz', deskriptorIds: ['at-philosophie-s11-argumentation-1', 'at-philosophie-s11-argumentation-2', 'at-philosophie-s11-argumentation-3', 'at-philosophie-s12-argumentation-1', 'at-philosophie-s12-argumentation-2', 'at-philosophie-s12-argumentation-3'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'ph-anwendung-und-transfer-ob', rahmenwerk: 'at-lehrplan', titel: 'Anwendung & Transfer', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['at-philosophie-s11-anwendung-1', 'at-philosophie-s11-anwendung-2', 'at-philosophie-s12-anwendung-1', 'at-philosophie-s12-anwendung-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
