import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Psychologie — generiert aus Lehrplan-Recherche (_stufen.json).
// Deskriptoren sind gesourct und mit konkreter Schulstufe (5–12) hinterlegt;
// StoffItems bleiben grob (Unter-/Oberstufe) und verlinken passende Deskriptoren.

export const psychologieDeskriptoren: Deskriptor[] = [
  { id: 'at-psychologie-s10-fachwissen-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können grundlegende psychologische Begriffe und Konzepte (z. B. Wahrnehmung, Lernen, Motivation) definieren und anwenden.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-fachwissen-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können wichtige psychologische Strömungen (z. B. Behaviorismus, Psychoanalyse, kognitive Psychologie) in Grundzügen charakterisieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-fachwissen-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Modelle der Entwicklungspsychologie (z. B. Piaget, Erikson) beschreiben.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache psychologische Forschungsmethoden (z. B. Beobachtung, Befragung, Experiment) beschreiben und ihre Vor- und Nachteile benennen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache psychologische Studien kritisch analysieren und ihre Aussagekraft bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-reflexion-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse auf Alltagssituationen übertragen und kritisch reflektieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-reflexion-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können populärwissenschaftliche Darstellungen psychologischer Themen von wissenschaftlichen unterscheiden.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse auf Lern- und Leistungssituationen anwenden.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s10-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 10, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Konzepte zur Selbstreflexion und Persönlichkeitsentwicklung nutzen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-fachwissen-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können komplexe psychologische Theorien und Modelle (z. B. Sozialpsychologie, Persönlichkeitspsychologie, klinische Psychologie) analysieren und vergleichen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-fachwissen-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können psychologische Phänomene (z. B. Konformität, Aggression, Stress) mit verschiedenen theoretischen Ansätzen erklären.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-fachwissen-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können die historische Entwicklung psychologischer Forschung in Grundzügen nachvollziehen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können verschiedene psychologische Forschungsmethoden systematisch vergleichen und ihre Anwendbarkeit bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Studien hinsichtlich ihrer methodischen Qualität und ethischen Vertretbarkeit kritisch analysieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-reflexion-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse in verschiedenen Anwendungsfeldern (z. B. Bildung, Gesundheit, Arbeit) kritisch bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-reflexion-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können ethische Fragen psychologischer Forschung und Praxis reflektieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse auf komplexe gesellschaftliche und individuelle Fragestellungen übertragen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s11-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Konzepte zur Analyse sozialer Prozesse und zwischenmenschlicher Beziehungen nutzen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-fachwissen-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können aktuelle psychologische Forschung und ihre gesellschaftliche Relevanz multiperspektivisch analysieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-fachwissen-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können psychologische Theorien im Kontext philosophischer, biologischer und soziologischer Diskurse verorten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können eigenständig psychologische Fragestellungen entwickeln und mit wissenschaftlichen Methoden bearbeiten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Studien hinsichtlich ihrer methodischen Qualität, ethischen Vertretbarkeit und gesellschaftlichen Relevanz umfassend bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-reflexion-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse souverän und reflektiert in akademischen und öffentlichen Diskursen vertreten.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-reflexion-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können mündliche Reifeprüfung differenziert und souverän führen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse auf komplexe individuelle und gesellschaftliche Herausforderungen souverän übertragen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
  { id: 'at-psychologie-s12-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Konzepte als Grundlage für lebenslanges Lernen und verantwortungsvolles Handeln nutzen.', quelle: 'BMBWF-Lehrplan AHS Psychologie — RIS, Stand 2023' },
];

export const psychologieStoffItems: StoffItem[] = [
  { id: 'ps-fachwissen-ob', rahmenwerk: 'at-lehrplan', titel: 'Fachwissen', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Fachwissen', deskriptorIds: ['at-psychologie-s10-fachwissen-1', 'at-psychologie-s10-fachwissen-2', 'at-psychologie-s10-fachwissen-3', 'at-psychologie-s11-fachwissen-1', 'at-psychologie-s11-fachwissen-2', 'at-psychologie-s11-fachwissen-3', 'at-psychologie-s12-fachwissen-1', 'at-psychologie-s12-fachwissen-2'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'ps-methoden-und-erkenntniskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Methoden- & Erkenntniskompetenz', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Methoden- & Erkenntniskompetenz', deskriptorIds: ['at-psychologie-s10-methoden-1', 'at-psychologie-s10-methoden-2', 'at-psychologie-s11-methoden-1', 'at-psychologie-s11-methoden-2', 'at-psychologie-s12-methoden-1', 'at-psychologie-s12-methoden-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ps-reflexions-und-urteilskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Reflexions- & Urteilskompetenz', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Reflexions- & Urteilskompetenz', deskriptorIds: ['at-psychologie-s10-reflexion-1', 'at-psychologie-s10-reflexion-2', 'at-psychologie-s11-reflexion-1', 'at-psychologie-s11-reflexion-2', 'at-psychologie-s12-reflexion-1', 'at-psychologie-s12-reflexion-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'ps-anwendung-und-transfer-ob', rahmenwerk: 'at-lehrplan', titel: 'Anwendung & Transfer', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['at-psychologie-s10-anwendung-1', 'at-psychologie-s10-anwendung-2', 'at-psychologie-s11-anwendung-1', 'at-psychologie-s11-anwendung-2', 'at-psychologie-s12-anwendung-1', 'at-psychologie-s12-anwendung-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
