import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Psychologie — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Psychologie ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const psychologieDeskriptoren: Deskriptor[] = [
  { id: 'at-psychologie-ob-fachwissen-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können grundlegende psychologische Konzepte, Theorien und Modelle (zB Lerntheorien, Entwicklungspsychologie, Sozialpsychologie) benennen und erklären.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-fachwissen-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können zentrale Forschungsergebnisse der Psychologie zu Wahrnehmung, Gedächtnis, Motivation und Emotion darlegen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-fachwissen-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können historische Entwicklungen und wichtige Vertreter der Psychologie (Freud, Piaget, Skinner, Rogers) in ihren Grundzügen darstellen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-fachwissen-4', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können psychologische Fachbegriffe und Forschungsmethoden (Experiment, Beobachtung, Interview) unterscheiden und ihre Anwendungsbereiche benennen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-methoden-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Fragestellungen formulieren und geeignete Untersuchungsmethoden zur Beantwortung auswählen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-methoden-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Studien kritisch analysieren, ihre methodische Qualität bewerten und Schlussfolgerungen überprüfen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-methoden-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache psychologische Untersuchungen (Beobachtungen, Befragungen, Experimente) planen, durchführen und auswerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-methoden-4', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können statistische Grundbegriffe (Mittelwert, Korrelation, Signifikanz) interpretieren und ihre Bedeutung für psychologische Forschung erklären.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-reflexion-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse kritisch reflektieren, ihre Gültigkeit prüfen und ethische Implikationen bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-reflexion-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können verschiedene psychologische Erklärungsansätze für menschliches Verhalten vergleichen und ihre Stärken und Grenzen diskutieren.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-reflexion-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Konzepte auf eigene Erfahrungen und Beobachtungen anwenden und deren Erklärungsgehalt überprüfen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-reflexion-4', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können gesellschaftliche Diskurse zu psychologischen Themen (zB Stress, Sucht, mentale Gesundheit) fachlich fundiert mitgestalten.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-anwendung-1', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erkenntnisse auf konkrete Lebensbereiche (Schule, Beruf, Beziehungen, Gesundheit) übertragen und Handlungsempfehlungen ableiten.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-anwendung-2', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können Strategien zur Stressbewältigung, Lernoptimierung und Konfliktlösung auf der Grundlage psychologischer Forschung entwickeln und anwenden.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-anwendung-3', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Beratungsmöglichkeiten und therapeutische Ansätze beschreiben und deren Wirksamkeit bewerten.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-psychologie-ob-anwendung-4', rahmenwerk: 'at-lehrplan', fach: 'psychologie', stufe: 'oberstufe', bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Prinzipien in angewandten Bereichen (Arbeitspsychologie, Pädagogik, Gesundheitswesen) erkennen und ihre praktische Relevanz aufzeigen.', quelle: 'BMBWF-Lehrplan AHS Psychologie (Oberstufe) — RIS, Stand 2023' },
];

export const psychologieStoffItems: StoffItem[] = [
  { id: 'ps-fachwissen-ob', rahmenwerk: 'at-lehrplan', titel: 'Fachwissen', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Fachwissen', deskriptorIds: ['at-psychologie-ob-fachwissen-1', 'at-psychologie-ob-fachwissen-2', 'at-psychologie-ob-fachwissen-3', 'at-psychologie-ob-fachwissen-4'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'ps-methoden-und-erkenntniskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Methoden- & Erkenntniskompetenz', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Methoden- & Erkenntniskompetenz', deskriptorIds: ['at-psychologie-ob-methoden-1', 'at-psychologie-ob-methoden-2', 'at-psychologie-ob-methoden-3', 'at-psychologie-ob-methoden-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'ps-reflexions-und-urteilskompetenz-ob', rahmenwerk: 'at-lehrplan', titel: 'Reflexions- & Urteilskompetenz', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Reflexions- & Urteilskompetenz', deskriptorIds: ['at-psychologie-ob-reflexion-1', 'at-psychologie-ob-reflexion-2', 'at-psychologie-ob-reflexion-3', 'at-psychologie-ob-reflexion-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'ps-anwendung-und-transfer-ob', rahmenwerk: 'at-lehrplan', titel: 'Anwendung & Transfer', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['at-psychologie-ob-anwendung-1', 'at-psychologie-ob-anwendung-2', 'at-psychologie-ob-anwendung-3', 'at-psychologie-ob-anwendung-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
