import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Religion — generiert aus Lehrplan-Recherche (Task 2).
// Deskriptoren sind gesourct (quelle = offizielle URL); StoffItems enthalten
// vorgeschlagene defaultAufgabentypen je Kompetenzbereich.

const Q = (stufe: string) =>
  `Gesourct, angelehnt an offiziellen Lehrplan AHS Religion ${stufe} — siehe Quell-URL in der Forschungsdatei.`;

export const religionDeskriptoren: Deskriptor[] = [
  { id: 'at-religion-un-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Wahrnehmen & Verstehen', code: 'A', text: 'Die Schülerinnen und Schüler können religiös bedeutsame Phänomene in ihrer Lebenswelt wahrnehmen und beschreiben.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Wahrnehmen & Verstehen', code: 'B', text: 'Die Schülerinnen und Schüler können religiöse Sprach- und Gestaltungsformen (Symbole, Rituale, Gebete) erkennen und ihre Bedeutung verstehen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Wahrnehmen & Verstehen', code: 'A', text: 'Die Schülerinnen und Schüler können biblische Erzählungen und ihre zentralen Botschaften wiedergeben und deuten.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-wahrnehmen-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Wahrnehmen & Verstehen', code: 'B', text: 'Die Schülerinnen und Schüler können grundlegende Aspekte der christlichen Religion (Gottesbild, Jesus Christus, Kirche) beschreiben und erklären.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-deuten-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Deuten & Urteilen', code: 'B', text: 'Die Schülerinnen und Schüler können religiöse Texte (Bibel, Gleichnisse) interpretieren und ihre Aussagen für heute deuten.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-deuten-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Deuten & Urteilen', code: 'D', text: 'Die Schülerinnen und Schüler können ethische Fragen aus ihrer Lebenswelt identifizieren und verschiedene Positionen dazu darstellen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-deuten-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Deuten & Urteilen', code: 'D', text: 'Die Schülerinnen und Schüler können Gemeinsamkeiten und Unterschiede zwischen Religionen und Weltanschauungen benennen und respektvoll damit umgehen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-deuten-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Deuten & Urteilen', code: 'B', text: 'Die Schülerinnen und Schüler können die Bedeutung christlicher Feste und Feiern im Kirchenjahr erklären und ihre Symbolik deuten.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-reflektieren-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Reflektieren & Kommunizieren', code: 'D', text: 'Die Schülerinnen und Schüler können eigene religiöse Vorstellungen artikulieren und mit anderen ins Gespräch bringen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-reflektieren-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Reflektieren & Kommunizieren', code: 'E', text: 'Die Schülerinnen und Schüler können Fragen nach Sinn und Ziel des Lebens stellen und verschiedene Antwortmöglichkeiten reflektieren.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-reflektieren-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Reflektieren & Kommunizieren', code: 'D', text: 'Die Schülerinnen und Schüler können in einfachen ethischen Dilemmata begründet Stellung nehmen und ihre Position vertreten.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-reflektieren-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Reflektieren & Kommunizieren', code: 'E', text: 'Die Schülerinnen und Schüler können Erfahrungen mit Gerechtigkeit und Ungerechtigkeit beschreiben und christliche Antworten darauf reflektieren.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-gestalten-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Gestalten & Handeln', code: 'C', text: 'Die Schülerinnen und Schüler können an religiösen Ausdrucksformen (Gebete, Lieder, Rituale) aktiv teilnehmen und diese mitgestalten.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-gestalten-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Gestalten & Handeln', code: 'C', text: 'Die Schülerinnen und Schüler können in konkreten Situationen solidarisches und verantwortungsvolles Handeln zeigen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-gestalten-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Gestalten & Handeln', code: 'E', text: 'Die Schülerinnen und Schüler können Projekte zur Nächstenliebe und sozialen Gerechtigkeit planen und durchführen.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-un-gestalten-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'unterstufe', bereich: 'Gestalten & Handeln', code: 'C', text: 'Die Schülerinnen und Schüler können Wege zur Konfliktlösung und Versöhnung aufzeigen und in ihrem Umfeld praktizieren.', quelle: 'BMBWF-Lehrplan AHS Religion (Unterstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-wahrnehmen-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Wahrnehmen & Verstehen', code: 'A', text: 'Die Schülerinnen und Schüler können sich selbst, ihr Lebensumfeld und die Welt mit ihren Chancen, Problemen, Grenzen und Entwicklungsmöglichkeiten offen und differenziert wahrnehmen und diese Wahrnehmung zum Ausdruck bringen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-wahrnehmen-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Wahrnehmen & Verstehen', code: 'A', text: 'Die Schülerinnen und Schüler können religiös bedeutsame Phänomene wahrnehmen und Sprach-, Kommunikations- und Gestaltungsformen erkennen, die für das religiöse Selbst- und Weltverständnis charakteristisch sind.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-wahrnehmen-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Wahrnehmen & Verstehen', code: 'A', text: 'Die Schülerinnen und Schüler erkennen die vielfältigen Dimensionen religiösen Denkens und Handelns und reflektieren die unterschiedlichen Zugänge zur Religion sowie verschiedene Ausdrucksformen von Spiritualität.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-wahrnehmen-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Wahrnehmen & Verstehen', code: 'B', text: 'Die Schülerinnen und Schüler können die zentrale Botschaft, die Grundbegriffe, die Aussagen der wichtigsten Texte und Lehren sowie entscheidende Phasen und geschichtliche Schlüsselereignisse ihrer Religion in ihrer konfessionellen Ausprägung wiedergeben und deuten.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-deuten-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Deuten & Urteilen', code: 'B', text: 'Die Schülerinnen und Schüler können zwischen verschiedenen kulturellen Ausprägungen ihrer Religion in ihrer konfessionellen Ausprägung differenzieren, deren Gemeinsamkeiten und Unterschiede erkennen und sensibel darstellen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-deuten-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Deuten & Urteilen', code: 'B', text: 'Die Schülerinnen und Schüler können Grundformen religiöser Praxis (zB Rituale sowie religiöse Riten und Feiern) in ihrer allgemeinen und persönlichen Bedeutung beschreiben und reflektieren.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-deuten-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Deuten & Urteilen', code: 'D', text: 'Die Schülerinnen und Schüler können verschiedene (religiös fundierte) Modelle ethischen Handelns beschreiben und beurteilen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-deuten-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Deuten & Urteilen', code: 'D', text: 'Die Schülerinnen und Schüler sind fähig, auf der Basis religiöser Grundwerte zu ethischen Konflikten sowie den damit verbundenen gesellschaftlichen Diskursen Stellung zu nehmen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-reflektieren-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Reflektieren & Kommunizieren', code: 'D', text: 'Auf Basis ihres Wissens und der erworbenen dialogischen Grundhaltung sind die Schülerinnen und Schüler in der Lage, in der (religions)pluralen Gesellschaft mit Angehörigen anderer Kulturen, Konfessionen und Religionen respektvoll zu kommunizieren.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-reflektieren-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Reflektieren & Kommunizieren', code: 'E', text: 'Die Schülerinnen und Schüler können eigene religiöse Vorstellungen auf Grund der zentralen Deutungsmuster ihrer Religion in ihrer konfessionellen Ausprägung reflektieren und wichtige Grundlagen anderer Religionen, Konfessionen oder Weltanschauungen darlegen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-reflektieren-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Reflektieren & Kommunizieren', code: 'D', text: 'Die Schülerinnen und Schüler sind in der Lage, die zentralen Deutungsmuster ihrer Religion in ihrer konfessionellen Ausprägung mit den Deutungsmustern anderer religiöser Traditionen, Weltanschauungen und Weltbilder in Beziehung zu setzen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-reflektieren-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Reflektieren & Kommunizieren', code: 'D', text: 'Die Schülerinnen und Schüler sind fähig, die zentrale Botschaft und die Deutungsmuster ihrer Religion in ihrer konfessionellen Ausprägung als relevant für das Leben des oder der Einzelnen und das Leben in der Gemeinschaft aufzuzeigen und zu würdigen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-gestalten-1', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Gestalten & Handeln', code: 'C', text: 'Die Schülerinnen und Schüler sind in der Lage, in (inter)kulturellen und ethischen Herausforderungen unserer Welt Handlungsoptionen zu entwickeln und zu begründen sowie Möglichkeiten von eigenem verantwortlichem Handeln zu beschreiben.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-gestalten-2', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Gestalten & Handeln', code: 'E', text: 'Die Schülerinnen und Schüler können einen verantwortlichen Umgang mit Mensch und Natur darlegen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-gestalten-3', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Gestalten & Handeln', code: 'C', text: 'Die Schülerinnen und Schüler können sich mit der Frage nach Gerechtigkeit, Frieden und Bewahrung der Schöpfung auseinandersetzen und Wege zu solidarischem Handeln aufzeigen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
  { id: 'at-religion-ob-gestalten-4', rahmenwerk: 'at-lehrplan', fach: 'religion', stufe: 'oberstufe', bereich: 'Gestalten & Handeln', code: 'E', text: 'Die Schülerinnen und Schüler können Möglichkeiten der Mitgestaltung von Kirche und Gesellschaft in ihrem Umfeld identifizieren und sich engagiert einbringen.', quelle: 'BMBWF-Lehrplan AHS Religion (Oberstufe) — RIS, Stand 2023' },
];

export const religionStoffItems: StoffItem[] = [
  { id: 're-wahrnehmen-und-verstehen-un', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmen & Verstehen', fach: 'religion', stufe: 'unterstufe', kategorie: 'Wahrnehmen & Verstehen', deskriptorIds: ['at-religion-un-wahrnehmen-1', 'at-religion-un-wahrnehmen-2', 'at-religion-un-wahrnehmen-3', 'at-religion-un-wahrnehmen-4'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 're-deuten-und-urteilen-un', rahmenwerk: 'at-lehrplan', titel: 'Deuten & Urteilen', fach: 'religion', stufe: 'unterstufe', kategorie: 'Deuten & Urteilen', deskriptorIds: ['at-religion-un-deuten-1', 'at-religion-un-deuten-2', 'at-religion-un-deuten-3', 'at-religion-un-deuten-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 're-reflektieren-und-kommunizieren-un', rahmenwerk: 'at-lehrplan', titel: 'Reflektieren & Kommunizieren', fach: 'religion', stufe: 'unterstufe', kategorie: 'Reflektieren & Kommunizieren', deskriptorIds: ['at-religion-un-reflektieren-1', 'at-religion-un-reflektieren-2', 'at-religion-un-reflektieren-3', 'at-religion-un-reflektieren-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 're-gestalten-und-handeln-un', rahmenwerk: 'at-lehrplan', titel: 'Gestalten & Handeln', fach: 'religion', stufe: 'unterstufe', kategorie: 'Gestalten & Handeln', deskriptorIds: ['at-religion-un-gestalten-1', 'at-religion-un-gestalten-2', 'at-religion-un-gestalten-3', 'at-religion-un-gestalten-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
  { id: 're-wahrnehmen-und-verstehen-ob', rahmenwerk: 'at-lehrplan', titel: 'Wahrnehmen & Verstehen', fach: 'religion', stufe: 'oberstufe', kategorie: 'Wahrnehmen & Verstehen', deskriptorIds: ['at-religion-ob-wahrnehmen-1', 'at-religion-ob-wahrnehmen-2', 'at-religion-ob-wahrnehmen-3', 'at-religion-ob-wahrnehmen-4'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 're-deuten-und-urteilen-ob', rahmenwerk: 'at-lehrplan', titel: 'Deuten & Urteilen', fach: 'religion', stufe: 'oberstufe', kategorie: 'Deuten & Urteilen', deskriptorIds: ['at-religion-ob-deuten-1', 'at-religion-ob-deuten-2', 'at-religion-ob-deuten-3', 'at-religion-ob-deuten-4'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 're-reflektieren-und-kommunizieren-ob', rahmenwerk: 'at-lehrplan', titel: 'Reflektieren & Kommunizieren', fach: 'religion', stufe: 'oberstufe', kategorie: 'Reflektieren & Kommunizieren', deskriptorIds: ['at-religion-ob-reflektieren-1', 'at-religion-ob-reflektieren-2', 'at-religion-ob-reflektieren-3', 'at-religion-ob-reflektieren-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 're-gestalten-und-handeln-ob', rahmenwerk: 'at-lehrplan', titel: 'Gestalten & Handeln', fach: 'religion', stufe: 'oberstufe', kategorie: 'Gestalten & Handeln', deskriptorIds: ['at-religion-ob-gestalten-1', 'at-religion-ob-gestalten-2', 'at-religion-ob-gestalten-3', 'at-religion-ob-gestalten-4'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
];
