import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Deutsch — kuratierter Kompetenzkatalog für deutsche Schulabschlüsse.

export const deutschDeDeskriptoren: Deskriptor[] = [
  { id: 'de-deutsch-s6-zuhoeren-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können längeren mündlichen Beiträgen folgen und zentrale Aussagen sowie wichtige Einzelinformationen wiedergeben.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-zuhoeren-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können in Diskussionen auf andere Beiträge eingehen, Gesprächsregeln einhalten und eigene Standpunkte nachvollziehbar begründen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-zuhoeren-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können anspruchsvolle mündliche und mediale Beiträge unter Berücksichtigung von Argumentationsgang, Adressat und Intention erschließen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-zuhoeren-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Zuhören & Sprechen', code: '', text: 'Die Schülerinnen und Schüler können in fachlichen Gesprächen eigenständig argumentieren, Gegenpositionen präzise aufnehmen und Gesprächsergebnisse sichern.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s6-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können Sach- und Gebrauchstexten zentrale Informationen entnehmen, diese ordnen und mit eigenen Worten zusammenfassen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können argumentierende Texte hinsichtlich These, Begründungen, Belegen und Schlussfolgerungen analysieren.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können literarische und pragmatische Texte unter Einbeziehung ihrer historischen, gesellschaftlichen und kommunikativen Bedingungen erschließen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Lesen & Textverständnis', code: '', text: 'Die Schülerinnen und Schüler können komplexe Textarrangements und Materialien vergleichend auswerten und daraus eigenständige Deutungs- und Arbeitsfragen entwickeln.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s6-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können informierende und erzählende Texte adressatenbezogen, verständlich und in einer nachvollziehbaren Ordnung verfassen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können eine begründete Stellungnahme oder Erörterung auf der Grundlage ausgewählter Materialien strukturiert schreiben.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können literarische und pragmatische Texte analytisch deuten und ihre Ergebnisse mit geeigneten Textbelegen in einer kohärenten Darstellung entfalten.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können materialgestützt informieren, argumentieren oder erörtern und dabei Schreibhandlung, Textsorte, Adressat und Umfang sicher steuern.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s6-sprachbewusstsein-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können sprachliche Entscheidungen in eigenen Texten prüfen und grundlegende Regeln der Rechtschreibung und Zeichensetzung anwenden.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-sprachbewusstsein-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können die Wirkung sprachlicher Mittel in unterschiedlichen Kommunikationssituationen erkennen und ihren eigenen Sprachgebrauch reflektieren.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-sprachbewusstsein-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können sprachliche Register, Varietäten und rhetorische Verfahren im Hinblick auf Funktion, Situation und Wirkung analysieren.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-sprachbewusstsein-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Sprachbewusstsein', code: '', text: 'Die Schülerinnen und Schüler können Veränderungen des Deutschen und den Einfluss digitaler Kommunikation differenziert beschreiben und sprachkritisch beurteilen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s6-literarisch-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Figuren, Handlung und Erzählperspektive in altersgemäßen Erzählungen beschreiben und erste Deutungen entwickeln.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-literarisch-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Gedichte, Kurzprosa und dramatische Szenen anhand von Form, Sprache, Figurenkonstellation und Konfliktgestaltung untersuchen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-literarisch-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen und Schüler können literarische Texte in epochale und gesellschaftliche Zusammenhänge einordnen und unterschiedliche Interpretationsansätze vergleichen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-literarisch-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Literarische Bildung', code: '', text: 'Die Schülerinnen und Schüler können literarische Texte eigenständig interpretieren, Ambivalenzen herausarbeiten und ihre Deutung textnah sowie methodisch reflektiert begründen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s6-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können Satzglieder und grundlegende Satzarten bestimmen sowie einfache Satzgefüge bilden.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s9-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können Nebensätze, Konnektoren und Tempusformen funktional einsetzen, um Beziehungen zwischen Aussagen präzise auszudrücken.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss — kuratierter Entwurf' },
  { id: 'de-deutsch-s11-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 11, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können syntaktische Strukturen und sprachliche Kohäsionsmittel in anspruchsvollen Texten analysieren und für eigene Texte nutzen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-deutsch-s13-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'deutsch', stufe: 'oberstufe', schulstufe: 13, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können grammatische Varianten und Satzbauentscheidungen im Hinblick auf Präzision, Stil und argumentative Wirkung begründet beurteilen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
];

export const deutschDeStoffItems: StoffItem[] = [
  { id: 'de-deu-zuhoeren-un', rahmenwerk: 'de-lehrplan', titel: 'Zuhören, Gespräch und Vortrag', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Zuhören & Sprechen', deskriptorIds: ['de-deutsch-s6-zuhoeren-1', 'de-deutsch-s9-zuhoeren-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'de-deu-lesen-un', rahmenwerk: 'de-lehrplan', titel: 'Sachtexte lesen und auswerten', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Lesen & Textverständnis', deskriptorIds: ['de-deutsch-s6-lesen-1', 'de-deutsch-s9-lesen-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-deu-schreiben-un', rahmenwerk: 'de-lehrplan', titel: 'Informieren, erzählen und argumentieren', fach: 'deutsch', stufe: 'unterstufe', kategorie: 'Schreiben', deskriptorIds: ['de-deutsch-s6-schreiben-1', 'de-deutsch-s9-schreiben-1'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'de-deu-literatur-ob', rahmenwerk: 'de-lehrplan', titel: 'Literatur analysieren und interpretieren', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Literarische Bildung', deskriptorIds: ['de-deutsch-s11-literarisch-1', 'de-deutsch-s13-literarisch-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'offeneSchreibaufgabe'] },
  { id: 'de-deu-sprachbewusstsein-ob', rahmenwerk: 'de-lehrplan', titel: 'Sprache, Register und Sprachwandel', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Sprachbewusstsein', deskriptorIds: ['de-deutsch-s11-sprachbewusstsein-1', 'de-deutsch-s13-sprachbewusstsein-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-deu-grammatik-ob', rahmenwerk: 'de-lehrplan', titel: 'Satzbau und sprachliche Präzision', fach: 'deutsch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['de-deutsch-s11-grammatik-1', 'de-deutsch-s13-grammatik-1'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
];
