import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Englisch — kuratierter Kompetenzkatalog für deutsche Schulabschlüsse.

export const englischDeDeskriptoren: Deskriptor[] = [
  { id: 'de-englisch-s6-hoeren-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können kurze, klar artikulierte Hörtexte aus Alltag und Schule verstehen und wesentliche Informationen entnehmen.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-hoeren-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können Gesprächen, Durchsagen und medialen Beiträgen zu vertrauten Themen folgen und Standpunkte sowie Begründungen erkennen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-hoeren-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Hören', code: '', text: 'Die Schülerinnen und Schüler können anspruchsvolle authentische Hör- und audiovisuelle Texte global und selektiv verstehen und Sprecherintentionen erschließen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können kurze Alltagstexte und einfache Geschichten lesen, Kernaussagen erfassen und unbekannte Wörter aus dem Kontext erschließen.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können Sachtexte, Berichte und literarische Auszüge hinsichtlich Inhalt, Aufbau und ausgewählter sprachlicher Mittel auswerten.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Lesen', code: '', text: 'Die Schülerinnen und Schüler können komplexe fiktionale und nichtfiktionale Texte analysieren, implizite Aussagen erschließen und Textbezüge herstellen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-gespraeche-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können in vertrauten Situationen Fragen stellen, antworten und mit einfachen Redemitteln Informationen austauschen.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-gespraeche-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können Gespräche über vertraute und schulische Themen führen, Rückfragen stellen und auf Gesprächspartner angemessen reagieren.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-gespraeche-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'An Gesprächen teilnehmen', code: '', text: 'Die Schülerinnen und Schüler können sich spontan und differenziert an Diskussionen beteiligen, Positionen abwägen und Gesprächsverläufe konstruktiv mitgestalten.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-sprechen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können Personen, Orte, Abläufe und eigene Interessen mit einfachen, verständlichen Sätzen beschreiben.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-sprechen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können Erlebnisse und Sachverhalte zusammenhängend darstellen, Beispiele geben und die eigene Meinung begründen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-sprechen-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Zusammenhängend sprechen', code: '', text: 'Die Schülerinnen und Schüler können komplexe Sachverhalte strukturiert präsentieren, Argumente gewichten und auf Nachfragen differenziert eingehen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können kurze persönliche Mitteilungen und einfache Beschreibungen verständlich und weitgehend korrekt verfassen.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können zusammenhängende Texte zu vertrauten Sachverhalten verfassen, Informationen ordnen und adressatengerecht formulieren.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Schreiben', code: '', text: 'Die Schülerinnen und Schüler können argumentierende, informierende und kreative Texte kohärent, adressatenbezogen und sprachlich differenziert verfassen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-sprachmittlung-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen und Schüler können einfache Informationen aus kurzen englischen oder deutschen Texten sinngemäß für andere wiedergeben.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-sprachmittlung-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen und Schüler können die für eine Situation wesentlichen Informationen aus Texten und Gesprächen adressatengerecht übertragen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-sprachmittlung-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Sprachmittlung', code: '', text: 'Die Schülerinnen und Schüler können komplexe Informationen sinngemäß, situationsgerecht und unter Wahrung zentraler Bedeutungen zwischen Deutsch und Englisch vermitteln.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Satzmuster, Frageformen und Zeitformen in vertrauten Situationen anwenden.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können ein erweitertes Repertoire an Zeitformen, Modalverben und Nebensatzstrukturen funktional verwenden.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Grammatik', code: '', text: 'Die Schülerinnen und Schüler können grammatische Mittel sicher und variabel einsetzen und deren Beitrag zu Präzision, Register und Textwirkung reflektieren.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
  { id: 'de-englisch-s6-wortschatz-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen und Schüler können einen grundlegenden Wortschatz zu Personen, Alltag, Schule und Freizeit verstehen und aktiv verwenden.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-s9-wortschatz-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen und Schüler können thematischen und funktionalen Wortschatz zu gesellschaftlichen, kulturellen und schulischen Themen differenziert nutzen.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-s12-wortschatz-1', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wortschatz', code: '', text: 'Die Schülerinnen und Schüler können idiomatische Wendungen, Kollokationen und registergerechten Wortschatz in anspruchsvollen Kommunikationssituationen sicher einsetzen.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
];

export const englischDeStoffItems: StoffItem[] = [
  { id: 'de-eng-hoeren-un', rahmenwerk: 'de-lehrplan', titel: 'Hörverstehen im Alltag und in Medien', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Hören', deskriptorIds: ['de-englisch-s6-hoeren-1', 'de-englisch-s9-hoeren-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-eng-lesen-un', rahmenwerk: 'de-lehrplan', titel: 'Lesen: Sachtexte und Geschichten', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Lesen', deskriptorIds: ['de-englisch-s6-lesen-1', 'de-englisch-s9-lesen-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-eng-wortschatz-un', rahmenwerk: 'de-lehrplan', titel: 'Thematischer Wortschatz', fach: 'englisch', stufe: 'unterstufe', kategorie: 'Wortschatz', deskriptorIds: ['de-englisch-s6-wortschatz-1', 'de-englisch-s9-wortschatz-1'], defaultAufgabentypen: ['vokabeluebung', 'kreuzwortraetsel'] },
  { id: 'de-eng-sprechen-ob', rahmenwerk: 'de-lehrplan', titel: 'Präsentieren und diskutieren', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['de-englisch-s12-sprechen-1', 'de-englisch-s12-gespraeche-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'de-eng-schreiben-ob', rahmenwerk: 'de-lehrplan', titel: 'Argumentative und informative Texte', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Schreiben', deskriptorIds: ['de-englisch-s12-schreiben-1'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'de-eng-sprachmittlung-ob', rahmenwerk: 'de-lehrplan', titel: 'Sprachmittlung in realen Situationen', fach: 'englisch', stufe: 'oberstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['de-englisch-s12-sprachmittlung-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
