import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Ethik — kuratierter, länderübergreifender Kern für deutsche Schulen.

const QUELLE = 'EPA Ethik (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const ethikDeDeskriptoren: Deskriptor[] = [
  { id: 'de-ethik-s8-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 8, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethisch relevante Situationen aus Schule, Familie und digitaler Lebenswelt wahrnehmen und sachlich beschreiben.', quelle: QUELLE },
  { id: 'de-ethik-s9-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 9, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können in Konflikten unterschiedliche Bedürfnisse, Interessen und Wertvorstellungen erkennen.', quelle: QUELLE },
  { id: 'de-ethik-s10-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 10, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Dimensionen gesellschaftlicher Fragen wie Gerechtigkeit, Freiheit und Verantwortung herausarbeiten.', quelle: QUELLE },
  { id: 'de-ethik-s11-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Problemstellungen in politischen, wissenschaftlichen und medialen Debatten differenziert erfassen.', quelle: QUELLE },
  { id: 'de-ethik-s12-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können Voraussetzungen und Folgen ethischer Entscheidungen in komplexen Lebens- und Gesellschaftszusammenhängen beschreiben.', quelle: QUELLE },
  { id: 'de-ethik-s13-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 13, bereich: 'Wahrnehmen & Beschreiben', code: '', text: 'Die Schülerinnen und Schüler können ethische Konflikte unter Einbeziehung empirischer Informationen, institutioneller Rahmenbedingungen und betroffener Perspektiven präzise darstellen.', quelle: QUELLE },
  { id: 'de-ethik-s8-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 8, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können einfache Argumente in Alltagssituationen unterscheiden und Gründe für eine Entscheidung benennen.', quelle: QUELLE },
  { id: 'de-ethik-s9-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 9, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können ein ethisches Dilemma strukturieren, Handlungsoptionen vergleichen und Argumente auf ihre Folgerichtigkeit prüfen.', quelle: QUELLE },
  { id: 'de-ethik-s10-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 10, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können Grundzüge von Pflichtethik, Folgenethik und Tugendethik unterscheiden und auf konkrete Fälle beziehen.', quelle: QUELLE },
  { id: 'de-ethik-s11-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können normative Argumentationen rekonstruieren, zentrale Begriffe klären und Einwände systematisch formulieren.', quelle: QUELLE },
  { id: 'de-ethik-s12-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können konkurrierende ethische Theorien anhand eines Problems vergleichen und ihre Voraussetzungen sowie Konsequenzen offenlegen.', quelle: QUELLE },
  { id: 'de-ethik-s13-analysieren-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 13, bereich: 'Analysieren & Argumentieren', code: '', text: 'Die Schülerinnen und Schüler können komplexe ethische Argumentationen wissenschaftspropädeutisch prüfen, Gegenargumente gewichten und ein begründetes Urteil vorbereiten.', quelle: QUELLE },
  { id: 'de-ethik-s8-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 8, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können zu überschaubaren Konflikten ein eigenes Urteil formulieren und auf nachvollziehbare Gründe stützen.', quelle: QUELLE },
  { id: 'de-ethik-s9-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 9, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können die eigene Position im Vergleich mit anderen begründet überprüfen und gegebenenfalls verändern.', quelle: QUELLE },
  { id: 'de-ethik-s10-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 10, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können moralische Urteile von persönlichen Vorlieben unterscheiden und Kriterien für Gerechtigkeit und Verantwortung anwenden.', quelle: QUELLE },
  { id: 'de-ethik-s11-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können eigene normative Urteile transparent begründen und die Grenzen des eigenen Standpunkts reflektieren.', quelle: QUELLE },
  { id: 'de-ethik-s12-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können ethische Urteile unter Unsicherheit und Interessenkonflikten differenzieren und ihre Entscheidungskriterien erläutern.', quelle: QUELLE },
  { id: 'de-ethik-s13-urteilen-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 13, bereich: 'Urteilen & Reflektieren', code: '', text: 'Die Schülerinnen und Schüler können ein eigenständiges, theoriebezogenes Urteil entwickeln und dessen Tragweite für individuelle und gesellschaftliche Verantwortung einschätzen.', quelle: QUELLE },
  { id: 'de-ethik-s8-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 8, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können die Sichtweisen verschiedener Beteiligter in einem Konflikt beschreiben und aufeinander beziehen.', quelle: QUELLE },
  { id: 'de-ethik-s9-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 9, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können kulturelle, religiöse und weltanschauliche Unterschiede respektvoll darstellen, ohne sie vorschnell zu bewerten.', quelle: QUELLE },
  { id: 'de-ethik-s10-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'unterstufe', schulstufe: 10, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können globale Folgen lokaler Entscheidungen aus der Perspektive verschiedener Gruppen nachvollziehen.', quelle: QUELLE },
  { id: 'de-ethik-s11-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 11, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können in ethischen Debatten individuelle, gesellschaftliche und institutionelle Perspektiven systematisch unterscheiden.', quelle: QUELLE },
  { id: 'de-ethik-s12-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 12, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können Perspektiven marginalisierter oder zukünftig betroffener Gruppen in ihre ethische Analyse einbeziehen.', quelle: QUELLE },
  { id: 'de-ethik-s13-perspektiven-1', rahmenwerk: 'de-lehrplan', fach: 'ethik', stufe: 'oberstufe', schulstufe: 13, bereich: 'Perspektivenwechsel', code: '', text: 'Die Schülerinnen und Schüler können widersprüchliche Perspektiven in pluralistischen Gesellschaften vermitteln und die Bedingungen eines fairen Diskurses reflektieren.', quelle: QUELLE },
];

export const ethikDeStoffItems: StoffItem[] = [
  { id: 'de-ethik-wahrnehmen-un', rahmenwerk: 'de-lehrplan', titel: 'Ethische Situationen wahrnehmen', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Wahrnehmen & Beschreiben', deskriptorIds: ['de-ethik-s8-wahrnehmen-1', 'de-ethik-s9-wahrnehmen-1', 'de-ethik-s10-wahrnehmen-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
  { id: 'de-ethik-analysieren-un', rahmenwerk: 'de-lehrplan', titel: 'Dilemmata und Argumente', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Analysieren & Argumentieren', deskriptorIds: ['de-ethik-s8-analysieren-1', 'de-ethik-s9-analysieren-1', 'de-ethik-s10-analysieren-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'de-ethik-perspektiven-un', rahmenwerk: 'de-lehrplan', titel: 'Andere Perspektiven verstehen', fach: 'ethik', stufe: 'unterstufe', kategorie: 'Perspektivenwechsel', deskriptorIds: ['de-ethik-s8-perspektiven-1', 'de-ethik-s9-perspektiven-1', 'de-ethik-s10-perspektiven-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'de-ethik-urteilen-ob', rahmenwerk: 'de-lehrplan', titel: 'Ethische Urteilsbildung', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Urteilen & Reflektieren', deskriptorIds: ['de-ethik-s11-urteilen-1', 'de-ethik-s12-urteilen-1', 'de-ethik-s13-urteilen-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-ethik-analysieren-ob', rahmenwerk: 'de-lehrplan', titel: 'Theorien und angewandte Ethik', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Analysieren & Argumentieren', deskriptorIds: ['de-ethik-s11-analysieren-1', 'de-ethik-s12-analysieren-1', 'de-ethik-s13-analysieren-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'de-ethik-perspektiven-ob', rahmenwerk: 'de-lehrplan', titel: 'Pluralismus und Verantwortung', fach: 'ethik', stufe: 'oberstufe', kategorie: 'Perspektivenwechsel', deskriptorIds: ['de-ethik-s11-perspektiven-1', 'de-ethik-s12-perspektiven-1', 'de-ethik-s13-perspektiven-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
];
