import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

const QUELLE = 'KMK-Bildungsstandards Französisch (übertragen) + GeR/CEFR-Bezug — kuratierter Entwurf';

export const franzoesischDeDeskriptoren: Deskriptor[] = [
  { id: 'de-franzoesisch-s7-hoeren-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Hören', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können kurze Gespräche, Durchsagen und Hörtexte zu vertrauten Alltagsthemen global verstehen und zentrale Informationen entnehmen.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-hoeren-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Hören', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können authentische Hör- und audiovisuelle Texte zu gesellschaftlichen und kulturellen Themen verstehen und Sprecherintentionen erschließen.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Lesen', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können kurze persönliche und informierende Texte lesen, Kernaussagen erfassen und konkrete Einzelinformationen finden.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-lesen-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Lesen', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können längere Sachtexte und literarische Auszüge hinsichtlich Inhalt, Aufbau, Perspektive und ausgewählter sprachlicher Mittel analysieren.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-gespraech-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'An Gesprächen teilnehmen', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können in vertrauten Situationen Fragen stellen, antworten und mit einfachen Redemitteln Informationen austauschen.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-gespraech-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'An Gesprächen teilnehmen', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können sich an Diskussionen beteiligen, Positionen begründen, Nachfragen aufnehmen und auf Gegenargumente reagieren.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-sprechen-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Zusammenhängend sprechen', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können Personen, Orte, Abläufe und eigene Interessen mit einfachen zusammenhängenden Sätzen beschreiben.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-sprechen-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Zusammenhängend sprechen', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können Sachverhalte strukturiert präsentieren, Beispiele einbeziehen und einen eigenen Standpunkt differenziert vertreten.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Schreiben', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können kurze persönliche Mitteilungen, Beschreibungen und einfache Berichte verständlich verfassen.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-schreiben-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Schreiben', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können informative, argumentierende und kreative Texte adressatenbezogen, kohärent und sprachlich angemessen schreiben.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-mittlung-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Sprachmittlung', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können einfache Informationen aus kurzen französischen oder deutschen Texten sinngemäß für andere wiedergeben.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-mittlung-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Sprachmittlung', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können wesentliche Inhalte komplexerer Texte situations- und adressatengerecht zwischen Deutsch und Französisch vermitteln.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Grammatik', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können grundlegende Satzmuster, Frageformen sowie Präsens und passé composé in vertrauten Zusammenhängen anwenden.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-grammatik-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Grammatik', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können komplexere Satzgefüge, Zeiten und Modi sicher einsetzen und ihre sprachlichen Entscheidungen reflektieren.', quelle: QUELLE },
  { id: 'de-franzoesisch-s7-wortschatz-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, bereich: 'Wortschatz', code: 'A1/A2', text: 'Die Schülerinnen und Schüler können einen Grundwortschatz zu Schule, Familie, Freizeit, Reisen und Alltag aktiv verwenden.', quelle: QUELLE },
  { id: 'de-franzoesisch-s12-wortschatz-1', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wortschatz', code: 'B1/B2', text: 'Die Schülerinnen und Schüler können thematischen, idiomatischen und registergerechten Wortschatz in anspruchsvolleren Kommunikationssituationen nutzen.', quelle: QUELLE },
];

export const franzoesischDeStoffItems: StoffItem[] = [
  { id: 'de-fra-hoeren-un', rahmenwerk: 'de-lehrplan', titel: 'Hörverstehen im Alltag', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Hören', deskriptorIds: ['de-franzoesisch-s7-hoeren-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-fra-lesen-un', rahmenwerk: 'de-lehrplan', titel: 'Kurze französische Texte lesen', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Lesen', deskriptorIds: ['de-franzoesisch-s7-lesen-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-fra-sprechen-un', rahmenwerk: 'de-lehrplan', titel: 'Sprechen über vertraute Themen', fach: 'franzoesisch', stufe: 'unterstufe', kategorie: 'Zusammenhängend sprechen', deskriptorIds: ['de-franzoesisch-s7-sprechen-1'], defaultAufgabentypen: ['roleplay', 'offeneSchreibaufgabe'] },
  { id: 'de-fra-schreiben-ob', rahmenwerk: 'de-lehrplan', titel: 'Argumentieren und informieren', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Schreiben', deskriptorIds: ['de-franzoesisch-s12-schreiben-1'], defaultAufgabentypen: ['offeneSchreibaufgabe'] },
  { id: 'de-fra-mittlung-ob', rahmenwerk: 'de-lehrplan', titel: 'Sprachmittlung zwischen Deutsch und Französisch', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Sprachmittlung', deskriptorIds: ['de-franzoesisch-s12-mittlung-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-fra-grammatik-ob', rahmenwerk: 'de-lehrplan', titel: 'Grammatik und sprachliche Genauigkeit', fach: 'franzoesisch', stufe: 'oberstufe', kategorie: 'Grammatik', deskriptorIds: ['de-franzoesisch-s12-grammatik-1'], defaultAufgabentypen: ['fehlerkorrektur', 'multipleChoice'] },
];
