import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Geographie — kuratierter, länderübergreifender Kern für deutsche Schulen.

const QUELLE = 'EPA Geographie (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const geographieDeDeskriptoren: Deskriptor[] = [
  { id: 'de-geographie-s6-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Karten, Landschaftsbilder und einfache thematische Darstellungen lesen und räumlich zuordnen.', quelle: QUELLE },
  { id: 'de-geographie-s8-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können natur- und humangeographische Räume anhand ausgewählter Merkmale beschreiben und Maßstabsebenen unterscheiden.', quelle: QUELLE },
  { id: 'de-geographie-s10-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können globale Verflechtungen und regionale Unterschiede mithilfe von Karten, Statistiken und Raumbeispielen erklären.', quelle: QUELLE },
  { id: 'de-geographie-s11-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Räume als Ergebnis des Zusammenwirkens natürlicher, gesellschaftlicher und wirtschaftlicher Prozesse analysieren.', quelle: QUELLE },
  { id: 'de-geographie-s12-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können regionale Entwicklungsunterschiede auf mehreren Maßstabsebenen einordnen und die Aussagekraft räumlicher Modelle beurteilen.', quelle: QUELLE },
  { id: 'de-geographie-s13-wahrnehmung-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Wahrnehmungs- & Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe Raumkonflikte kartographisch und argumentativ darstellen und unterschiedliche Raumwahrnehmungen reflektieren.', quelle: QUELLE },
  { id: 'de-geographie-s6-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache Kartenlegenden, Maßstäbe und Diagramme nutzen, um geographische Informationen zu entnehmen.', quelle: QUELLE },
  { id: 'de-geographie-s8-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Tabellen, Klimadiagramme und thematische Karten auswerten und Ergebnisse in geeigneten Formen darstellen.', quelle: QUELLE },
  { id: 'de-geographie-s10-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Statistiken, Satellitenbilder und digitale Karten kritisch auswerten und Quellen sowie Darstellungsinteressen benennen.', quelle: QUELLE },
  { id: 'de-geographie-s11-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können geographische Daten aus unterschiedlichen Quellen verknüpfen, aufbereiten und mit angemessenen Fachmethoden interpretieren.', quelle: QUELLE },
  { id: 'de-geographie-s12-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Modelle, Indikatoren und statistische Verfahren hinsichtlich ihrer Voraussetzungen und Grenzen reflektieren.', quelle: QUELLE },
  { id: 'de-geographie-s13-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können eine geographische Untersuchung von der Fragestellung über die Datenerhebung bis zur begründeten Auswertung planen.', quelle: QUELLE },
  { id: 'de-geographie-s6-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Zusammenhänge zwischen Klima, Vegetation, Nutzung und Lebensbedingungen an überschaubaren Raumbeispielen erklären.', quelle: QUELLE },
  { id: 'de-geographie-s8-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Ursachen und Folgen von Stadtentwicklung, Migration und Nutzungskonflikten aus mehreren Perspektiven verknüpfen.', quelle: QUELLE },
  { id: 'de-geographie-s10-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Wechselwirkungen von Klimawandel, Ressourcenverbrauch, Globalisierung und regionaler Entwicklung an Beispielen beurteilen.', quelle: QUELLE },
  { id: 'de-geographie-s11-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe Mensch-Umwelt-Systeme analysieren und Zielkonflikte zwischen ökologischen, sozialen und ökonomischen Interessen herausarbeiten.', quelle: QUELLE },
  { id: 'de-geographie-s12-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können nachhaltige Entwicklungsstrategien anhand von Kriterien vergleichen und ihre räumlichen Nebenfolgen einschätzen.', quelle: QUELLE },
  { id: 'de-geographie-s13-synthese-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Synthesekompetenz', code: '', text: 'Die Schülerinnen und Schüler können geographische Systeme modellhaft erklären, Unsicherheiten offenlegen und daraus begründete Handlungsempfehlungen ableiten.', quelle: QUELLE },
  { id: 'de-geographie-s6-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können grundlegende Formen von Landwirtschaft, Arbeitsteilung und Versorgung in unterschiedlichen Räumen beschreiben.', quelle: QUELLE },
  { id: 'de-geographie-s8-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können Standortfaktoren und Produktionsketten an regionalen und internationalen Beispielen erklären.', quelle: QUELLE },
  { id: 'de-geographie-s10-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können Auswirkungen globaler Wertschöpfungsketten auf Arbeit, Umwelt und regionale Entwicklung analysieren.', quelle: QUELLE },
  { id: 'de-geographie-s11-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können wirtschaftliche Disparitäten mit ausgewählten Indikatoren untersuchen und strukturelle Ursachen von Entwicklungschancen diskutieren.', quelle: QUELLE },
  { id: 'de-geographie-s12-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können internationale Handels-, Finanz- und Migrationsbeziehungen in ihrer räumlichen Wirkung bewerten.', quelle: QUELLE },
  { id: 'de-geographie-s13-wirtschaft-1', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Wirtschaftliche Bildung', code: '', text: 'Die Schülerinnen und Schüler können wirtschaftspolitische und raumplanerische Maßnahmen unter Nachhaltigkeits-, Verteilungs- und Resilienzgesichtspunkten beurteilen.', quelle: QUELLE },
];

export const geographieDeStoffItems: StoffItem[] = [
  { id: 'de-geographie-wahrnehmung-un', rahmenwerk: 'de-lehrplan', titel: 'Räume lesen und orientieren', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Wahrnehmungs- & Orientierungskompetenz', deskriptorIds: ['de-geographie-s6-wahrnehmung-1', 'de-geographie-s8-wahrnehmung-1', 'de-geographie-s10-wahrnehmung-1'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'de-geographie-methoden-un', rahmenwerk: 'de-lehrplan', titel: 'Karten, Daten und Diagramme', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Methodenkompetenz', deskriptorIds: ['de-geographie-s6-methoden-1', 'de-geographie-s8-methoden-1', 'de-geographie-s10-methoden-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-geographie-synthese-un', rahmenwerk: 'de-lehrplan', titel: 'Mensch-Umwelt-Zusammenhänge', fach: 'geographie', stufe: 'unterstufe', kategorie: 'Synthesekompetenz', deskriptorIds: ['de-geographie-s6-synthese-1', 'de-geographie-s8-synthese-1', 'de-geographie-s10-synthese-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-geographie-wirtschaft-ob', rahmenwerk: 'de-lehrplan', titel: 'Wirtschaftsräume und globale Verflechtungen', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Wirtschaftliche Bildung', deskriptorIds: ['de-geographie-s11-wirtschaft-1', 'de-geographie-s12-wirtschaft-1', 'de-geographie-s13-wirtschaft-1'], defaultAufgabentypen: ['multipleChoice', 'offeneSchreibaufgabe'] },
  { id: 'de-geographie-synthese-ob', rahmenwerk: 'de-lehrplan', titel: 'Klimawandel und nachhaltige Entwicklung', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Synthesekompetenz', deskriptorIds: ['de-geographie-s11-synthese-1', 'de-geographie-s12-synthese-1', 'de-geographie-s13-synthese-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-geographie-methoden-ob', rahmenwerk: 'de-lehrplan', titel: 'Geographisch forschen', fach: 'geographie', stufe: 'oberstufe', kategorie: 'Methodenkompetenz', deskriptorIds: ['de-geographie-s11-methoden-1', 'de-geographie-s12-methoden-1', 'de-geographie-s13-methoden-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
];
