import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Geschichte — kuratierter, länderübergreifender Kern für deutsche Schulen.

const QUELLE = 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const geschichteDeDeskriptoren: Deskriptor[] = [
  { id: 'de-geschichte-s6-frage-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können aus Darstellungen und Quellen einfache Fragen zu Lebensbedingungen, Herrschaft und Wandel in früheren Zeiten entwickeln.', quelle: QUELLE },
  { id: 'de-geschichte-s8-frage-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Fragen zu Reformation, Revolution und gesellschaftlichen Veränderungen formulieren und nach Zeit, Raum und Perspektive präzisieren.', quelle: QUELLE },
  { id: 'de-geschichte-s10-frage-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können untersuchbare Fragen zur deutschen und europäischen Geschichte des 20. Jahrhunderts entwickeln und begründen.', quelle: QUELLE },
  { id: 'de-geschichte-s12-frage-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 12, bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können aus Forschungsstand, Quellenlage und Gegenwartsbezug eigenständige historische Untersuchungsfragen ableiten.', quelle: QUELLE },
  { id: 'de-geschichte-s13-frage-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, bereich: 'Historische Fragekompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Kontroversen erkennen, ihre Fragestellung daran ausrichten und die Reichweite möglicher Antworten kritisch einschätzen.', quelle: QUELLE },
  { id: 'de-geschichte-s6-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einfache schriftliche, bildliche und gegenständliche Quellen nach Urheber, Inhalt und erkennbarem Zweck befragen.', quelle: QUELLE },
  { id: 'de-geschichte-s8-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Quellen unterschiedlicher Gattung vergleichen und zwischen Quelle, Darstellung und eigener Deutung unterscheiden.', quelle: QUELLE },
  { id: 'de-geschichte-s10-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können politische Reden, Fotografien und Zeitzeugenberichte quellenkritisch analysieren und Perspektiven von Betroffenen berücksichtigen.', quelle: QUELLE },
  { id: 'de-geschichte-s12-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 12, bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Quellen im historischen Kontext prüfen, Aussagen belegen und konkurrierende Deutungen methodisch kontrolliert vergleichen.', quelle: QUELLE },
  { id: 'de-geschichte-s13-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, bereich: 'Historische Methodenkompetenz', code: '', text: 'Die Schülerinnen und Schüler können historische Narrative und geschichtskulturelle Darstellungen dekonstruieren sowie Auswahl, Perspektive und Interessen transparent machen.', quelle: QUELLE },
  { id: 'de-geschichte-s6-orientierung-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können wichtige Ereignisse der Antike und des Mittelalters in Zeitleisten einordnen und Veränderungen über längere Zeiträume beschreiben.', quelle: QUELLE },
  { id: 'de-geschichte-s8-orientierung-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Aufklärung, Französische Revolution und Industrialisierung als miteinander verbundene Umbrüche in Europa einordnen.', quelle: QUELLE },
  { id: 'de-geschichte-s10-orientierung-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Nationalsozialismus, Holocaust, Zweiten Weltkrieg und die deutsche Teilung in europäische und globale Zusammenhänge einordnen.', quelle: QUELLE },
  { id: 'de-geschichte-s12-orientierung-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 12, bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Entwicklung von Demokratie, Menschenrechten und europäischer Integration als historische Prozesse mit Brüchen und Konflikten erklären.', quelle: QUELLE },
  { id: 'de-geschichte-s13-orientierung-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, bereich: 'Historische Orientierungskompetenz', code: '', text: 'Die Schülerinnen und Schüler können gegenwärtige Debatten historisch kontextualisieren, ohne historische Analogien vorschnell gleichzusetzen.', quelle: QUELLE },
  { id: 'de-geschichte-s6-sach-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Merkmale früher Hochkulturen, der griechischen Polis und des Römischen Reiches erklären.', quelle: QUELLE },
  { id: 'de-geschichte-s8-sach-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Reformation, Konfessionalisierung, Absolutismus und Aufklärung als historische Konflikt- und Transformationsprozesse darstellen.', quelle: QUELLE },
  { id: 'de-geschichte-s10-sach-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Ursachen und Folgen von Erstem Weltkrieg, Weimarer Republik, NS-Herrschaft und Holocaust fachlich präzise erläutern.', quelle: QUELLE },
  { id: 'de-geschichte-s12-sach-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 12, bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Kalten Krieg, deutsche Teilung, Wiedervereinigung und europäische Integration in ihren politischen und gesellschaftlichen Wechselwirkungen analysieren.', quelle: QUELLE },
  { id: 'de-geschichte-s13-sach-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, bereich: 'Historische Sachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können langfristige Entwicklungslinien wie Staatlichkeit, Migration, Globalisierung und Erinnerungskultur vergleichend untersuchen.', quelle: QUELLE },
  { id: 'de-geschichte-s6-politisch-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Grundideen von Herrschaft, Recht und Beteiligung in antiken Gemeinwesen beschreiben und mit heutigen Vorstellungen vergleichen.', quelle: QUELLE },
  { id: 'de-geschichte-s8-politisch-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können Forderungen nach Freiheit, Gleichheit und politischer Mitbestimmung in historischen Revolutionen beurteilen.', quelle: QUELLE },
  { id: 'de-geschichte-s10-politisch-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung von Menschenrechten, Rechtsstaat und demokratischer Erinnerungskultur aus der deutschen Geschichte heraus begründen.', quelle: QUELLE },
  { id: 'de-geschichte-s13-politisch-1', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, bereich: 'Politische Bildung', code: '', text: 'Die Schülerinnen und Schüler können historische Verantwortung, politische Urteilskraft und Handlungsmöglichkeiten in aktuellen demokratischen Kontroversen reflektiert verbinden.', quelle: QUELLE },
];

export const geschichteDeStoffItems: StoffItem[] = [
  { id: 'de-ges-frage-un', rahmenwerk: 'de-lehrplan', titel: 'Historische Fragen entwickeln', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Fragekompetenz', deskriptorIds: ['de-geschichte-s6-frage-1', 'de-geschichte-s8-frage-1', 'de-geschichte-s10-frage-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-ges-methoden-un', rahmenwerk: 'de-lehrplan', titel: 'Quellen untersuchen', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Methodenkompetenz', deskriptorIds: ['de-geschichte-s6-methoden-1', 'de-geschichte-s8-methoden-1', 'de-geschichte-s10-methoden-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-ges-sach-un', rahmenwerk: 'de-lehrplan', titel: 'Epochen und Umbrüche verstehen', fach: 'geschichte', stufe: 'unterstufe', kategorie: 'Historische Sachkompetenz', deskriptorIds: ['de-geschichte-s6-sach-1', 'de-geschichte-s8-sach-1', 'de-geschichte-s10-sach-1'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'de-ges-orientierung-ob', rahmenwerk: 'de-lehrplan', titel: 'Zeitgeschichte einordnen', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Orientierungskompetenz', deskriptorIds: ['de-geschichte-s10-orientierung-1', 'de-geschichte-s12-orientierung-1', 'de-geschichte-s13-orientierung-1'], defaultAufgabentypen: ['kategorisierung', 'multipleChoice'] },
  { id: 'de-ges-sach-ob', rahmenwerk: 'de-lehrplan', titel: 'Deutschland, Europa und die Welt', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Historische Sachkompetenz', deskriptorIds: ['de-geschichte-s12-sach-1', 'de-geschichte-s13-sach-1'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'de-ges-politik-ob', rahmenwerk: 'de-lehrplan', titel: 'Geschichte und politische Bildung', fach: 'geschichte', stufe: 'oberstufe', kategorie: 'Politische Bildung', deskriptorIds: ['de-geschichte-s10-politisch-1', 'de-geschichte-s13-politisch-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
