import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

const QUELLE = 'GI-Bildungsstandards Informatik + KMK-Empfehlungen — kuratierter Entwurf';

export const informatikkiDeDeskriptoren: Deskriptor[] = [
  { id: 'de-informatikki-s6-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 6, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können alltägliche Abläufe als geordnete Schrittfolgen beschreiben und Bedingungen sowie Wiederholungen erkennen.', quelle: QUELLE },
  { id: 'de-informatikki-s8-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 8, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können einfache Algorithmen in Ablaufplänen oder einer visuellen Programmiersprache darstellen und testen.', quelle: QUELLE },
  { id: 'de-informatikki-s10-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 10, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können Probleme in Teilprobleme zerlegen, Variablen und Kontrollstrukturen nutzen und Fehler systematisch suchen.', quelle: QUELLE },
  { id: 'de-informatikki-s11-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Lösungswege vergleichen und nach Verständlichkeit, Effizienz und Fehleranfälligkeit beurteilen.', quelle: QUELLE },
  { id: 'de-informatikki-s12-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können Datenstrukturen als Konzepte beschreiben und die Grenzen algorithmischer Verfahren an Beispielen erklären.', quelle: QUELLE },
  { id: 'de-informatikki-s13-algorithmen-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 13, bereich: 'Algorithmisches Denken', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Entscheidungen hinsichtlich Nachvollziehbarkeit, Skalierung und gesellschaftlicher Folgen bewerten.', quelle: QUELLE },
  { id: 'de-informatikki-s6-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 6, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Beispiele für digitale Systeme und KI-Anwendungen im Alltag benennen und ihre Zwecke beschreiben.', quelle: QUELLE },
  { id: 'de-informatikki-s8-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 8, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können zwischen regelbasierten und lernenden Systemen unterscheiden und Chancen sowie Risiken automatisierter Empfehlungen erläutern.', quelle: QUELLE },
  { id: 'de-informatikki-s10-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 10, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können erklären, dass KI-Systeme Muster aus Trainingsdaten ableiten und von Datenqualität sowie Modellannahmen abhängen.', quelle: QUELLE },
  { id: 'de-informatikki-s11-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Klassifikation, Generierung und Vorhersage als typische KI-Leistungen unterscheiden.', quelle: QUELLE },
  { id: 'de-informatikki-s12-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können Bias, Fehlklassifikation, Transparenz und menschliche Kontrolle in KI-Anwendungen analysieren.', quelle: QUELLE },
  { id: 'de-informatikki-s13-ki-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 13, bereich: 'KI-Grundlagen & Ethik', code: '', text: 'Die Schülerinnen und Schüler können begründete Positionen zu KI-Regulierung, Urheberrecht, Verantwortung und gesellschaftlicher Teilhabe entwickeln.', quelle: QUELLE },
  { id: 'de-informatikki-s6-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 6, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können personenbezogene Daten erkennen und grundlegende Regeln für sichere Passwörter und vorsichtige Weitergabe anwenden.', quelle: QUELLE },
  { id: 'de-informatikki-s8-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 8, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Phishing, Malware und Social Engineering als Sicherheitsrisiken unterscheiden und Schutzmaßnahmen begründen.', quelle: QUELLE },
  { id: 'de-informatikki-s10-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'unterstufe', schulstufe: 10, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Datenschutz-Einstellungen digitaler Dienste prüfen und ihre Wirkung auf Sichtbarkeit, Tracking und Kontrolle beschreiben.', quelle: QUELLE },
  { id: 'de-informatikki-s11-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 11, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Grundprinzipien von Verschlüsselung, Zugriffskontrolle und Datensicherung in alltagsnahen Szenarien erklären.', quelle: QUELLE },
  { id: 'de-informatikki-s12-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 12, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Datenschutz, IT-Sicherheit und digitale Grundrechte in Konfliktfällen systematisch gegeneinander abwägen.', quelle: QUELLE },
  { id: 'de-informatikki-s13-datenschutz-1', rahmenwerk: 'de-lehrplan', fach: 'informatikki', stufe: 'oberstufe', schulstufe: 13, bereich: 'Datenschutz & Cybersecurity', code: '', text: 'Die Schülerinnen und Schüler können Sicherheitsvorfälle, Datenlecks und Plattformrisiken anhand von Ursachen, Folgen und Präventionsmaßnahmen analysieren.', quelle: QUELLE },
];

export const informatikkiDeStoffItems: StoffItem[] = [
  { id: 'de-ik-algorithmen-un', rahmenwerk: 'de-lehrplan', titel: 'Abläufe und Algorithmen', fach: 'informatikki', stufe: 'unterstufe', kategorie: 'Algorithmisches Denken', deskriptorIds: ['de-informatikki-s6-algorithmen-1', 'de-informatikki-s8-algorithmen-1', 'de-informatikki-s10-algorithmen-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-ik-ki-un', rahmenwerk: 'de-lehrplan', titel: 'KI im Alltag verstehen', fach: 'informatikki', stufe: 'unterstufe', kategorie: 'KI-Grundlagen & Ethik', deskriptorIds: ['de-informatikki-s6-ki-1', 'de-informatikki-s8-ki-1', 'de-informatikki-s10-ki-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-ik-sicherheit-un', rahmenwerk: 'de-lehrplan', titel: 'Datenschutz und sichere Nutzung', fach: 'informatikki', stufe: 'unterstufe', kategorie: 'Datenschutz & Cybersecurity', deskriptorIds: ['de-informatikki-s6-datenschutz-1', 'de-informatikki-s8-datenschutz-1', 'de-informatikki-s10-datenschutz-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-ik-algorithmen-ob', rahmenwerk: 'de-lehrplan', titel: 'Algorithmen bewerten', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'Algorithmisches Denken', deskriptorIds: ['de-informatikki-s11-algorithmen-1', 'de-informatikki-s12-algorithmen-1', 'de-informatikki-s13-algorithmen-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-ik-ki-ob', rahmenwerk: 'de-lehrplan', titel: 'Generative KI und Verantwortung', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'KI-Grundlagen & Ethik', deskriptorIds: ['de-informatikki-s11-ki-1', 'de-informatikki-s12-ki-1', 'de-informatikki-s13-ki-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-ik-sicherheit-ob', rahmenwerk: 'de-lehrplan', titel: 'Cybersecurity und digitale Grundrechte', fach: 'informatikki', stufe: 'oberstufe', kategorie: 'Datenschutz & Cybersecurity', deskriptorIds: ['de-informatikki-s11-datenschutz-1', 'de-informatikki-s12-datenschutz-1', 'de-informatikki-s13-datenschutz-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
];
