import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Latein ist in Deutschland überwiegend ein Oberstufen- und Abiturfach.
const QUELLE = 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const lateinDeDeskriptoren: Deskriptor[] = [
  { id: 'de-latein-s11-sprach-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können komplexe lateinische Satzgefüge mit Partizipialkonstruktionen, AcI und Nebensätzen sicher analysieren und übersetzen.', quelle: QUELLE },
  { id: 'de-latein-s11-sprach-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Formen, syntaktische Funktionen und semantische Bezüge lateinischer Wörter im Kontext bestimmen.', quelle: QUELLE },
  { id: 'de-latein-s12-sprach-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können stilistische und rhetorische Besonderheiten bei Cicero, Caesar, Ovid oder Vergil erkennen und für die Übersetzung nutzen.', quelle: QUELLE },
  { id: 'de-latein-s12-sprach-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Übersetzungsvarianten auf Genauigkeit, sprachliche Angemessenheit und den Erhalt von Textwirkung prüfen.', quelle: QUELLE },
  { id: 'de-latein-s13-sprach-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können anspruchsvolle Originaltexte mit Wörterbuch und Kommentar selbstständig erschließen und begründet übersetzen.', quelle: QUELLE },
  { id: 'de-latein-s13-sprach-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Sprachkompetenz', code: '', text: 'Die Schülerinnen und Schüler können lateinische Sprachformen mit romanischen und deutschen Sprachentwicklungen in Beziehung setzen.', quelle: QUELLE },
  { id: 'de-latein-s11-text-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können den Inhalt und Aufbau eines lateinischen Textes mit geeigneten Textbelegen wiedergeben.', quelle: QUELLE },
  { id: 'de-latein-s11-text-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Übersetzungsentscheidungen an Syntax, Wortbedeutung und Textzusammenhang begründen.', quelle: QUELLE },
  { id: 'de-latein-s12-text-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können einen lateinischen Text hinsichtlich Argumentation, Erzählperspektive, Gattung und sprachlicher Gestaltung analysieren.', quelle: QUELLE },
  { id: 'de-latein-s12-text-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können antike Texte mit Übersetzungen, Kommentaren und modernen Bearbeitungen vergleichend auswerten.', quelle: QUELLE },
  { id: 'de-latein-s13-text-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können eine eigenständige textnahe Interpretation entwickeln und ihre Deutung im historischen Kontext absichern.', quelle: QUELLE },
  { id: 'de-latein-s13-text-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Textkompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Wirkung eines lateinischen Originals und einer deutschen Übersetzung kritisch vergleichen.', quelle: QUELLE },
  { id: 'de-latein-s11-kultur-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale Institutionen, Wertvorstellungen und Lebensformen der römischen Republik und Kaiserzeit erklären.', quelle: QUELLE },
  { id: 'de-latein-s11-kultur-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können griechische Einflüsse auf römische Literatur, Religion und politische Kultur beschreiben.', quelle: QUELLE },
  { id: 'de-latein-s12-kultur-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können antike philosophische und politische Positionen mit späteren europäischen Debatten vergleichen.', quelle: QUELLE },
  { id: 'de-latein-s12-kultur-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Rezeption lateinischer Motive in Literatur, Kunst und politischer Sprache nachvollziehen.', quelle: QUELLE },
  { id: 'de-latein-s13-kultur-1', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können Kontinuitäten und Brüche zwischen antiken Konzepten und ihrer modernen Verwendung kritisch beurteilen.', quelle: QUELLE },
  { id: 'de-latein-s13-kultur-2', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 13, bereich: 'Kulturkompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Bedeutung lateinischer Texte für europäische Bildungstraditionen und kulturelle Identität reflektieren.', quelle: QUELLE },
];

export const lateinDeStoffItems: StoffItem[] = [
  { id: 'de-lat-sprachkompetenz-ob', rahmenwerk: 'de-lehrplan', titel: 'Syntax, Formenlehre und Übersetzen', fach: 'latein', stufe: 'oberstufe', kategorie: 'Sprachkompetenz', deskriptorIds: ['de-latein-s11-sprach-1', 'de-latein-s11-sprach-2', 'de-latein-s12-sprach-1', 'de-latein-s12-sprach-2', 'de-latein-s13-sprach-1', 'de-latein-s13-sprach-2'], defaultAufgabentypen: ['lueckentext', 'multipleChoice'] },
  { id: 'de-lat-textkompetenz-ob', rahmenwerk: 'de-lehrplan', titel: 'Lateinische Texte erschließen', fach: 'latein', stufe: 'oberstufe', kategorie: 'Textkompetenz', deskriptorIds: ['de-latein-s11-text-1', 'de-latein-s11-text-2', 'de-latein-s12-text-1', 'de-latein-s12-text-2', 'de-latein-s13-text-1', 'de-latein-s13-text-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-lat-kultur-ob', rahmenwerk: 'de-lehrplan', titel: 'Römische Kultur und Gesellschaft', fach: 'latein', stufe: 'oberstufe', kategorie: 'Kulturkompetenz', deskriptorIds: ['de-latein-s11-kultur-1', 'de-latein-s11-kultur-2', 'de-latein-s12-kultur-1', 'de-latein-s12-kultur-2', 'de-latein-s13-kultur-1', 'de-latein-s13-kultur-2'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'de-lat-rezeption-ob', rahmenwerk: 'de-lehrplan', titel: 'Antike Rezeption und Gegenwart', fach: 'latein', stufe: 'oberstufe', kategorie: 'Kulturkompetenz', deskriptorIds: ['de-latein-s12-kultur-2', 'de-latein-s13-kultur-1', 'de-latein-s13-kultur-2'], defaultAufgabentypen: ['multipleChoice', 'kategorisierung'] },
  { id: 'de-lat-interpretation-ob', rahmenwerk: 'de-lehrplan', titel: 'Interpretation und Übersetzungsvergleich', fach: 'latein', stufe: 'oberstufe', kategorie: 'Textkompetenz', deskriptorIds: ['de-latein-s12-text-1', 'de-latein-s12-text-2', 'de-latein-s13-text-1', 'de-latein-s13-text-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
];
