import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

const QUELLE = 'KMK-Strategie „Bildung in der digitalen Welt“ + Länder-Curricula — kuratierter Entwurf';

export const mediendemokratieDeDeskriptoren: Deskriptor[] = [
  { id: 'de-mediendemokratie-s6-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können zwischen Nachricht, Meinung, Werbung und Unterhaltung unterscheiden und einfache Quellenangaben prüfen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s8-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Bilder, Überschriften und Beiträge auf Perspektive, Auslassungen und mögliche Beeinflussung untersuchen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s10-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Quellen zu einem kontroversen Thema vergleichen, Belege bewerten und Desinformation begründet erkennen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s11-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können Medienbeiträge multiperspektivisch analysieren und Interessen, Zielgruppen sowie journalistische Darstellungsentscheidungen herausarbeiten.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s12-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können algorithmische Auswahl, Filterblasen, Plattformlogiken und synthetische Medien als Faktoren öffentlicher Wahrnehmung beurteilen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s13-medien-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Medienkompetenz & Quellenkritik', code: '', text: 'Die Schülerinnen und Schüler können komplexe Medienereignisse anhand von Quellenlage, professionellen Standards und gesellschaftlicher Wirkung kritisch bewerten.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s6-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Grundzüge demokratischer Entscheidungen und die Bedeutung verlässlicher Informationen für Beteiligung erklären.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s8-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Aufgaben von Parlament, Regierung, Opposition und Medien in einer Demokratie beschreiben.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s10-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Chancen und Risiken sozialer Medien für politische Teilhabe, Meinungsfreiheit und Schutz der Persönlichkeit abwägen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s11-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können den Einfluss medialer Öffentlichkeit auf politische Agenda, Wahlen und Protestbewegungen analysieren.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s12-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können Medienfreiheit, Plattformverantwortung, Regulierung und Grundrechte in demokratischen Konfliktlagen gegeneinander abwägen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s13-demokratie-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Politische Bildung & Demokratieverständnis', code: '', text: 'Die Schülerinnen und Schüler können die Wirkung digitaler Öffentlichkeit auf Vertrauen, politische Institutionen und gesellschaftlichen Zusammenhalt reflektiert beurteilen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s6-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 6, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können eigene Medienbeiträge adressatenbezogen gestalten und zwischen sachlicher Information und persönlicher Meinung unterscheiden.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s8-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 8, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können kontroverse Positionen fair zusammenfassen, begründet kommentieren und Regeln respektvoller Online-Kommunikation anwenden.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s10-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'unterstufe', schulstufe: 10, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können Kommentar, Leserbrief, Kurzvideo und Social-Media-Post als unterschiedliche Formen öffentlicher Meinungsäußerung vergleichen.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s11-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können argumentativ auf polarisierende Beiträge reagieren und dabei Belege, Gegenargumente und demokratische Gesprächsregeln verbinden.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s12-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können begründete öffentliche Stellungnahmen zu medienpolitischen Fragen verfassen und kommunikative Wirkungen reflektieren.', quelle: QUELLE },
  { id: 'de-mediendemokratie-s13-kommunikation-1', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Kommunikation & Meinungsbildung', code: '', text: 'Die Schülerinnen und Schüler können eigene Verantwortung als Produzentinnen und Produzenten digitaler Öffentlichkeit analysieren und verantwortbare Kommunikationsstrategien entwickeln.', quelle: QUELLE },
];

export const mediendemokratieDeStoffItems: StoffItem[] = [
  { id: 'de-md-medien-un', rahmenwerk: 'de-lehrplan', titel: 'Medienbeiträge und Quellen prüfen', fach: 'mediendemokratie', stufe: 'unterstufe', kategorie: 'Medienkompetenz & Quellenkritik', deskriptorIds: ['de-mediendemokratie-s6-medien-1', 'de-mediendemokratie-s8-medien-1', 'de-mediendemokratie-s10-medien-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-md-demokratie-un', rahmenwerk: 'de-lehrplan', titel: 'Demokratie und digitale Beteiligung', fach: 'mediendemokratie', stufe: 'unterstufe', kategorie: 'Politische Bildung & Demokratieverständnis', deskriptorIds: ['de-mediendemokratie-s6-demokratie-1', 'de-mediendemokratie-s8-demokratie-1', 'de-mediendemokratie-s10-demokratie-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-md-kommunikation-un', rahmenwerk: 'de-lehrplan', fach: 'mediendemokratie', titel: 'Sich online sachlich äußern', stufe: 'unterstufe', kategorie: 'Kommunikation & Meinungsbildung', deskriptorIds: ['de-mediendemokratie-s6-kommunikation-1', 'de-mediendemokratie-s8-kommunikation-1', 'de-mediendemokratie-s10-kommunikation-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'de-md-medien-ob', rahmenwerk: 'de-lehrplan', titel: 'Desinformation und Plattformlogiken', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Medienkompetenz & Quellenkritik', deskriptorIds: ['de-mediendemokratie-s11-medien-1', 'de-mediendemokratie-s12-medien-1', 'de-mediendemokratie-s13-medien-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-md-demokratie-ob', rahmenwerk: 'de-lehrplan', titel: 'Medien und demokratische Öffentlichkeit', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Politische Bildung & Demokratieverständnis', deskriptorIds: ['de-mediendemokratie-s11-demokratie-1', 'de-mediendemokratie-s12-demokratie-1', 'de-mediendemokratie-s13-demokratie-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-md-kommunikation-ob', rahmenwerk: 'de-lehrplan', titel: 'Öffentliche Meinungsbildung gestalten', fach: 'mediendemokratie', stufe: 'oberstufe', kategorie: 'Kommunikation & Meinungsbildung', deskriptorIds: ['de-mediendemokratie-s11-kommunikation-1', 'de-mediendemokratie-s12-kommunikation-1', 'de-mediendemokratie-s13-kommunikation-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
];
