import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Philosophie wird in Deutschland überwiegend in der gymnasialen Oberstufe belegt.
const QUELLE = 'EPA Philosophie (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const philosophieDeDeskriptoren: Deskriptor[] = [
  { id: 'de-philosophie-s11-begriff-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Grundbegriffe wie Wahrheit, Freiheit, Person, Gerechtigkeit und Verantwortung klären und voneinander abgrenzen.', quelle: QUELLE },
  { id: 'de-philosophie-s11-begriff-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können erkenntnistheoretische und anthropologische Grundpositionen in ihren Leitfragen darstellen.', quelle: QUELLE },
  { id: 'de-philosophie-s12-begriff-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können zentrale Argumente ausgewählter philosophischer Positionen textnah rekonstruieren und in ihren historischen Kontext einordnen.', quelle: QUELLE },
  { id: 'de-philosophie-s12-begriff-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können Unterschiede zwischen deontologischen, konsequentialistischen und tugendethischen Theorien präzise beschreiben.', quelle: QUELLE },
  { id: 'de-philosophie-s13-begriff-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Theorien vergleichend analysieren und Voraussetzungen, Begriffsverwendungen sowie Konsequenzen offenlegen.', quelle: QUELLE },
  { id: 'de-philosophie-s13-begriff-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Begriffs- & Theoriekompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Reichweite und Grenzen einer philosophischen Position im Hinblick auf eine konkrete Fragestellung begründet einschätzen.', quelle: QUELLE },
  { id: 'de-philosophie-s11-argument-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Thesen, Gründe, Beispiele und Einwände in philosophischen Texten unterscheiden.', quelle: QUELLE },
  { id: 'de-philosophie-s11-argument-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können die Gültigkeit und Schlüssigkeit einfacher Argumente prüfen und argumentative Lücken benennen.', quelle: QUELLE },
  { id: 'de-philosophie-s12-argument-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können eine philosophische Erörterung strukturiert entwickeln, Gegenpositionen fair darstellen und ein eigenes Urteil begründen.', quelle: QUELLE },
  { id: 'de-philosophie-s13-argument-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können konkurrierende Argumentationen anhand expliziter Kriterien vergleichen und ihre eigene Position selbstkritisch weiterentwickeln.', quelle: QUELLE },
  { id: 'de-philosophie-s13-argument-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Argumentations- & Reflexionskompetenz', code: '', text: 'Die Schülerinnen und Schüler können philosophische Probleme in ihrer Offenheit aushalten und begründete Urteile auch unter verbleibender Unsicherheit formulieren.', quelle: QUELLE },
  { id: 'de-philosophie-s11-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können philosophische Begriffe auf Fragen aus Alltag, Schule und digitaler Lebenswelt anwenden.', quelle: QUELLE },
  { id: 'de-philosophie-s12-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können ethische und politische Theorien auf Konflikte um Technik, Klima, Gerechtigkeit und Freiheit beziehen.', quelle: QUELLE },
  { id: 'de-philosophie-s12-transfer-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche Begriffe von Fortschritt und Menschenwürde auf aktuelle Fragen wissenschaftlicher und technischer Entwicklung anwenden.', quelle: QUELLE },
  { id: 'de-philosophie-s13-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können aus einer philosophischen Analyse begründete Kriterien für gesellschaftliche Entscheidungen und verantwortliches Handeln ableiten.', quelle: QUELLE },
  { id: 'de-philosophie-s13-transfer-2', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können die Übertragbarkeit philosophischer Positionen auf neue Fälle prüfen und unzulässige Analogien zurückweisen.', quelle: QUELLE },
];

export const philosophieDeStoffItems: StoffItem[] = [
  { id: 'de-phil-begriff-ob', rahmenwerk: 'de-lehrplan', titel: 'Begriffe und philosophische Theorien', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Begriffs- & Theoriekompetenz', deskriptorIds: ['de-philosophie-s11-begriff-1', 'de-philosophie-s11-begriff-2', 'de-philosophie-s12-begriff-1', 'de-philosophie-s12-begriff-2', 'de-philosophie-s13-begriff-1', 'de-philosophie-s13-begriff-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-phil-argument-ob', rahmenwerk: 'de-lehrplan', titel: 'Argumentieren und philosophisch urteilen', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Argumentations- & Reflexionskompetenz', deskriptorIds: ['de-philosophie-s11-argument-1', 'de-philosophie-s11-argument-2', 'de-philosophie-s12-argument-1', 'de-philosophie-s13-argument-1', 'de-philosophie-s13-argument-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-phil-transfer-ob', rahmenwerk: 'de-lehrplan', titel: 'Philosophie auf Gegenwartsfragen anwenden', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['de-philosophie-s11-transfer-1', 'de-philosophie-s12-transfer-1', 'de-philosophie-s12-transfer-2', 'de-philosophie-s13-transfer-1', 'de-philosophie-s13-transfer-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-phil-ethik-ob', rahmenwerk: 'de-lehrplan', titel: 'Freiheit, Gerechtigkeit und Verantwortung', fach: 'philosophie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['de-philosophie-s12-transfer-1', 'de-philosophie-s12-transfer-2', 'de-philosophie-s13-transfer-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
