import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

// Psychologie ist in Deutschland überwiegend ein Fach der gymnasialen Oberstufe.
const QUELLE = 'EPA Psychologie (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const psychologieDeDeskriptoren: Deskriptor[] = [
  { id: 'de-psychologie-s11-fachwissen-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können Wahrnehmung, Lernen, Gedächtnis und Motivation als grundlegende psychologische Gegenstandsbereiche erläutern.', quelle: QUELLE },
  { id: 'de-psychologie-s12-fachwissen-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können zentrale Ansätze der Entwicklungs-, Sozial- und Persönlichkeitspsychologie unterscheiden und auf Beispiele beziehen.', quelle: QUELLE },
  { id: 'de-psychologie-s13-fachwissen-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können psychologische Erklärungen in ihrer theoretischen Reichweite, empirischen Grundlage und gesellschaftlichen Bedeutung vergleichen.', quelle: QUELLE },
  { id: 'de-psychologie-s13-fachwissen-2', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Fachwissen', code: '', text: 'Die Schülerinnen und Schüler können psychologische Fachbegriffe präzise verwenden und biologische, individuelle sowie soziale Einflussfaktoren auf Verhalten verknüpfen.', quelle: QUELLE },
  { id: 'de-psychologie-s11-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Fragestellungen in überprüfbare Hypothesen und geeignete Untersuchungsfragen überführen.', quelle: QUELLE },
  { id: 'de-psychologie-s12-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können Experimente, Befragungen und Beobachtungen hinsichtlich Fragestellung, Variablen und Aussagekraft unterscheiden.', quelle: QUELLE },
  { id: 'de-psychologie-s13-methoden-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Studien kritisch auf Stichprobe, Operationalisierung, Auswertung und mögliche Verzerrungen prüfen.', quelle: QUELLE },
  { id: 'de-psychologie-s13-methoden-2', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Methoden- & Erkenntniskompetenz', code: '', text: 'Die Schülerinnen und Schüler können aus Daten begrenzte Schlussfolgerungen ziehen und Korrelation, Kausalität sowie Replizierbarkeit auseinanderhalten.', quelle: QUELLE },
  { id: 'de-psychologie-s11-reflexion-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können psychologische Aussagen aus Medien und Alltag auf Fachbegriffe, Plausibilität und Belege prüfen.', quelle: QUELLE },
  { id: 'de-psychologie-s12-reflexion-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche psychologische Erklärungen vergleichen und ihre jeweiligen Grenzen begründet benennen.', quelle: QUELLE },
  { id: 'de-psychologie-s13-reflexion-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können ethische Grenzen psychologischer Forschung und Anwendung unter Berücksichtigung von Autonomie, Schutz und Fairness beurteilen.', quelle: QUELLE },
  { id: 'de-psychologie-s13-reflexion-2', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Reflexions- & Urteilskompetenz', code: '', text: 'Die Schülerinnen und Schüler können den Einfluss gesellschaftlicher Normen und eigener Vorannahmen auf psychologische Urteile reflektieren.', quelle: QUELLE },
  { id: 'de-psychologie-s11-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Konzepte auf Lernen, Kommunikation und Konflikte im schulischen Alltag anwenden.', quelle: QUELLE },
  { id: 'de-psychologie-s12-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können psychologische Modelle nutzen, um Entwicklungsaufgaben, Gruppenprozesse und Medienwirkungen zu analysieren.', quelle: QUELLE },
  { id: 'de-psychologie-s13-transfer-1', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können aus psychologischen Befunden verantwortbare Handlungsmöglichkeiten für Beratung, Prävention oder Bildung ableiten.', quelle: QUELLE },
  { id: 'de-psychologie-s13-transfer-2', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, bereich: 'Anwendung & Transfer', code: '', text: 'Die Schülerinnen und Schüler können die Übertragbarkeit psychologischer Erkenntnisse auf neue Fälle prüfen und vorschnelle Alltagsdiagnosen vermeiden.', quelle: QUELLE },
];

export const psychologieDeStoffItems: StoffItem[] = [
  { id: 'de-psy-fachwissen-ob', rahmenwerk: 'de-lehrplan', titel: 'Grundlagen und Theorien', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Fachwissen', deskriptorIds: ['de-psychologie-s11-fachwissen-1', 'de-psychologie-s12-fachwissen-1', 'de-psychologie-s13-fachwissen-1', 'de-psychologie-s13-fachwissen-2'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-psy-methoden-ob', rahmenwerk: 'de-lehrplan', titel: 'Psychologisch forschen', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Methoden- & Erkenntniskompetenz', deskriptorIds: ['de-psychologie-s11-methoden-1', 'de-psychologie-s12-methoden-1', 'de-psychologie-s13-methoden-1', 'de-psychologie-s13-methoden-2'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-psy-reflexion-ob', rahmenwerk: 'de-lehrplan', titel: 'Psychologische Aussagen beurteilen', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Reflexions- & Urteilskompetenz', deskriptorIds: ['de-psychologie-s11-reflexion-1', 'de-psychologie-s12-reflexion-1', 'de-psychologie-s13-reflexion-1', 'de-psychologie-s13-reflexion-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
  { id: 'de-psy-transfer-ob', rahmenwerk: 'de-lehrplan', titel: 'Psychologie im Alltag anwenden', fach: 'psychologie', stufe: 'oberstufe', kategorie: 'Anwendung & Transfer', deskriptorIds: ['de-psychologie-s11-transfer-1', 'de-psychologie-s12-transfer-1', 'de-psychologie-s13-transfer-1', 'de-psychologie-s13-transfer-2'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'offeneVerstaendnisfrage'] },
];
