import type { StoffItem, Deskriptor } from '@lehrunterlagen/schema';

const QUELLE = 'EPA Religion (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf';

export const religionDeDeskriptoren: Deskriptor[] = [
  { id: 'de-religion-s7-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 7, bereich: 'Wahrnehmen & Verstehen', code: '', text: 'Die Schülerinnen und Schüler können religiöse Ausdrucksformen, Rituale und Feste in der eigenen und in anderen Traditionen beschreiben.', quelle: QUELLE },
  { id: 'de-religion-s9-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 9, bereich: 'Wahrnehmen & Verstehen', code: '', text: 'Die Schülerinnen und Schüler können religiöse und weltanschauliche Deutungen in persönlichen, gesellschaftlichen und medialen Konflikten erkennen.', quelle: QUELLE },
  { id: 'de-religion-s11-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 11, bereich: 'Wahrnehmen & Verstehen', code: '', text: 'Die Schülerinnen und Schüler können religiöse Sprache, Symbole und Traditionen in ihrem historischen und gegenwärtigen Kontext differenziert erschließen.', quelle: QUELLE },
  { id: 'de-religion-s13-wahrnehmen-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 13, bereich: 'Wahrnehmen & Verstehen', code: '', text: 'Die Schülerinnen und Schüler können religiöse, säkulare und interreligiöse Perspektiven auf globale Herausforderungen sachgerecht darstellen.', quelle: QUELLE },
  { id: 'de-religion-s7-deuten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 7, bereich: 'Deuten & Urteilen', code: '', text: 'Die Schülerinnen und Schüler können einfache biblische, religiöse und ethische Texte in ihren Kernaussagen erschließen.', quelle: QUELLE },
  { id: 'de-religion-s9-deuten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 9, bereich: 'Deuten & Urteilen', code: '', text: 'Die Schülerinnen und Schüler können unterschiedliche religiöse Deutungen zu Fragen von Freiheit, Gerechtigkeit und Verantwortung vergleichen.', quelle: QUELLE },
  { id: 'de-religion-s11-deuten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 11, bereich: 'Deuten & Urteilen', code: '', text: 'Die Schülerinnen und Schüler können theologische und religionswissenschaftliche Deutungen anhand von Texten, Begriffen und Argumenten nachvollziehen.', quelle: QUELLE },
  { id: 'de-religion-s13-deuten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 13, bereich: 'Deuten & Urteilen', code: '', text: 'Die Schülerinnen und Schüler können religiöse Deutungsangebote zu anthropologischen und gesellschaftlichen Fragen eigenständig prüfen und begründet beurteilen.', quelle: QUELLE },
  { id: 'de-religion-s7-reflektieren-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 7, bereich: 'Reflektieren & Kommunizieren', code: '', text: 'Die Schülerinnen und Schüler können eigene Fragen zu Sinn, Zugehörigkeit und Hoffnung formulieren und respektvoll mit anderen besprechen.', quelle: QUELLE },
  { id: 'de-religion-s9-reflektieren-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 9, bereich: 'Reflektieren & Kommunizieren', code: '', text: 'Die Schülerinnen und Schüler können eigene religiöse oder weltanschauliche Vorstellungen im Austausch mit anderen reflektieren, ohne Unterschiede abzuwerten.', quelle: QUELLE },
  { id: 'de-religion-s11-reflektieren-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 11, bereich: 'Reflektieren & Kommunizieren', code: '', text: 'Die Schülerinnen und Schüler können den eigenen Standpunkt zu religiösen und ethischen Fragen transparent begründen und auf Gegenpositionen eingehen.', quelle: QUELLE },
  { id: 'de-religion-s13-reflektieren-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 13, bereich: 'Reflektieren & Kommunizieren', code: '', text: 'Die Schülerinnen und Schüler können religiöse Pluralität, Zweifel und Gewissheit als Bestandteile reflektierter Urteilsbildung in einer offenen Gesellschaft diskutieren.', quelle: QUELLE },
  { id: 'de-religion-s7-gestalten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 7, bereich: 'Gestalten & Handeln', code: '', text: 'Die Schülerinnen und Schüler können Möglichkeiten solidarischen Handelns im schulischen und lokalen Umfeld beschreiben und an einem Beispiel planen.', quelle: QUELLE },
  { id: 'de-religion-s9-gestalten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 9, bereich: 'Gestalten & Handeln', code: '', text: 'Die Schülerinnen und Schüler können aus religiösen oder ethischen Überzeugungen begründete Handlungsmöglichkeiten für Gerechtigkeit und Frieden ableiten.', quelle: QUELLE },
  { id: 'de-religion-s11-gestalten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 11, bereich: 'Gestalten & Handeln', code: '', text: 'Die Schülerinnen und Schüler können Konsequenzen religiöser und ethischer Überzeugungen für gesellschaftliche Verantwortung und nachhaltiges Handeln analysieren.', quelle: QUELLE },
  { id: 'de-religion-s13-gestalten-1', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 13, bereich: 'Gestalten & Handeln', code: '', text: 'Die Schülerinnen und Schüler können ein verantwortliches Handlungsprojekt zu einer gesellschaftlichen Herausforderung entwickeln, begründen und kritisch evaluieren.', quelle: QUELLE },
];

export const religionDeStoffItems: StoffItem[] = [
  { id: 'de-rel-wahrnehmen-un', rahmenwerk: 'de-lehrplan', titel: 'Religionen und Weltanschauungen wahrnehmen', fach: 'religion', stufe: 'unterstufe', kategorie: 'Wahrnehmen & Verstehen', deskriptorIds: ['de-religion-s7-wahrnehmen-1', 'de-religion-s9-wahrnehmen-1'], defaultAufgabentypen: ['multipleChoice', 'offeneVerstaendnisfrage'] },
  { id: 'de-rel-deuten-un', rahmenwerk: 'de-lehrplan', titel: 'Religiöse Texte und Deutungen', fach: 'religion', stufe: 'unterstufe', kategorie: 'Deuten & Urteilen', deskriptorIds: ['de-religion-s7-deuten-1', 'de-religion-s9-deuten-1'], defaultAufgabentypen: ['offeneVerstaendnisfrage', 'multipleChoice'] },
  { id: 'de-rel-reflektieren-ob', rahmenwerk: 'de-lehrplan', titel: 'Glaube, Zweifel und Pluralität', fach: 'religion', stufe: 'oberstufe', kategorie: 'Reflektieren & Kommunizieren', deskriptorIds: ['de-religion-s11-reflektieren-1', 'de-religion-s13-reflektieren-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'roleplay'] },
  { id: 'de-rel-gestalten-ob', rahmenwerk: 'de-lehrplan', titel: 'Verantwortung und gesellschaftliches Handeln', fach: 'religion', stufe: 'oberstufe', kategorie: 'Gestalten & Handeln', deskriptorIds: ['de-religion-s11-gestalten-1', 'de-religion-s13-gestalten-1'], defaultAufgabentypen: ['offeneSchreibaufgabe', 'multipleChoice'] },
];
