import type { InhaltsModul } from '@lehrunterlagen/schema';

export const englischDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-englisch-alltag-s6', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 6, titel: 'Everyday Life and Personal World', beschreibung: 'Schule, Familie, Freizeit und Routinen werden in vertrauten Alltagssituationen sprachlich erschlossen.', quelle: 'KMK-Bildungsstandards Erster Schulabschluss (ESA) — kuratierter Entwurf' },
  { id: 'de-englisch-growing-up-s7', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 7, titel: 'Growing up and Identity', beschreibung: 'Jugend, Selbstbild, Freundschaften und Zugehörigkeit werden in persönlichen und medialen Texten reflektiert.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-usa-dream-reality-s9', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 9, titel: 'The USA – dream and reality', beschreibung: 'Amerikanische Gesellschaft, Chancenversprechen und soziale Wirklichkeit werden anhand verschiedener Perspektiven untersucht.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-global-issues-s10', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'unterstufe', schulstufe: 10, titel: 'Global Issues and Sustainability', beschreibung: 'Klimawandel, globale Verantwortung und nachhaltige Lebensweisen werden sprachlich und argumentativ bearbeitet.', quelle: 'KMK-Bildungsstandards Mittlerer Schulabschluss (MSA) — kuratierter Entwurf' },
  { id: 'de-englisch-media-democracy-s12', rahmenwerk: 'de-lehrplan', fach: 'englisch', stufe: 'oberstufe', schulstufe: 12, titel: 'Media, Democracy and Public Debate', beschreibung: 'Medien, politische Kommunikation und öffentliche Debatten werden in anspruchsvollen englischsprachigen Quellen analysiert.', quelle: 'KMK-Bildungsstandards Allgemeine Hochschulreife — kuratierter Entwurf' },
];
