import type { InhaltsModul } from '@lehrunterlagen/schema';

export const franzoesischDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-franzoesisch-alltag-s7', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 7, titel: 'Vie quotidienne et monde personnel', beschreibung: 'Schule, Familie, Freizeit und persönliche Vorlieben werden in einfachen französischen Alltagssituationen ausgedrückt.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-franzoesisch-frankophonie-s8', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 8, titel: 'La francophonie et les cultures', beschreibung: 'Frankophone Regionen, kulturelle Vielfalt und interkulturelle Begegnungen werden sprachlich erschlossen.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-franzoesisch-migration-identitaet-s9', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 9, titel: 'Migration, identité et appartenance', beschreibung: 'Migration, Mehrsprachigkeit und Zugehörigkeit werden anhand persönlicher und gesellschaftlicher Perspektiven diskutiert.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-franzoesisch-medien-gesellschaft-s10', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'unterstufe', schulstufe: 10, titel: 'Médias et société', beschreibung: 'Nachrichten, soziale Medien und gesellschaftliche Fragen werden in französischsprachigen Texten und Gesprächen bearbeitet.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-franzoesisch-literatur-frankophonie-s12', rahmenwerk: 'de-lehrplan', fach: 'franzoesisch', stufe: 'oberstufe', schulstufe: 12, titel: 'Littérature et mondes francophones', beschreibung: 'Literarische Texte aus Frankreich und anderen frankophonen Räumen werden sprachlich, kulturell und historisch interpretiert.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (Allgemeine Hochschulreife) — kuratierter Entwurf' },
];
