import type { InhaltsModul } from '@lehrunterlagen/schema';

export const geographieDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-geographie-deutschland-naturraum-s5', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 5, titel: 'Deutschland: Naturraum und Bundesländer', beschreibung: 'Naturräume, Landschaften und die politische Gliederung Deutschlands werden räumlich eingeordnet.', quelle: 'KMK-Bildungsstandards Geographie für den Mittleren Schulabschluss — kuratierter Entwurf' },
  { id: 'de-geographie-stadt-land-s7', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 7, titel: 'Stadt, Land und räumliche Entwicklung', beschreibung: 'Siedlungsformen, Verstädterung und die Beziehungen zwischen städtischen und ländlichen Räumen werden verglichen.', quelle: 'KMK-Bildungsstandards Geographie für den Mittleren Schulabschluss — kuratierter Entwurf' },
  { id: 'de-geographie-europa-s9', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 9, titel: 'Europa: Räume, Grenzen und Verflechtungen', beschreibung: 'Europäische Naturräume, regionale Unterschiede und grenzüberschreitende Beziehungen werden untersucht.', quelle: 'KMK-Bildungsstandards Geographie + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geographie-globalisierung-disparitaeten-s10', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'unterstufe', schulstufe: 10, titel: 'Globalisierung und Disparitäten', beschreibung: 'Globale Wertschöpfungsketten, ungleiche Entwicklung und die Folgen internationaler Verflechtungen werden analysiert.', quelle: 'KMK-Bildungsstandards Geographie + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geographie-klima-ressourcen-s12', rahmenwerk: 'de-lehrplan', fach: 'geographie', stufe: 'oberstufe', schulstufe: 12, titel: 'Klima, Ressourcen und nachhaltige Raumentwicklung', beschreibung: 'Klimawandel, Ressourcennutzung und Zielkonflikte nachhaltiger Entwicklung werden anhand von Raumbeispielen beurteilt.', quelle: 'KMK-Bildungsstandards Geographie für die Allgemeine Hochschulreife — kuratierter Entwurf' },
];
