import type { InhaltsModul } from '@lehrunterlagen/schema';

export const geschichteDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-geschichte-antike-mittelalter-s6', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 6, titel: 'Antike und Mittelalter', beschreibung: 'Hochkulturen, griechische Polis, Rom, mittelalterliche Herrschaft und Gesellschaft.', quelle: 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geschichte-reformation-revolution-s8', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 8, titel: 'Reformation, Aufklärung und Revolution', beschreibung: 'Konfessionalisierung, Absolutismus, Aufklärung und politische Revolutionen als Umbrüche.', quelle: 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geschichte-industrialisierung-nationalstaat-s9', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 9, titel: 'Industrialisierung und Nationalstaat', beschreibung: 'Wirtschaftlicher Wandel, soziale Frage, Nationalbewegungen und die Entstehung moderner Staaten.', quelle: 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geschichte-ns-teilung-s10', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'unterstufe', schulstufe: 10, titel: 'Nationalsozialismus, Holocaust und deutsche Teilung', beschreibung: 'NS-Herrschaft und Holocaust, Zweiter Weltkrieg, Nachkriegsordnung und Teilung Deutschlands.', quelle: 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-geschichte-europa-gegenwart-s13', rahmenwerk: 'de-lehrplan', fach: 'geschichte', stufe: 'oberstufe', schulstufe: 13, titel: 'Europa, Globalisierung und Erinnerungskultur', beschreibung: 'Deutsche Zeitgeschichte, europäische Integration, globale Verflechtungen und historische Verantwortung.', quelle: 'EPA Geschichte (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
];
