import type { InhaltsModul } from '@lehrunterlagen/schema';

export const italienischDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-italienisch-alltag-s7', rahmenwerk: 'de-lehrplan', fach: 'italienisch', stufe: 'unterstufe', schulstufe: 7, titel: 'Vita quotidiana e mondo personale', beschreibung: 'Schule, Familie, Freizeit und persönliche Vorlieben werden in vertrauten italienischen Alltagssituationen ausgedrückt.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-italienisch-regionen-kultur-s8', rahmenwerk: 'de-lehrplan', fach: 'italienisch', stufe: 'unterstufe', schulstufe: 8, titel: 'Regioni e cultura italiana', beschreibung: 'Italienische Regionen, Alltagskultur und kulturelle Vielfalt werden anhand landeskundlicher Materialien erschlossen.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-italienisch-migration-identitaet-s9', rahmenwerk: 'de-lehrplan', fach: 'italienisch', stufe: 'unterstufe', schulstufe: 9, titel: 'Migrazione, identità e società', beschreibung: 'Migration, Mehrsprachigkeit und gesellschaftliche Zugehörigkeit werden in italienischsprachigen Perspektiven untersucht.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-italienisch-medien-gesellschaft-s10', rahmenwerk: 'de-lehrplan', fach: 'italienisch', stufe: 'unterstufe', schulstufe: 10, titel: 'Media e società', beschreibung: 'Digitale Kommunikation, Nachrichten und gesellschaftliche Debatten werden sprachlich und kritisch bearbeitet.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-italienisch-letteratura-s12', rahmenwerk: 'de-lehrplan', fach: 'italienisch', stufe: 'oberstufe', schulstufe: 12, titel: 'Letteratura e memoria', beschreibung: 'Italienische Literatur und Erinnerungskultur werden in ihrem sprachlichen, historischen und gesellschaftlichen Zusammenhang interpretiert.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (Allgemeine Hochschulreife) — kuratierter Entwurf' },
];
