import type { InhaltsModul } from '@lehrunterlagen/schema';

export const lateinDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-latein-grundlagen-s6', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'unterstufe', schulstufe: 6, titel: 'Grundlagen der lateinischen Sprache', beschreibung: 'Formenlehre, Satzbau und grundlegende Übersetzungsstrategien werden an einfachen lateinischen Texten eingeübt.', quelle: 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-latein-roemischer-alltag-s7', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'unterstufe', schulstufe: 7, titel: 'Römisches Alltagsleben', beschreibung: 'Familie, Schule, Wohnen, Sklaverei und öffentliche Räume werden aus lateinischen Texten und Sachquellen erschlossen.', quelle: 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-latein-republik-imperium-s8', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'unterstufe', schulstufe: 8, titel: 'Römische Republik und Imperium', beschreibung: 'Politische Ordnung, Expansion und Herrschaft des römischen Staates werden an historischen Texten untersucht.', quelle: 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-latein-rhetorik-cicero-s11', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 11, titel: 'Rhetorik: Cicero', beschreibung: 'Ciceros Reden werden hinsichtlich Argumentation, Stilmitteln, Adressatenbezug und politischem Kontext analysiert.', quelle: 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
  { id: 'de-latein-philosophie-s12', rahmenwerk: 'de-lehrplan', fach: 'latein', stufe: 'oberstufe', schulstufe: 12, titel: 'Philosophie: Seneca und die Stoa', beschreibung: 'Senecas Überlegungen zu Lebensführung, Freiheit und Verantwortung werden übersetzt und philosophisch eingeordnet.', quelle: 'EPA Latein (KMK) + länderübergreifender Lehrplan-Kern — kuratierter Entwurf' },
];
