import type { InhaltsModul } from '@lehrunterlagen/schema';

export const philosophieDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-philosophie-erkenntnis-s11', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, titel: 'Erkenntnis und Wahrheit', beschreibung: 'Quellen, Grenzen und Kriterien von Wissen werden anhand klassischer erkenntnistheoretischer Positionen geprüft.', quelle: 'Länderübergreifender Lehrplan-Kern Philosophie — kuratierter Entwurf' },
  { id: 'de-philosophie-ethik-s11', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 11, titel: 'Ethik und moralische Urteile', beschreibung: 'Pflichtethik, Utilitarismus und Tugendethik werden verglichen und auf konkrete moralische Konflikte angewendet.', quelle: 'Länderübergreifender Lehrplan-Kern Philosophie — kuratierter Entwurf' },
  { id: 'de-philosophie-politik-s12', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, titel: 'Politische Philosophie', beschreibung: 'Freiheit, Gerechtigkeit, Demokratie und die Legitimation staatlicher Ordnung werden argumentativ untersucht.', quelle: 'Länderübergreifender Lehrplan-Kern Philosophie — kuratierter Entwurf' },
  { id: 'de-philosophie-mensch-technik-s12', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 12, titel: 'Menschenbild und Technik', beschreibung: 'Vorstellungen vom Menschen und ihre Bedeutung für Digitalisierung, KI und technische Selbstgestaltung werden reflektiert.', quelle: 'Länderübergreifender Lehrplan-Kern Philosophie — kuratierter Entwurf' },
  { id: 'de-philosophie-wissenschaft-s13', rahmenwerk: 'de-lehrplan', fach: 'philosophie', stufe: 'oberstufe', schulstufe: 13, titel: 'Wissenschaft, Sprache und Wirklichkeit', beschreibung: 'Wissenschaftliche Erklärung, Sprache und die Konstruktion von Wirklichkeit werden anhand philosophischer Argumente beurteilt.', quelle: 'Länderübergreifender Lehrplan-Kern Philosophie für die Sekundarstufe II — kuratierter Entwurf' },
];
