import type { InhaltsModul } from '@lehrunterlagen/schema';

export const psychologieDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-psychologie-grundlagen-methoden-s11', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, titel: 'Grundlagen und Methoden der Psychologie', beschreibung: 'Wahrnehmung, Denken, Gedächtnis und grundlegende psychologische Forschungsmethoden werden eingeführt.', quelle: 'Länderübergreifender Lehrplan-Kern Psychologie — kuratierter Entwurf' },
  { id: 'de-psychologie-entwicklung-jugend-s11', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 11, titel: 'Entwicklungspsychologie und Jugend', beschreibung: 'Entwicklung in Kindheit und Jugend wird unter biologischen, kognitiven und psychosozialen Gesichtspunkten betrachtet.', quelle: 'Länderübergreifender Lehrplan-Kern Psychologie — kuratierter Entwurf' },
  { id: 'de-psychologie-sozialpsychologie-s12', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, titel: 'Sozialpsychologie', beschreibung: 'Gruppenprozesse, Konformität, Vorurteile und prosoziales Verhalten werden anhand von Studien und Alltagssituationen analysiert.', quelle: 'Länderübergreifender Lehrplan-Kern Psychologie — kuratierter Entwurf' },
  { id: 'de-psychologie-lernen-motivation-s12', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 12, titel: 'Lernen, Motivation und Emotion', beschreibung: 'Lernprozesse, Motivation und Emotionen werden mit psychologischen Modellen erklärt und auf schulische Situationen bezogen.', quelle: 'Länderübergreifender Lehrplan-Kern Psychologie — kuratierter Entwurf' },
  { id: 'de-psychologie-gesundheit-medien-s13', rahmenwerk: 'de-lehrplan', fach: 'psychologie', stufe: 'oberstufe', schulstufe: 13, titel: 'Psychische Gesundheit und digitale Lebenswelten', beschreibung: 'Stress, Resilienz und psychische Gesundheit werden im Zusammenhang mit Mediennutzung und sozialen Beziehungen reflektiert.', quelle: 'Länderübergreifender Lehrplan-Kern Psychologie für die Sekundarstufe II — kuratierter Entwurf' },
];
