import type { InhaltsModul } from '@lehrunterlagen/schema';

export const religionDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-religion-identitaet-vielfalt-s5', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 5, titel: 'Identität, Gemeinschaft und religiöse Vielfalt', beschreibung: 'Eigene Zugehörigkeiten, religiöse Ausdrucksformen und respektvolle Begegnung werden im schulischen Alltag erschlossen.', quelle: 'Länderübergreifender Lehrplan-Kern Religionsunterricht — kuratierter Entwurf' },
  { id: 'de-religion-bibel-auslegung-s7', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 7, titel: 'Bibel und religiöse Auslegung', beschreibung: 'Biblische Texte, ihre Entstehung und unterschiedliche Auslegungen werden sachgerecht gelesen und verglichen.', quelle: 'Länderübergreifender Lehrplan-Kern Religionsunterricht — kuratierter Entwurf' },
  { id: 'de-religion-weltreligionen-dialog-s8', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 8, titel: 'Weltreligionen und Dialog', beschreibung: 'Judentum, Christentum, Islam und weitere religiöse Traditionen werden in ihren Gemeinsamkeiten und Unterschieden betrachtet.', quelle: 'Länderübergreifender Lehrplan-Kern Religionsunterricht — kuratierter Entwurf' },
  { id: 'de-religion-gesellschaft-s10', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'unterstufe', schulstufe: 10, titel: 'Religion in Gesellschaft und Öffentlichkeit', beschreibung: 'Religiöse Pluralität, Säkularisierung und die Rolle von Religion im demokratischen Gemeinwesen werden diskutiert.', quelle: 'Länderübergreifender Lehrplan-Kern Religionsunterricht — kuratierter Entwurf' },
  { id: 'de-religion-sinn-verantwortung-s12', rahmenwerk: 'de-lehrplan', fach: 'religion', stufe: 'oberstufe', schulstufe: 12, titel: 'Sinn, Verantwortung und Hoffnung', beschreibung: 'Fragen nach Leid, Tod, Hoffnung und verantwortlichem Handeln werden aus religiösen und weltanschaulichen Perspektiven reflektiert.', quelle: 'Länderübergreifender Lehrplan-Kern Religionsunterricht für die Sekundarstufe II — kuratierter Entwurf' },
];
