import type { InhaltsModul } from '@lehrunterlagen/schema';

export const spanischDeInhaltsModule: InhaltsModul[] = [
  { id: 'de-spanisch-alltag-s7', rahmenwerk: 'de-lehrplan', fach: 'spanisch', stufe: 'unterstufe', schulstufe: 7, titel: 'Vida cotidiana y mundo personal', beschreibung: 'Schule, Familie, Freizeit und persönliche Vorlieben werden in vertrauten spanischen Alltagssituationen ausgedrückt.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-spanisch-hispanophone-welten-s8', rahmenwerk: 'de-lehrplan', fach: 'spanisch', stufe: 'unterstufe', schulstufe: 8, titel: 'Mundos hispanohablantes', beschreibung: 'Spanien und Lateinamerika werden als vielfältige Sprach- und Kulturräume mit unterschiedlichen Perspektiven erschlossen.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-spanisch-migration-identitaet-s9', rahmenwerk: 'de-lehrplan', fach: 'spanisch', stufe: 'unterstufe', schulstufe: 9, titel: 'Migración, identidad y convivencia', beschreibung: 'Migration, Identität und Zusammenleben werden anhand spanischsprachiger Erfahrungsberichte und Sachtexte diskutiert.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-spanisch-umwelt-zukunft-s10', rahmenwerk: 'de-lehrplan', fach: 'spanisch', stufe: 'unterstufe', schulstufe: 10, titel: 'Medio ambiente y futuro', beschreibung: 'Umwelt, Klimaschutz und Zukunftsfragen werden in argumentierenden spanischen Texten und Gesprächen bearbeitet.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (MSA) — kuratierter Entwurf' },
  { id: 'de-spanisch-literatur-gesellschaft-s12', rahmenwerk: 'de-lehrplan', fach: 'spanisch', stufe: 'oberstufe', schulstufe: 12, titel: 'Literatura y sociedad', beschreibung: 'Literarische Texte und gesellschaftliche Debatten aus der spanischsprachigen Welt werden differenziert analysiert.', quelle: 'KMK-Bildungsstandards fortgeführte Fremdsprachen (Allgemeine Hochschulreife) — kuratierter Entwurf' },
];
